// Code generated by ent, DO NOT EDIT.

package review

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the review type in the database.
	Label = "review"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrNumber holds the string denoting the pr_number field in the database.
	FieldPrNumber = "pr_number"
	// FieldPrTitle holds the string denoting the pr_title field in the database.
	FieldPrTitle = "pr_title"
	// FieldPrAuthor holds the string denoting the pr_author field in the database.
	FieldPrAuthor = "pr_author"
	// FieldHeadSha holds the string denoting the head_sha field in the database.
	FieldHeadSha = "head_sha"
	// FieldBaseSha holds the string denoting the base_sha field in the database.
	FieldBaseSha = "base_sha"
	// FieldGithubReviewID holds the string denoting the github_review_id field in the database.
	FieldGithubReviewID = "github_review_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldTokenUsage holds the string denoting the token_usage field in the database.
	FieldTokenUsage = "token_usage"
	// FieldTrigger holds the string denoting the trigger field in the database.
	FieldTrigger = "trigger"
	// FieldTriggeredBy holds the string denoting the triggered_by field in the database.
	FieldTriggeredBy = "triggered_by"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// EdgeRepo holds the string denoting the repo edge name in mutations.
	EdgeRepo = "repo"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgePipelineStates holds the string denoting the pipeline_states edge name in mutations.
	EdgePipelineStates = "pipeline_states"
	// Table holds the table name of the review in the database.
	Table = "reviews"
	// RepoTable is the table that holds the repo relation/edge.
	RepoTable = "reviews"
	// RepoInverseTable is the table name for the Repo entity.
	// It exists in this package in order to avoid circular dependency with the "repo" package.
	RepoInverseTable = "repos"
	// RepoColumn is the table column denoting the repo relation/edge.
	RepoColumn = "repo_reviews"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "review_comments"
	// CommentsInverseTable is the table name for the ReviewComment entity.
	// It exists in this package in order to avoid circular dependency with the "reviewcomment" package.
	CommentsInverseTable = "review_comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "review_comments"
	// PipelineStatesTable is the table that holds the pipeline_states relation/edge.
	PipelineStatesTable = "pipeline_states"
	// PipelineStatesInverseTable is the table name for the PipelineState entity.
	// It exists in this package in order to avoid circular dependency with the "pipelinestate" package.
	PipelineStatesInverseTable = "pipeline_states"
	// PipelineStatesColumn is the table column denoting the pipeline_states relation/edge.
	PipelineStatesColumn = "review_pipeline_states"
)

// Columns holds all SQL columns for review fields.
var Columns = []string{
	FieldID,
	FieldPrNumber,
	FieldPrTitle,
	FieldPrAuthor,
	FieldHeadSha,
	FieldBaseSha,
	FieldGithubReviewID,
	FieldStatus,
	FieldSummary,
	FieldScore,
	FieldTokenUsage,
	FieldTrigger,
	FieldTriggeredBy,
	FieldDurationMs,
	FieldError,
	FieldCreatedAt,
	FieldCompletedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "reviews"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"repo_reviews",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending    Status = "pending"
	StatusInProgress Status = "in_progress"
	StatusCompleted  Status = "completed"
	StatusFailed     Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusInProgress, StatusCompleted, StatusFailed:
		return nil
	default:
		return fmt.Errorf("review: invalid enum value for status field: %q", s)
	}
}

// Trigger defines the type for the "trigger" enum field.
type Trigger string

// TriggerWebhook is the default value of the Trigger enum.
const DefaultTrigger = TriggerWebhook

// Trigger values.
const (
	TriggerWebhook Trigger = "webhook"
	TriggerManual  Trigger = "manual"
)

func (t Trigger) String() string {
	return string(t)
}

// TriggerValidator is a validator for the "trigger" field enum values. It is called by the builders before save.
func TriggerValidator(t Trigger) error {
	switch t {
	case TriggerWebhook, TriggerManual:
		return nil
	default:
		return fmt.Errorf("review: invalid enum value for trigger field: %q", t)
	}
}

// OrderOption defines the ordering options for the Review queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrNumber orders the results by the pr_number field.
func ByPrNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrNumber, opts...).ToFunc()
}

// ByPrTitle orders the results by the pr_title field.
func ByPrTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrTitle, opts...).ToFunc()
}

// ByPrAuthor orders the results by the pr_author field.
func ByPrAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrAuthor, opts...).ToFunc()
}

// ByHeadSha orders the results by the head_sha field.
func ByHeadSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadSha, opts...).ToFunc()
}

// ByBaseSha orders the results by the base_sha field.
func ByBaseSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseSha, opts...).ToFunc()
}

// ByGithubReviewID orders the results by the github_review_id field.
func ByGithubReviewID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubReviewID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByTrigger orders the results by the trigger field.
func ByTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrigger, opts...).ToFunc()
}

// ByTriggeredBy orders the results by the triggered_by field.
func ByTriggeredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggeredBy, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByRepoField orders the results by repo field.
func ByRepoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRepoStep(), sql.OrderByField(field, opts...))
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPipelineStatesCount orders the results by pipeline_states count.
func ByPipelineStatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPipelineStatesStep(), opts...)
	}
}

// ByPipelineStates orders the results by pipeline_states terms.
func ByPipelineStates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPipelineStatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRepoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RepoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RepoTable, RepoColumn),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
	)
}
func newPipelineStatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PipelineStatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PipelineStatesTable, PipelineStatesColumn),
	)
}
