ALTER TABLE code_nodes ADD COLUMN IF NOT EXISTS return_type TEXT DEFAULT '';
ALTER TABLE code_nodes ADD COLUMN IF NOT EXISTS params TEXT DEFAULT '';
ALTER TABLE code_nodes ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT '';
ALTER TABLE code_nodes ADD COLUMN IF NOT EXISTS is_async BOOLEAN DEFAULT false;
ALTER TABLE code_nodes ADD COLUMN IF NOT EXISTS receiver_type TEXT DEFAULT '';
ALTER TABLE code_nodes ADD COLUMN IF NOT EXISTS scope TEXT DEFAULT '';
