// Code generated by ent, DO NOT EDIT.

package installation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the installation type in the database.
	Label = "installation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstallationID holds the string denoting the installation_id field in the database.
	FieldInstallationID = "installation_id"
	// FieldOrgLogin holds the string denoting the org_login field in the database.
	FieldOrgLogin = "org_login"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldSuspendedAt holds the string denoting the suspended_at field in the database.
	FieldSuspendedAt = "suspended_at"
	// EdgeRepos holds the string denoting the repos edge name in mutations.
	EdgeRepos = "repos"
	// Table holds the table name of the installation in the database.
	Table = "installations"
	// ReposTable is the table that holds the repos relation/edge.
	ReposTable = "repos"
	// ReposInverseTable is the table name for the Repo entity.
	// It exists in this package in order to avoid circular dependency with the "repo" package.
	ReposInverseTable = "repos"
	// ReposColumn is the table column denoting the repos relation/edge.
	ReposColumn = "installation_repos"
)

// Columns holds all SQL columns for installation fields.
var Columns = []string{
	FieldID,
	FieldInstallationID,
	FieldOrgLogin,
	FieldCreatedAt,
	FieldSuspendedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Installation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstallationID orders the results by the installation_id field.
func ByInstallationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallationID, opts...).ToFunc()
}

// ByOrgLogin orders the results by the org_login field.
func ByOrgLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgLogin, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySuspendedAt orders the results by the suspended_at field.
func BySuspendedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuspendedAt, opts...).ToFunc()
}

// ByReposCount orders the results by repos count.
func ByReposCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReposStep(), opts...)
	}
}

// ByRepos orders the results by repos terms.
func ByRepos(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReposStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newReposStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReposInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReposTable, ReposColumn),
	)
}
