// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActivityLogsColumns holds the columns for the "activity_logs" table.
	ActivityLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "action", Type: field.TypeString},
		{Name: "actor", Type: field.TypeString, Nullable: true},
		{Name: "resource", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ActivityLogsTable holds the schema information for the "activity_logs" table.
	ActivityLogsTable = &schema.Table{
		Name:       "activity_logs",
		Columns:    ActivityLogsColumns,
		PrimaryKey: []*schema.Column{ActivityLogsColumns[0]},
	}
	// InstallationsColumns holds the columns for the "installations" table.
	InstallationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "installation_id", Type: field.TypeInt64, Unique: true},
		{Name: "org_login", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "suspended_at", Type: field.TypeTime, Nullable: true},
	}
	// InstallationsTable holds the schema information for the "installations" table.
	InstallationsTable = &schema.Table{
		Name:       "installations",
		Columns:    InstallationsColumns,
		PrimaryKey: []*schema.Column{InstallationsColumns[0]},
	}
	// ModelConfigsColumns holds the columns for the "model_configs" table.
	ModelConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "stage", Type: field.TypeEnum, Enums: []string{"triage", "review", "synthesis", "embedding"}},
		{Name: "provider", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "base_url", Type: field.TypeString, Nullable: true},
		{Name: "max_tokens", Type: field.TypeInt, Default: 4096},
		{Name: "temperature", Type: field.TypeFloat32, Default: 0.2},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "repo_model_configs", Type: field.TypeInt, Nullable: true},
	}
	// ModelConfigsTable holds the schema information for the "model_configs" table.
	ModelConfigsTable = &schema.Table{
		Name:       "model_configs",
		Columns:    ModelConfigsColumns,
		PrimaryKey: []*schema.Column{ModelConfigsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "model_configs_repos_model_configs",
				Columns:    []*schema.Column{ModelConfigsColumns[9]},
				RefColumns: []*schema.Column{ReposColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "modelconfig_stage_repo_model_configs",
				Unique:  true,
				Columns: []*schema.Column{ModelConfigsColumns[1], ModelConfigsColumns[9]},
			},
		},
	}
	// PipelineStatesColumns holds the columns for the "pipeline_states" table.
	PipelineStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "state", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "review_pipeline_states", Type: field.TypeUUID},
	}
	// PipelineStatesTable holds the schema information for the "pipeline_states" table.
	PipelineStatesTable = &schema.Table{
		Name:       "pipeline_states",
		Columns:    PipelineStatesColumns,
		PrimaryKey: []*schema.Column{PipelineStatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pipeline_states_reviews_pipeline_states",
				Columns:    []*schema.Column{PipelineStatesColumns[6]},
				RefColumns: []*schema.Column{ReviewsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ReposColumns holds the columns for the "repos" table.
	ReposColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "github_id", Type: field.TypeInt64, Unique: true},
		{Name: "full_name", Type: field.TypeString},
		{Name: "default_branch", Type: field.TypeString, Default: "main"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "settings_json", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "installation_repos", Type: field.TypeInt},
	}
	// ReposTable holds the schema information for the "repos" table.
	ReposTable = &schema.Table{
		Name:       "repos",
		Columns:    ReposColumns,
		PrimaryKey: []*schema.Column{ReposColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "repos_installations_repos",
				Columns:    []*schema.Column{ReposColumns[8]},
				RefColumns: []*schema.Column{InstallationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ReviewsColumns holds the columns for the "reviews" table.
	ReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "pr_number", Type: field.TypeInt},
		{Name: "pr_title", Type: field.TypeString},
		{Name: "pr_author", Type: field.TypeString},
		{Name: "head_sha", Type: field.TypeString},
		{Name: "base_sha", Type: field.TypeString},
		{Name: "github_review_id", Type: field.TypeInt64, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "in_progress", "completed", "failed"}, Default: "pending"},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "score", Type: field.TypeInt, Nullable: true},
		{Name: "token_usage", Type: field.TypeJSON, Nullable: true},
		{Name: "trigger", Type: field.TypeEnum, Enums: []string{"webhook", "manual"}, Default: "webhook"},
		{Name: "triggered_by", Type: field.TypeString, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "repo_reviews", Type: field.TypeInt},
	}
	// ReviewsTable holds the schema information for the "reviews" table.
	ReviewsTable = &schema.Table{
		Name:       "reviews",
		Columns:    ReviewsColumns,
		PrimaryKey: []*schema.Column{ReviewsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reviews_repos_reviews",
				Columns:    []*schema.Column{ReviewsColumns[17]},
				RefColumns: []*schema.Column{ReposColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ReviewCommentsColumns holds the columns for the "review_comments" table.
	ReviewCommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "file_path", Type: field.TypeString},
		{Name: "start_line", Type: field.TypeInt, Nullable: true},
		{Name: "end_line", Type: field.TypeInt, Nullable: true},
		{Name: "side", Type: field.TypeEnum, Nullable: true, Enums: []string{"LEFT", "RIGHT"}},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "severity", Type: field.TypeEnum, Nullable: true, Enums: []string{"critical", "warning", "suggestion", "praise"}},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "review_comments", Type: field.TypeUUID},
	}
	// ReviewCommentsTable holds the schema information for the "review_comments" table.
	ReviewCommentsTable = &schema.Table{
		Name:       "review_comments",
		Columns:    ReviewCommentsColumns,
		PrimaryKey: []*schema.Column{ReviewCommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "review_comments_reviews_comments",
				Columns:    []*schema.Column{ReviewCommentsColumns[9]},
				RefColumns: []*schema.Column{ReviewsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RulesColumns holds the columns for the "rules" table.
	RulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "category", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RulesTable holds the schema information for the "rules" table.
	RulesTable = &schema.Table{
		Name:       "rules",
		Columns:    RulesColumns,
		PrimaryKey: []*schema.Column{RulesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActivityLogsTable,
		InstallationsTable,
		ModelConfigsTable,
		PipelineStatesTable,
		ReposTable,
		ReviewsTable,
		ReviewCommentsTable,
		RulesTable,
	}
)

func init() {
	ModelConfigsTable.ForeignKeys[0].RefTable = ReposTable
	PipelineStatesTable.ForeignKeys[0].RefTable = ReviewsTable
	ReposTable.ForeignKeys[0].RefTable = InstallationsTable
	ReviewsTable.ForeignKeys[0].RefTable = ReposTable
	ReviewCommentsTable.ForeignKeys[0].RefTable = ReviewsTable
}
