// Code generated by ent, DO NOT EDIT.

package modelconfig

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelconfig type in the database.
	Label = "model_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStage holds the string denoting the stage field in the database.
	FieldStage = "stage"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldMaxTokens holds the string denoting the max_tokens field in the database.
	FieldMaxTokens = "max_tokens"
	// FieldTemperature holds the string denoting the temperature field in the database.
	FieldTemperature = "temperature"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRepo holds the string denoting the repo edge name in mutations.
	EdgeRepo = "repo"
	// Table holds the table name of the modelconfig in the database.
	Table = "model_configs"
	// RepoTable is the table that holds the repo relation/edge.
	RepoTable = "model_configs"
	// RepoInverseTable is the table name for the Repo entity.
	// It exists in this package in order to avoid circular dependency with the "repo" package.
	RepoInverseTable = "repos"
	// RepoColumn is the table column denoting the repo relation/edge.
	RepoColumn = "repo_model_configs"
)

// Columns holds all SQL columns for modelconfig fields.
var Columns = []string{
	FieldID,
	FieldStage,
	FieldProvider,
	FieldModel,
	FieldBaseURL,
	FieldMaxTokens,
	FieldTemperature,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "model_configs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"repo_model_configs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMaxTokens holds the default value on creation for the "max_tokens" field.
	DefaultMaxTokens int
	// DefaultTemperature holds the default value on creation for the "temperature" field.
	DefaultTemperature float32
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Stage defines the type for the "stage" enum field.
type Stage string

// Stage values.
const (
	StageTriage    Stage = "triage"
	StageReview    Stage = "review"
	StageSynthesis Stage = "synthesis"
	StageEmbedding Stage = "embedding"
)

func (s Stage) String() string {
	return string(s)
}

// StageValidator is a validator for the "stage" field enum values. It is called by the builders before save.
func StageValidator(s Stage) error {
	switch s {
	case StageTriage, StageReview, StageSynthesis, StageEmbedding:
		return nil
	default:
		return fmt.Errorf("modelconfig: invalid enum value for stage field: %q", s)
	}
}

// OrderOption defines the ordering options for the ModelConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStage orders the results by the stage field.
func ByStage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStage, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByMaxTokens orders the results by the max_tokens field.
func ByMaxTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTokens, opts...).ToFunc()
}

// ByTemperature orders the results by the temperature field.
func ByTemperature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemperature, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRepoField orders the results by repo field.
func ByRepoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRepoStep(), sql.OrderByField(field, opts...))
	}
}
func newRepoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RepoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RepoTable, RepoColumn),
	)
}
