// Code generated by ent, DO NOT EDIT.

package modelconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/acmeorg/argus/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldProvider, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldModel, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldBaseURL, v))
}

// MaxTokens applies equality check predicate on the "max_tokens" field. It's identical to MaxTokensEQ.
func MaxTokens(v int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldMaxTokens, v))
}

// Temperature applies equality check predicate on the "temperature" field. It's identical to TemperatureEQ.
func Temperature(v float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldTemperature, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v Stage) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v Stage) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...Stage) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...Stage) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldStage, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldContainsFold(FieldProvider, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldContainsFold(FieldModel, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLIsNil applies the IsNil predicate on the "base_url" field.
func BaseURLIsNil() predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIsNull(FieldBaseURL))
}

// BaseURLNotNil applies the NotNil predicate on the "base_url" field.
func BaseURLNotNil() predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotNull(FieldBaseURL))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldContainsFold(FieldBaseURL, v))
}

// MaxTokensEQ applies the EQ predicate on the "max_tokens" field.
func MaxTokensEQ(v int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldMaxTokens, v))
}

// MaxTokensNEQ applies the NEQ predicate on the "max_tokens" field.
func MaxTokensNEQ(v int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldMaxTokens, v))
}

// MaxTokensIn applies the In predicate on the "max_tokens" field.
func MaxTokensIn(vs ...int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldMaxTokens, vs...))
}

// MaxTokensNotIn applies the NotIn predicate on the "max_tokens" field.
func MaxTokensNotIn(vs ...int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldMaxTokens, vs...))
}

// MaxTokensGT applies the GT predicate on the "max_tokens" field.
func MaxTokensGT(v int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGT(FieldMaxTokens, v))
}

// MaxTokensGTE applies the GTE predicate on the "max_tokens" field.
func MaxTokensGTE(v int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGTE(FieldMaxTokens, v))
}

// MaxTokensLT applies the LT predicate on the "max_tokens" field.
func MaxTokensLT(v int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLT(FieldMaxTokens, v))
}

// MaxTokensLTE applies the LTE predicate on the "max_tokens" field.
func MaxTokensLTE(v int) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLTE(FieldMaxTokens, v))
}

// TemperatureEQ applies the EQ predicate on the "temperature" field.
func TemperatureEQ(v float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldTemperature, v))
}

// TemperatureNEQ applies the NEQ predicate on the "temperature" field.
func TemperatureNEQ(v float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldTemperature, v))
}

// TemperatureIn applies the In predicate on the "temperature" field.
func TemperatureIn(vs ...float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldTemperature, vs...))
}

// TemperatureNotIn applies the NotIn predicate on the "temperature" field.
func TemperatureNotIn(vs ...float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldTemperature, vs...))
}

// TemperatureGT applies the GT predicate on the "temperature" field.
func TemperatureGT(v float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGT(FieldTemperature, v))
}

// TemperatureGTE applies the GTE predicate on the "temperature" field.
func TemperatureGTE(v float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGTE(FieldTemperature, v))
}

// TemperatureLT applies the LT predicate on the "temperature" field.
func TemperatureLT(v float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLT(FieldTemperature, v))
}

// TemperatureLTE applies the LTE predicate on the "temperature" field.
func TemperatureLTE(v float32) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLTE(FieldTemperature, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelConfig {
	return predicate.ModelConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasRepo applies the HasEdge predicate on the "repo" edge.
func HasRepo() predicate.ModelConfig {
	return predicate.ModelConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepoTable, RepoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepoWith applies the HasEdge predicate on the "repo" edge with a given conditions (other predicates).
func HasRepoWith(preds ...predicate.Repo) predicate.ModelConfig {
	return predicate.ModelConfig(func(s *sql.Selector) {
		step := newRepoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelConfig) predicate.ModelConfig {
	return predicate.ModelConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelConfig) predicate.ModelConfig {
	return predicate.ModelConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelConfig) predicate.ModelConfig {
	return predicate.ModelConfig(sql.NotPredicates(p))
}
