// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/acmeorg/argus/ent/activitylog"
)

// ActivityLog is the model entity for the ActivityLog schema.
type ActivityLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Actor holds the value of the "actor" field.
	Actor *string `json:"actor,omitempty"`
	// Resource holds the value of the "resource" field.
	Resource *string `json:"resource,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActivityLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case activitylog.FieldMetadata:
			values[i] = new([]byte)
		case activitylog.FieldID:
			values[i] = new(sql.NullInt64)
		case activitylog.FieldAction, activitylog.FieldActor, activitylog.FieldResource:
			values[i] = new(sql.NullString)
		case activitylog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActivityLog fields.
func (_m *ActivityLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case activitylog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case activitylog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case activitylog.FieldActor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor", values[i])
			} else if value.Valid {
				_m.Actor = new(string)
				*_m.Actor = value.String
			}
		case activitylog.FieldResource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource", values[i])
			} else if value.Valid {
				_m.Resource = new(string)
				*_m.Resource = value.String
			}
		case activitylog.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case activitylog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActivityLog.
// This includes values selected through modifiers, order, etc.
func (_m *ActivityLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ActivityLog.
// Note that you need to call ActivityLog.Unwrap() before calling this method if this ActivityLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActivityLog) Update() *ActivityLogUpdateOne {
	return NewActivityLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActivityLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActivityLog) Unwrap() *ActivityLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActivityLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActivityLog) String() string {
	var builder strings.Builder
	builder.WriteString("ActivityLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	if v := _m.Actor; v != nil {
		builder.WriteString("actor=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Resource; v != nil {
		builder.WriteString("resource=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ActivityLogs is a parsable slice of ActivityLog.
type ActivityLogs []*ActivityLog
