// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/BeLazy167/argus/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/BeLazy167/argus/ent/activitylog"
	"github.com/BeLazy167/argus/ent/installation"
	"github.com/BeLazy167/argus/ent/modelconfig"
	"github.com/BeLazy167/argus/ent/pipelinestate"
	"github.com/BeLazy167/argus/ent/repo"
	"github.com/BeLazy167/argus/ent/review"
	"github.com/BeLazy167/argus/ent/reviewcomment"
	"github.com/BeLazy167/argus/ent/rule"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ActivityLog is the client for interacting with the ActivityLog builders.
	ActivityLog *ActivityLogClient
	// Installation is the client for interacting with the Installation builders.
	Installation *InstallationClient
	// ModelConfig is the client for interacting with the ModelConfig builders.
	ModelConfig *ModelConfigClient
	// PipelineState is the client for interacting with the PipelineState builders.
	PipelineState *PipelineStateClient
	// Repo is the client for interacting with the Repo builders.
	Repo *RepoClient
	// Review is the client for interacting with the Review builders.
	Review *ReviewClient
	// ReviewComment is the client for interacting with the ReviewComment builders.
	ReviewComment *ReviewCommentClient
	// Rule is the client for interacting with the Rule builders.
	Rule *RuleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ActivityLog = NewActivityLogClient(c.config)
	c.Installation = NewInstallationClient(c.config)
	c.ModelConfig = NewModelConfigClient(c.config)
	c.PipelineState = NewPipelineStateClient(c.config)
	c.Repo = NewRepoClient(c.config)
	c.Review = NewReviewClient(c.config)
	c.ReviewComment = NewReviewCommentClient(c.config)
	c.Rule = NewRuleClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		ActivityLog:   NewActivityLogClient(cfg),
		Installation:  NewInstallationClient(cfg),
		ModelConfig:   NewModelConfigClient(cfg),
		PipelineState: NewPipelineStateClient(cfg),
		Repo:          NewRepoClient(cfg),
		Review:        NewReviewClient(cfg),
		ReviewComment: NewReviewCommentClient(cfg),
		Rule:          NewRuleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		ActivityLog:   NewActivityLogClient(cfg),
		Installation:  NewInstallationClient(cfg),
		ModelConfig:   NewModelConfigClient(cfg),
		PipelineState: NewPipelineStateClient(cfg),
		Repo:          NewRepoClient(cfg),
		Review:        NewReviewClient(cfg),
		ReviewComment: NewReviewCommentClient(cfg),
		Rule:          NewRuleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ActivityLog.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.ActivityLog, c.Installation, c.ModelConfig, c.PipelineState, c.Repo, c.Review,
		c.ReviewComment, c.Rule,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.ActivityLog, c.Installation, c.ModelConfig, c.PipelineState, c.Repo, c.Review,
		c.ReviewComment, c.Rule,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ActivityLogMutation:
		return c.ActivityLog.mutate(ctx, m)
	case *InstallationMutation:
		return c.Installation.mutate(ctx, m)
	case *ModelConfigMutation:
		return c.ModelConfig.mutate(ctx, m)
	case *PipelineStateMutation:
		return c.PipelineState.mutate(ctx, m)
	case *RepoMutation:
		return c.Repo.mutate(ctx, m)
	case *ReviewMutation:
		return c.Review.mutate(ctx, m)
	case *ReviewCommentMutation:
		return c.ReviewComment.mutate(ctx, m)
	case *RuleMutation:
		return c.Rule.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ActivityLogClient is a client for the ActivityLog schema.
type ActivityLogClient struct {
	config
}

// NewActivityLogClient returns a client for the ActivityLog from the given config.
func NewActivityLogClient(c config) *ActivityLogClient {
	return &ActivityLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `activitylog.Hooks(f(g(h())))`.
func (c *ActivityLogClient) Use(hooks ...Hook) {
	c.hooks.ActivityLog = append(c.hooks.ActivityLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `activitylog.Intercept(f(g(h())))`.
func (c *ActivityLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.ActivityLog = append(c.inters.ActivityLog, interceptors...)
}

// Create returns a builder for creating a ActivityLog entity.
func (c *ActivityLogClient) Create() *ActivityLogCreate {
	mutation := newActivityLogMutation(c.config, OpCreate)
	return &ActivityLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ActivityLog entities.
func (c *ActivityLogClient) CreateBulk(builders ...*ActivityLogCreate) *ActivityLogCreateBulk {
	return &ActivityLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ActivityLogClient) MapCreateBulk(slice any, setFunc func(*ActivityLogCreate, int)) *ActivityLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ActivityLogCreateBulk{err: fmt.Errorf("calling to ActivityLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ActivityLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ActivityLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ActivityLog.
func (c *ActivityLogClient) Update() *ActivityLogUpdate {
	mutation := newActivityLogMutation(c.config, OpUpdate)
	return &ActivityLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ActivityLogClient) UpdateOne(_m *ActivityLog) *ActivityLogUpdateOne {
	mutation := newActivityLogMutation(c.config, OpUpdateOne, withActivityLog(_m))
	return &ActivityLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ActivityLogClient) UpdateOneID(id int) *ActivityLogUpdateOne {
	mutation := newActivityLogMutation(c.config, OpUpdateOne, withActivityLogID(id))
	return &ActivityLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ActivityLog.
func (c *ActivityLogClient) Delete() *ActivityLogDelete {
	mutation := newActivityLogMutation(c.config, OpDelete)
	return &ActivityLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ActivityLogClient) DeleteOne(_m *ActivityLog) *ActivityLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ActivityLogClient) DeleteOneID(id int) *ActivityLogDeleteOne {
	builder := c.Delete().Where(activitylog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ActivityLogDeleteOne{builder}
}

// Query returns a query builder for ActivityLog.
func (c *ActivityLogClient) Query() *ActivityLogQuery {
	return &ActivityLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeActivityLog},
		inters: c.Interceptors(),
	}
}

// Get returns a ActivityLog entity by its id.
func (c *ActivityLogClient) Get(ctx context.Context, id int) (*ActivityLog, error) {
	return c.Query().Where(activitylog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ActivityLogClient) GetX(ctx context.Context, id int) *ActivityLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ActivityLogClient) Hooks() []Hook {
	return c.hooks.ActivityLog
}

// Interceptors returns the client interceptors.
func (c *ActivityLogClient) Interceptors() []Interceptor {
	return c.inters.ActivityLog
}

func (c *ActivityLogClient) mutate(ctx context.Context, m *ActivityLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ActivityLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ActivityLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ActivityLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ActivityLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ActivityLog mutation op: %q", m.Op())
	}
}

// InstallationClient is a client for the Installation schema.
type InstallationClient struct {
	config
}

// NewInstallationClient returns a client for the Installation from the given config.
func NewInstallationClient(c config) *InstallationClient {
	return &InstallationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `installation.Hooks(f(g(h())))`.
func (c *InstallationClient) Use(hooks ...Hook) {
	c.hooks.Installation = append(c.hooks.Installation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `installation.Intercept(f(g(h())))`.
func (c *InstallationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Installation = append(c.inters.Installation, interceptors...)
}

// Create returns a builder for creating a Installation entity.
func (c *InstallationClient) Create() *InstallationCreate {
	mutation := newInstallationMutation(c.config, OpCreate)
	return &InstallationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Installation entities.
func (c *InstallationClient) CreateBulk(builders ...*InstallationCreate) *InstallationCreateBulk {
	return &InstallationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InstallationClient) MapCreateBulk(slice any, setFunc func(*InstallationCreate, int)) *InstallationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InstallationCreateBulk{err: fmt.Errorf("calling to InstallationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InstallationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InstallationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Installation.
func (c *InstallationClient) Update() *InstallationUpdate {
	mutation := newInstallationMutation(c.config, OpUpdate)
	return &InstallationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InstallationClient) UpdateOne(_m *Installation) *InstallationUpdateOne {
	mutation := newInstallationMutation(c.config, OpUpdateOne, withInstallation(_m))
	return &InstallationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InstallationClient) UpdateOneID(id int) *InstallationUpdateOne {
	mutation := newInstallationMutation(c.config, OpUpdateOne, withInstallationID(id))
	return &InstallationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Installation.
func (c *InstallationClient) Delete() *InstallationDelete {
	mutation := newInstallationMutation(c.config, OpDelete)
	return &InstallationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InstallationClient) DeleteOne(_m *Installation) *InstallationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InstallationClient) DeleteOneID(id int) *InstallationDeleteOne {
	builder := c.Delete().Where(installation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InstallationDeleteOne{builder}
}

// Query returns a query builder for Installation.
func (c *InstallationClient) Query() *InstallationQuery {
	return &InstallationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInstallation},
		inters: c.Interceptors(),
	}
}

// Get returns a Installation entity by its id.
func (c *InstallationClient) Get(ctx context.Context, id int) (*Installation, error) {
	return c.Query().Where(installation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InstallationClient) GetX(ctx context.Context, id int) *Installation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRepos queries the repos edge of a Installation.
func (c *InstallationClient) QueryRepos(_m *Installation) *RepoQuery {
	query := (&RepoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(installation.Table, installation.FieldID, id),
			sqlgraph.To(repo.Table, repo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, installation.ReposTable, installation.ReposColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InstallationClient) Hooks() []Hook {
	return c.hooks.Installation
}

// Interceptors returns the client interceptors.
func (c *InstallationClient) Interceptors() []Interceptor {
	return c.inters.Installation
}

func (c *InstallationClient) mutate(ctx context.Context, m *InstallationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InstallationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InstallationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InstallationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InstallationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Installation mutation op: %q", m.Op())
	}
}

// ModelConfigClient is a client for the ModelConfig schema.
type ModelConfigClient struct {
	config
}

// NewModelConfigClient returns a client for the ModelConfig from the given config.
func NewModelConfigClient(c config) *ModelConfigClient {
	return &ModelConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `modelconfig.Hooks(f(g(h())))`.
func (c *ModelConfigClient) Use(hooks ...Hook) {
	c.hooks.ModelConfig = append(c.hooks.ModelConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `modelconfig.Intercept(f(g(h())))`.
func (c *ModelConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.ModelConfig = append(c.inters.ModelConfig, interceptors...)
}

// Create returns a builder for creating a ModelConfig entity.
func (c *ModelConfigClient) Create() *ModelConfigCreate {
	mutation := newModelConfigMutation(c.config, OpCreate)
	return &ModelConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ModelConfig entities.
func (c *ModelConfigClient) CreateBulk(builders ...*ModelConfigCreate) *ModelConfigCreateBulk {
	return &ModelConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModelConfigClient) MapCreateBulk(slice any, setFunc func(*ModelConfigCreate, int)) *ModelConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModelConfigCreateBulk{err: fmt.Errorf("calling to ModelConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModelConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModelConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ModelConfig.
func (c *ModelConfigClient) Update() *ModelConfigUpdate {
	mutation := newModelConfigMutation(c.config, OpUpdate)
	return &ModelConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModelConfigClient) UpdateOne(_m *ModelConfig) *ModelConfigUpdateOne {
	mutation := newModelConfigMutation(c.config, OpUpdateOne, withModelConfig(_m))
	return &ModelConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModelConfigClient) UpdateOneID(id int) *ModelConfigUpdateOne {
	mutation := newModelConfigMutation(c.config, OpUpdateOne, withModelConfigID(id))
	return &ModelConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ModelConfig.
func (c *ModelConfigClient) Delete() *ModelConfigDelete {
	mutation := newModelConfigMutation(c.config, OpDelete)
	return &ModelConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModelConfigClient) DeleteOne(_m *ModelConfig) *ModelConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModelConfigClient) DeleteOneID(id int) *ModelConfigDeleteOne {
	builder := c.Delete().Where(modelconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModelConfigDeleteOne{builder}
}

// Query returns a query builder for ModelConfig.
func (c *ModelConfigClient) Query() *ModelConfigQuery {
	return &ModelConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeModelConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a ModelConfig entity by its id.
func (c *ModelConfigClient) Get(ctx context.Context, id int) (*ModelConfig, error) {
	return c.Query().Where(modelconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModelConfigClient) GetX(ctx context.Context, id int) *ModelConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRepo queries the repo edge of a ModelConfig.
func (c *ModelConfigClient) QueryRepo(_m *ModelConfig) *RepoQuery {
	query := (&RepoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(modelconfig.Table, modelconfig.FieldID, id),
			sqlgraph.To(repo.Table, repo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modelconfig.RepoTable, modelconfig.RepoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ModelConfigClient) Hooks() []Hook {
	return c.hooks.ModelConfig
}

// Interceptors returns the client interceptors.
func (c *ModelConfigClient) Interceptors() []Interceptor {
	return c.inters.ModelConfig
}

func (c *ModelConfigClient) mutate(ctx context.Context, m *ModelConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModelConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModelConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModelConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModelConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ModelConfig mutation op: %q", m.Op())
	}
}

// PipelineStateClient is a client for the PipelineState schema.
type PipelineStateClient struct {
	config
}

// NewPipelineStateClient returns a client for the PipelineState from the given config.
func NewPipelineStateClient(c config) *PipelineStateClient {
	return &PipelineStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pipelinestate.Hooks(f(g(h())))`.
func (c *PipelineStateClient) Use(hooks ...Hook) {
	c.hooks.PipelineState = append(c.hooks.PipelineState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pipelinestate.Intercept(f(g(h())))`.
func (c *PipelineStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.PipelineState = append(c.inters.PipelineState, interceptors...)
}

// Create returns a builder for creating a PipelineState entity.
func (c *PipelineStateClient) Create() *PipelineStateCreate {
	mutation := newPipelineStateMutation(c.config, OpCreate)
	return &PipelineStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PipelineState entities.
func (c *PipelineStateClient) CreateBulk(builders ...*PipelineStateCreate) *PipelineStateCreateBulk {
	return &PipelineStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PipelineStateClient) MapCreateBulk(slice any, setFunc func(*PipelineStateCreate, int)) *PipelineStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PipelineStateCreateBulk{err: fmt.Errorf("calling to PipelineStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PipelineStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PipelineStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PipelineState.
func (c *PipelineStateClient) Update() *PipelineStateUpdate {
	mutation := newPipelineStateMutation(c.config, OpUpdate)
	return &PipelineStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PipelineStateClient) UpdateOne(_m *PipelineState) *PipelineStateUpdateOne {
	mutation := newPipelineStateMutation(c.config, OpUpdateOne, withPipelineState(_m))
	return &PipelineStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PipelineStateClient) UpdateOneID(id uuid.UUID) *PipelineStateUpdateOne {
	mutation := newPipelineStateMutation(c.config, OpUpdateOne, withPipelineStateID(id))
	return &PipelineStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PipelineState.
func (c *PipelineStateClient) Delete() *PipelineStateDelete {
	mutation := newPipelineStateMutation(c.config, OpDelete)
	return &PipelineStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PipelineStateClient) DeleteOne(_m *PipelineState) *PipelineStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PipelineStateClient) DeleteOneID(id uuid.UUID) *PipelineStateDeleteOne {
	builder := c.Delete().Where(pipelinestate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PipelineStateDeleteOne{builder}
}

// Query returns a query builder for PipelineState.
func (c *PipelineStateClient) Query() *PipelineStateQuery {
	return &PipelineStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePipelineState},
		inters: c.Interceptors(),
	}
}

// Get returns a PipelineState entity by its id.
func (c *PipelineStateClient) Get(ctx context.Context, id uuid.UUID) (*PipelineState, error) {
	return c.Query().Where(pipelinestate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PipelineStateClient) GetX(ctx context.Context, id uuid.UUID) *PipelineState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReview queries the review edge of a PipelineState.
func (c *PipelineStateClient) QueryReview(_m *PipelineState) *ReviewQuery {
	query := (&ReviewClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pipelinestate.Table, pipelinestate.FieldID, id),
			sqlgraph.To(review.Table, review.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pipelinestate.ReviewTable, pipelinestate.ReviewColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PipelineStateClient) Hooks() []Hook {
	return c.hooks.PipelineState
}

// Interceptors returns the client interceptors.
func (c *PipelineStateClient) Interceptors() []Interceptor {
	return c.inters.PipelineState
}

func (c *PipelineStateClient) mutate(ctx context.Context, m *PipelineStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PipelineStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PipelineStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PipelineStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PipelineStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PipelineState mutation op: %q", m.Op())
	}
}

// RepoClient is a client for the Repo schema.
type RepoClient struct {
	config
}

// NewRepoClient returns a client for the Repo from the given config.
func NewRepoClient(c config) *RepoClient {
	return &RepoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `repo.Hooks(f(g(h())))`.
func (c *RepoClient) Use(hooks ...Hook) {
	c.hooks.Repo = append(c.hooks.Repo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `repo.Intercept(f(g(h())))`.
func (c *RepoClient) Intercept(interceptors ...Interceptor) {
	c.inters.Repo = append(c.inters.Repo, interceptors...)
}

// Create returns a builder for creating a Repo entity.
func (c *RepoClient) Create() *RepoCreate {
	mutation := newRepoMutation(c.config, OpCreate)
	return &RepoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Repo entities.
func (c *RepoClient) CreateBulk(builders ...*RepoCreate) *RepoCreateBulk {
	return &RepoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RepoClient) MapCreateBulk(slice any, setFunc func(*RepoCreate, int)) *RepoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RepoCreateBulk{err: fmt.Errorf("calling to RepoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RepoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RepoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Repo.
func (c *RepoClient) Update() *RepoUpdate {
	mutation := newRepoMutation(c.config, OpUpdate)
	return &RepoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepoClient) UpdateOne(_m *Repo) *RepoUpdateOne {
	mutation := newRepoMutation(c.config, OpUpdateOne, withRepo(_m))
	return &RepoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepoClient) UpdateOneID(id int) *RepoUpdateOne {
	mutation := newRepoMutation(c.config, OpUpdateOne, withRepoID(id))
	return &RepoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Repo.
func (c *RepoClient) Delete() *RepoDelete {
	mutation := newRepoMutation(c.config, OpDelete)
	return &RepoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RepoClient) DeleteOne(_m *Repo) *RepoDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RepoClient) DeleteOneID(id int) *RepoDeleteOne {
	builder := c.Delete().Where(repo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepoDeleteOne{builder}
}

// Query returns a query builder for Repo.
func (c *RepoClient) Query() *RepoQuery {
	return &RepoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRepo},
		inters: c.Interceptors(),
	}
}

// Get returns a Repo entity by its id.
func (c *RepoClient) Get(ctx context.Context, id int) (*Repo, error) {
	return c.Query().Where(repo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepoClient) GetX(ctx context.Context, id int) *Repo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInstallation queries the installation edge of a Repo.
func (c *RepoClient) QueryInstallation(_m *Repo) *InstallationQuery {
	query := (&InstallationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repo.Table, repo.FieldID, id),
			sqlgraph.To(installation.Table, installation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, repo.InstallationTable, repo.InstallationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviews queries the reviews edge of a Repo.
func (c *RepoClient) QueryReviews(_m *Repo) *ReviewQuery {
	query := (&ReviewClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repo.Table, repo.FieldID, id),
			sqlgraph.To(review.Table, review.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repo.ReviewsTable, repo.ReviewsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryModelConfigs queries the model_configs edge of a Repo.
func (c *RepoClient) QueryModelConfigs(_m *Repo) *ModelConfigQuery {
	query := (&ModelConfigClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repo.Table, repo.FieldID, id),
			sqlgraph.To(modelconfig.Table, modelconfig.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repo.ModelConfigsTable, repo.ModelConfigsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RepoClient) Hooks() []Hook {
	return c.hooks.Repo
}

// Interceptors returns the client interceptors.
func (c *RepoClient) Interceptors() []Interceptor {
	return c.inters.Repo
}

func (c *RepoClient) mutate(ctx context.Context, m *RepoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RepoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RepoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RepoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RepoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Repo mutation op: %q", m.Op())
	}
}

// ReviewClient is a client for the Review schema.
type ReviewClient struct {
	config
}

// NewReviewClient returns a client for the Review from the given config.
func NewReviewClient(c config) *ReviewClient {
	return &ReviewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `review.Hooks(f(g(h())))`.
func (c *ReviewClient) Use(hooks ...Hook) {
	c.hooks.Review = append(c.hooks.Review, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `review.Intercept(f(g(h())))`.
func (c *ReviewClient) Intercept(interceptors ...Interceptor) {
	c.inters.Review = append(c.inters.Review, interceptors...)
}

// Create returns a builder for creating a Review entity.
func (c *ReviewClient) Create() *ReviewCreate {
	mutation := newReviewMutation(c.config, OpCreate)
	return &ReviewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Review entities.
func (c *ReviewClient) CreateBulk(builders ...*ReviewCreate) *ReviewCreateBulk {
	return &ReviewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ReviewClient) MapCreateBulk(slice any, setFunc func(*ReviewCreate, int)) *ReviewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ReviewCreateBulk{err: fmt.Errorf("calling to ReviewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ReviewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ReviewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Review.
func (c *ReviewClient) Update() *ReviewUpdate {
	mutation := newReviewMutation(c.config, OpUpdate)
	return &ReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReviewClient) UpdateOne(_m *Review) *ReviewUpdateOne {
	mutation := newReviewMutation(c.config, OpUpdateOne, withReview(_m))
	return &ReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReviewClient) UpdateOneID(id uuid.UUID) *ReviewUpdateOne {
	mutation := newReviewMutation(c.config, OpUpdateOne, withReviewID(id))
	return &ReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Review.
func (c *ReviewClient) Delete() *ReviewDelete {
	mutation := newReviewMutation(c.config, OpDelete)
	return &ReviewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReviewClient) DeleteOne(_m *Review) *ReviewDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReviewClient) DeleteOneID(id uuid.UUID) *ReviewDeleteOne {
	builder := c.Delete().Where(review.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReviewDeleteOne{builder}
}

// Query returns a query builder for Review.
func (c *ReviewClient) Query() *ReviewQuery {
	return &ReviewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReview},
		inters: c.Interceptors(),
	}
}

// Get returns a Review entity by its id.
func (c *ReviewClient) Get(ctx context.Context, id uuid.UUID) (*Review, error) {
	return c.Query().Where(review.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReviewClient) GetX(ctx context.Context, id uuid.UUID) *Review {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRepo queries the repo edge of a Review.
func (c *ReviewClient) QueryRepo(_m *Review) *RepoQuery {
	query := (&RepoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(review.Table, review.FieldID, id),
			sqlgraph.To(repo.Table, repo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, review.RepoTable, review.RepoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryComments queries the comments edge of a Review.
func (c *ReviewClient) QueryComments(_m *Review) *ReviewCommentQuery {
	query := (&ReviewCommentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(review.Table, review.FieldID, id),
			sqlgraph.To(reviewcomment.Table, reviewcomment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, review.CommentsTable, review.CommentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPipelineStates queries the pipeline_states edge of a Review.
func (c *ReviewClient) QueryPipelineStates(_m *Review) *PipelineStateQuery {
	query := (&PipelineStateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(review.Table, review.FieldID, id),
			sqlgraph.To(pipelinestate.Table, pipelinestate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, review.PipelineStatesTable, review.PipelineStatesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ReviewClient) Hooks() []Hook {
	return c.hooks.Review
}

// Interceptors returns the client interceptors.
func (c *ReviewClient) Interceptors() []Interceptor {
	return c.inters.Review
}

func (c *ReviewClient) mutate(ctx context.Context, m *ReviewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReviewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReviewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Review mutation op: %q", m.Op())
	}
}

// ReviewCommentClient is a client for the ReviewComment schema.
type ReviewCommentClient struct {
	config
}

// NewReviewCommentClient returns a client for the ReviewComment from the given config.
func NewReviewCommentClient(c config) *ReviewCommentClient {
	return &ReviewCommentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `reviewcomment.Hooks(f(g(h())))`.
func (c *ReviewCommentClient) Use(hooks ...Hook) {
	c.hooks.ReviewComment = append(c.hooks.ReviewComment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `reviewcomment.Intercept(f(g(h())))`.
func (c *ReviewCommentClient) Intercept(interceptors ...Interceptor) {
	c.inters.ReviewComment = append(c.inters.ReviewComment, interceptors...)
}

// Create returns a builder for creating a ReviewComment entity.
func (c *ReviewCommentClient) Create() *ReviewCommentCreate {
	mutation := newReviewCommentMutation(c.config, OpCreate)
	return &ReviewCommentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ReviewComment entities.
func (c *ReviewCommentClient) CreateBulk(builders ...*ReviewCommentCreate) *ReviewCommentCreateBulk {
	return &ReviewCommentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ReviewCommentClient) MapCreateBulk(slice any, setFunc func(*ReviewCommentCreate, int)) *ReviewCommentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ReviewCommentCreateBulk{err: fmt.Errorf("calling to ReviewCommentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ReviewCommentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ReviewCommentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ReviewComment.
func (c *ReviewCommentClient) Update() *ReviewCommentUpdate {
	mutation := newReviewCommentMutation(c.config, OpUpdate)
	return &ReviewCommentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReviewCommentClient) UpdateOne(_m *ReviewComment) *ReviewCommentUpdateOne {
	mutation := newReviewCommentMutation(c.config, OpUpdateOne, withReviewComment(_m))
	return &ReviewCommentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReviewCommentClient) UpdateOneID(id uuid.UUID) *ReviewCommentUpdateOne {
	mutation := newReviewCommentMutation(c.config, OpUpdateOne, withReviewCommentID(id))
	return &ReviewCommentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ReviewComment.
func (c *ReviewCommentClient) Delete() *ReviewCommentDelete {
	mutation := newReviewCommentMutation(c.config, OpDelete)
	return &ReviewCommentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReviewCommentClient) DeleteOne(_m *ReviewComment) *ReviewCommentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReviewCommentClient) DeleteOneID(id uuid.UUID) *ReviewCommentDeleteOne {
	builder := c.Delete().Where(reviewcomment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReviewCommentDeleteOne{builder}
}

// Query returns a query builder for ReviewComment.
func (c *ReviewCommentClient) Query() *ReviewCommentQuery {
	return &ReviewCommentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReviewComment},
		inters: c.Interceptors(),
	}
}

// Get returns a ReviewComment entity by its id.
func (c *ReviewCommentClient) Get(ctx context.Context, id uuid.UUID) (*ReviewComment, error) {
	return c.Query().Where(reviewcomment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReviewCommentClient) GetX(ctx context.Context, id uuid.UUID) *ReviewComment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReview queries the review edge of a ReviewComment.
func (c *ReviewCommentClient) QueryReview(_m *ReviewComment) *ReviewQuery {
	query := (&ReviewClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(reviewcomment.Table, reviewcomment.FieldID, id),
			sqlgraph.To(review.Table, review.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, reviewcomment.ReviewTable, reviewcomment.ReviewColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ReviewCommentClient) Hooks() []Hook {
	return c.hooks.ReviewComment
}

// Interceptors returns the client interceptors.
func (c *ReviewCommentClient) Interceptors() []Interceptor {
	return c.inters.ReviewComment
}

func (c *ReviewCommentClient) mutate(ctx context.Context, m *ReviewCommentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReviewCommentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReviewCommentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReviewCommentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReviewCommentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ReviewComment mutation op: %q", m.Op())
	}
}

// RuleClient is a client for the Rule schema.
type RuleClient struct {
	config
}

// NewRuleClient returns a client for the Rule from the given config.
func NewRuleClient(c config) *RuleClient {
	return &RuleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `rule.Hooks(f(g(h())))`.
func (c *RuleClient) Use(hooks ...Hook) {
	c.hooks.Rule = append(c.hooks.Rule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `rule.Intercept(f(g(h())))`.
func (c *RuleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Rule = append(c.inters.Rule, interceptors...)
}

// Create returns a builder for creating a Rule entity.
func (c *RuleClient) Create() *RuleCreate {
	mutation := newRuleMutation(c.config, OpCreate)
	return &RuleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Rule entities.
func (c *RuleClient) CreateBulk(builders ...*RuleCreate) *RuleCreateBulk {
	return &RuleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RuleClient) MapCreateBulk(slice any, setFunc func(*RuleCreate, int)) *RuleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RuleCreateBulk{err: fmt.Errorf("calling to RuleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RuleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RuleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Rule.
func (c *RuleClient) Update() *RuleUpdate {
	mutation := newRuleMutation(c.config, OpUpdate)
	return &RuleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RuleClient) UpdateOne(_m *Rule) *RuleUpdateOne {
	mutation := newRuleMutation(c.config, OpUpdateOne, withRule(_m))
	return &RuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RuleClient) UpdateOneID(id int) *RuleUpdateOne {
	mutation := newRuleMutation(c.config, OpUpdateOne, withRuleID(id))
	return &RuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Rule.
func (c *RuleClient) Delete() *RuleDelete {
	mutation := newRuleMutation(c.config, OpDelete)
	return &RuleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RuleClient) DeleteOne(_m *Rule) *RuleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RuleClient) DeleteOneID(id int) *RuleDeleteOne {
	builder := c.Delete().Where(rule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RuleDeleteOne{builder}
}

// Query returns a query builder for Rule.
func (c *RuleClient) Query() *RuleQuery {
	return &RuleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRule},
		inters: c.Interceptors(),
	}
}

// Get returns a Rule entity by its id.
func (c *RuleClient) Get(ctx context.Context, id int) (*Rule, error) {
	return c.Query().Where(rule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RuleClient) GetX(ctx context.Context, id int) *Rule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RuleClient) Hooks() []Hook {
	return c.hooks.Rule
}

// Interceptors returns the client interceptors.
func (c *RuleClient) Interceptors() []Interceptor {
	return c.inters.Rule
}

func (c *RuleClient) mutate(ctx context.Context, m *RuleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RuleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RuleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RuleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Rule mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ActivityLog, Installation, ModelConfig, PipelineState, Repo, Review,
		ReviewComment, Rule []ent.Hook
	}
	inters struct {
		ActivityLog, Installation, ModelConfig, PipelineState, Repo, Review,
		ReviewComment, Rule []ent.Interceptor
	}
)
