// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/acmeorg/argus/ent/installation"
)

// Installation is the model entity for the Installation schema.
type Installation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// InstallationID holds the value of the "installation_id" field.
	InstallationID int64 `json:"installation_id,omitempty"`
	// OrgLogin holds the value of the "org_login" field.
	OrgLogin string `json:"org_login,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// SuspendedAt holds the value of the "suspended_at" field.
	SuspendedAt *time.Time `json:"suspended_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InstallationQuery when eager-loading is set.
	Edges        InstallationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InstallationEdges holds the relations/edges for other nodes in the graph.
type InstallationEdges struct {
	// Repos holds the value of the repos edge.
	Repos []*Repo `json:"repos,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReposOrErr returns the Repos value or an error if the edge
// was not loaded in eager-loading.
func (e InstallationEdges) ReposOrErr() ([]*Repo, error) {
	if e.loadedTypes[0] {
		return e.Repos, nil
	}
	return nil, &NotLoadedError{edge: "repos"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Installation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case installation.FieldID, installation.FieldInstallationID:
			values[i] = new(sql.NullInt64)
		case installation.FieldOrgLogin:
			values[i] = new(sql.NullString)
		case installation.FieldCreatedAt, installation.FieldSuspendedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Installation fields.
func (_m *Installation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case installation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case installation.FieldInstallationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field installation_id", values[i])
			} else if value.Valid {
				_m.InstallationID = value.Int64
			}
		case installation.FieldOrgLogin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_login", values[i])
			} else if value.Valid {
				_m.OrgLogin = value.String
			}
		case installation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case installation.FieldSuspendedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field suspended_at", values[i])
			} else if value.Valid {
				_m.SuspendedAt = new(time.Time)
				*_m.SuspendedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Installation.
// This includes values selected through modifiers, order, etc.
func (_m *Installation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRepos queries the "repos" edge of the Installation entity.
func (_m *Installation) QueryRepos() *RepoQuery {
	return NewInstallationClient(_m.config).QueryRepos(_m)
}

// Update returns a builder for updating this Installation.
// Note that you need to call Installation.Unwrap() before calling this method if this Installation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Installation) Update() *InstallationUpdateOne {
	return NewInstallationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Installation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Installation) Unwrap() *Installation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Installation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Installation) String() string {
	var builder strings.Builder
	builder.WriteString("Installation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("installation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstallationID))
	builder.WriteString(", ")
	builder.WriteString("org_login=")
	builder.WriteString(_m.OrgLogin)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SuspendedAt; v != nil {
		builder.WriteString("suspended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Installations is a parsable slice of Installation.
type Installations []*Installation
