// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/BeLazy167/argus/ent/pipelinestate"
	"github.com/BeLazy167/argus/ent/predicate"
	"github.com/BeLazy167/argus/ent/review"
)

// PipelineStateUpdate is the builder for updating PipelineState entities.
type PipelineStateUpdate struct {
	config
	hooks    []Hook
	mutation *PipelineStateMutation
}

// Where appends a list predicates to the PipelineStateUpdate builder.
func (_u *PipelineStateUpdate) Where(ps ...predicate.PipelineState) *PipelineStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *PipelineStateUpdate) SetState(v string) *PipelineStateUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PipelineStateUpdate) SetNillableState(v *string) *PipelineStateUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *PipelineStateUpdate) SetPayload(v map[string]interface{}) *PipelineStateUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *PipelineStateUpdate) ClearPayload() *PipelineStateUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetError sets the "error" field.
func (_u *PipelineStateUpdate) SetError(v string) *PipelineStateUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *PipelineStateUpdate) SetNillableError(v *string) *PipelineStateUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *PipelineStateUpdate) ClearError() *PipelineStateUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PipelineStateUpdate) SetCreatedAt(v time.Time) *PipelineStateUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PipelineStateUpdate) SetNillableCreatedAt(v *time.Time) *PipelineStateUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PipelineStateUpdate) SetUpdatedAt(v time.Time) *PipelineStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetReviewID sets the "review" edge to the Review entity by ID.
func (_u *PipelineStateUpdate) SetReviewID(id uuid.UUID) *PipelineStateUpdate {
	_u.mutation.SetReviewID(id)
	return _u
}

// SetReview sets the "review" edge to the Review entity.
func (_u *PipelineStateUpdate) SetReview(v *Review) *PipelineStateUpdate {
	return _u.SetReviewID(v.ID)
}

// Mutation returns the PipelineStateMutation object of the builder.
func (_u *PipelineStateUpdate) Mutation() *PipelineStateMutation {
	return _u.mutation
}

// ClearReview clears the "review" edge to the Review entity.
func (_u *PipelineStateUpdate) ClearReview() *PipelineStateUpdate {
	_u.mutation.ClearReview()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PipelineStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PipelineStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PipelineStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PipelineStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PipelineStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pipelinestate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PipelineStateUpdate) check() error {
	if _u.mutation.ReviewCleared() && len(_u.mutation.ReviewIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PipelineState.review"`)
	}
	return nil
}

func (_u *PipelineStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pipelinestate.Table, pipelinestate.Columns, sqlgraph.NewFieldSpec(pipelinestate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(pipelinestate.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(pipelinestate.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(pipelinestate.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(pipelinestate.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(pipelinestate.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pipelinestate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pipelinestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pipelinestate.ReviewTable,
			Columns: []string{pipelinestate.ReviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pipelinestate.ReviewTable,
			Columns: []string{pipelinestate.ReviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pipelinestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PipelineStateUpdateOne is the builder for updating a single PipelineState entity.
type PipelineStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PipelineStateMutation
}

// SetState sets the "state" field.
func (_u *PipelineStateUpdateOne) SetState(v string) *PipelineStateUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PipelineStateUpdateOne) SetNillableState(v *string) *PipelineStateUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *PipelineStateUpdateOne) SetPayload(v map[string]interface{}) *PipelineStateUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *PipelineStateUpdateOne) ClearPayload() *PipelineStateUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetError sets the "error" field.
func (_u *PipelineStateUpdateOne) SetError(v string) *PipelineStateUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *PipelineStateUpdateOne) SetNillableError(v *string) *PipelineStateUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *PipelineStateUpdateOne) ClearError() *PipelineStateUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PipelineStateUpdateOne) SetCreatedAt(v time.Time) *PipelineStateUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PipelineStateUpdateOne) SetNillableCreatedAt(v *time.Time) *PipelineStateUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PipelineStateUpdateOne) SetUpdatedAt(v time.Time) *PipelineStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetReviewID sets the "review" edge to the Review entity by ID.
func (_u *PipelineStateUpdateOne) SetReviewID(id uuid.UUID) *PipelineStateUpdateOne {
	_u.mutation.SetReviewID(id)
	return _u
}

// SetReview sets the "review" edge to the Review entity.
func (_u *PipelineStateUpdateOne) SetReview(v *Review) *PipelineStateUpdateOne {
	return _u.SetReviewID(v.ID)
}

// Mutation returns the PipelineStateMutation object of the builder.
func (_u *PipelineStateUpdateOne) Mutation() *PipelineStateMutation {
	return _u.mutation
}

// ClearReview clears the "review" edge to the Review entity.
func (_u *PipelineStateUpdateOne) ClearReview() *PipelineStateUpdateOne {
	_u.mutation.ClearReview()
	return _u
}

// Where appends a list predicates to the PipelineStateUpdate builder.
func (_u *PipelineStateUpdateOne) Where(ps ...predicate.PipelineState) *PipelineStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PipelineStateUpdateOne) Select(field string, fields ...string) *PipelineStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PipelineState entity.
func (_u *PipelineStateUpdateOne) Save(ctx context.Context) (*PipelineState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PipelineStateUpdateOne) SaveX(ctx context.Context) *PipelineState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PipelineStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PipelineStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PipelineStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pipelinestate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PipelineStateUpdateOne) check() error {
	if _u.mutation.ReviewCleared() && len(_u.mutation.ReviewIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PipelineState.review"`)
	}
	return nil
}

func (_u *PipelineStateUpdateOne) sqlSave(ctx context.Context) (_node *PipelineState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pipelinestate.Table, pipelinestate.Columns, sqlgraph.NewFieldSpec(pipelinestate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PipelineState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pipelinestate.FieldID)
		for _, f := range fields {
			if !pipelinestate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pipelinestate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(pipelinestate.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(pipelinestate.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(pipelinestate.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(pipelinestate.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(pipelinestate.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pipelinestate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pipelinestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pipelinestate.ReviewTable,
			Columns: []string{pipelinestate.ReviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pipelinestate.ReviewTable,
			Columns: []string{pipelinestate.ReviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PipelineState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pipelinestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
