// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/acmeorg/argus/ent/pipelinestate"
	"github.com/acmeorg/argus/ent/review"
)

// PipelineState is the model entity for the PipelineState schema.
type PipelineState struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Error holds the value of the "error" field.
	Error *string `json:"error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PipelineStateQuery when eager-loading is set.
	Edges                  PipelineStateEdges `json:"edges"`
	review_pipeline_states *uuid.UUID
	selectValues           sql.SelectValues
}

// PipelineStateEdges holds the relations/edges for other nodes in the graph.
type PipelineStateEdges struct {
	// Review holds the value of the review edge.
	Review *Review `json:"review,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReviewOrErr returns the Review value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PipelineStateEdges) ReviewOrErr() (*Review, error) {
	if e.Review != nil {
		return e.Review, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: review.Label}
	}
	return nil, &NotLoadedError{edge: "review"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PipelineState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pipelinestate.FieldPayload:
			values[i] = new([]byte)
		case pipelinestate.FieldState, pipelinestate.FieldError:
			values[i] = new(sql.NullString)
		case pipelinestate.FieldCreatedAt, pipelinestate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case pipelinestate.FieldID:
			values[i] = new(uuid.UUID)
		case pipelinestate.ForeignKeys[0]: // review_pipeline_states
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PipelineState fields.
func (_m *PipelineState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pipelinestate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pipelinestate.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case pipelinestate.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case pipelinestate.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = new(string)
				*_m.Error = value.String
			}
		case pipelinestate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pipelinestate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case pipelinestate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field review_pipeline_states", values[i])
			} else if value.Valid {
				_m.review_pipeline_states = new(uuid.UUID)
				*_m.review_pipeline_states = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PipelineState.
// This includes values selected through modifiers, order, etc.
func (_m *PipelineState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReview queries the "review" edge of the PipelineState entity.
func (_m *PipelineState) QueryReview() *ReviewQuery {
	return NewPipelineStateClient(_m.config).QueryReview(_m)
}

// Update returns a builder for updating this PipelineState.
// Note that you need to call PipelineState.Unwrap() before calling this method if this PipelineState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PipelineState) Update() *PipelineStateUpdateOne {
	return NewPipelineStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PipelineState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PipelineState) Unwrap() *PipelineState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PipelineState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PipelineState) String() string {
	var builder strings.Builder
	builder.WriteString("PipelineState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	if v := _m.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PipelineStates is a parsable slice of PipelineState.
type PipelineStates []*PipelineState
