// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BeLazy167/argus/ent/pipelinestate"
	"github.com/BeLazy167/argus/ent/predicate"
)

// PipelineStateDelete is the builder for deleting a PipelineState entity.
type PipelineStateDelete struct {
	config
	hooks    []Hook
	mutation *PipelineStateMutation
}

// Where appends a list predicates to the PipelineStateDelete builder.
func (_d *PipelineStateDelete) Where(ps ...predicate.PipelineState) *PipelineStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PipelineStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PipelineStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PipelineStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pipelinestate.Table, sqlgraph.NewFieldSpec(pipelinestate.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PipelineStateDeleteOne is the builder for deleting a single PipelineState entity.
type PipelineStateDeleteOne struct {
	_d *PipelineStateDelete
}

// Where appends a list predicates to the PipelineStateDelete builder.
func (_d *PipelineStateDeleteOne) Where(ps ...predicate.PipelineState) *PipelineStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PipelineStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pipelinestate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PipelineStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
