// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/acmeorg/argus/ent/review"
	"github.com/acmeorg/argus/ent/reviewcomment"
)

// ReviewComment is the model entity for the ReviewComment schema.
type ReviewComment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FilePath holds the value of the "file_path" field.
	FilePath string `json:"file_path,omitempty"`
	// StartLine holds the value of the "start_line" field.
	StartLine *int `json:"start_line,omitempty"`
	// EndLine holds the value of the "end_line" field.
	EndLine *int `json:"end_line,omitempty"`
	// Side holds the value of the "side" field.
	Side *reviewcomment.Side `json:"side,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity *reviewcomment.Severity `json:"severity,omitempty"`
	// Category holds the value of the "category" field.
	Category *string `json:"category,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReviewCommentQuery when eager-loading is set.
	Edges           ReviewCommentEdges `json:"edges"`
	review_comments *uuid.UUID
	selectValues    sql.SelectValues
}

// ReviewCommentEdges holds the relations/edges for other nodes in the graph.
type ReviewCommentEdges struct {
	// Review holds the value of the review edge.
	Review *Review `json:"review,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReviewOrErr returns the Review value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReviewCommentEdges) ReviewOrErr() (*Review, error) {
	if e.Review != nil {
		return e.Review, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: review.Label}
	}
	return nil, &NotLoadedError{edge: "review"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReviewComment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reviewcomment.FieldStartLine, reviewcomment.FieldEndLine:
			values[i] = new(sql.NullInt64)
		case reviewcomment.FieldFilePath, reviewcomment.FieldSide, reviewcomment.FieldBody, reviewcomment.FieldSeverity, reviewcomment.FieldCategory:
			values[i] = new(sql.NullString)
		case reviewcomment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case reviewcomment.FieldID:
			values[i] = new(uuid.UUID)
		case reviewcomment.ForeignKeys[0]: // review_comments
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReviewComment fields.
func (_m *ReviewComment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reviewcomment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case reviewcomment.FieldFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_path", values[i])
			} else if value.Valid {
				_m.FilePath = value.String
			}
		case reviewcomment.FieldStartLine:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_line", values[i])
			} else if value.Valid {
				_m.StartLine = new(int)
				*_m.StartLine = int(value.Int64)
			}
		case reviewcomment.FieldEndLine:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field end_line", values[i])
			} else if value.Valid {
				_m.EndLine = new(int)
				*_m.EndLine = int(value.Int64)
			}
		case reviewcomment.FieldSide:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field side", values[i])
			} else if value.Valid {
				_m.Side = new(reviewcomment.Side)
				*_m.Side = reviewcomment.Side(value.String)
			}
		case reviewcomment.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case reviewcomment.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = new(reviewcomment.Severity)
				*_m.Severity = reviewcomment.Severity(value.String)
			}
		case reviewcomment.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = new(string)
				*_m.Category = value.String
			}
		case reviewcomment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case reviewcomment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field review_comments", values[i])
			} else if value.Valid {
				_m.review_comments = new(uuid.UUID)
				*_m.review_comments = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReviewComment.
// This includes values selected through modifiers, order, etc.
func (_m *ReviewComment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReview queries the "review" edge of the ReviewComment entity.
func (_m *ReviewComment) QueryReview() *ReviewQuery {
	return NewReviewCommentClient(_m.config).QueryReview(_m)
}

// Update returns a builder for updating this ReviewComment.
// Note that you need to call ReviewComment.Unwrap() before calling this method if this ReviewComment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReviewComment) Update() *ReviewCommentUpdateOne {
	return NewReviewCommentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReviewComment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReviewComment) Unwrap() *ReviewComment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReviewComment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReviewComment) String() string {
	var builder strings.Builder
	builder.WriteString("ReviewComment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("file_path=")
	builder.WriteString(_m.FilePath)
	builder.WriteString(", ")
	if v := _m.StartLine; v != nil {
		builder.WriteString("start_line=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EndLine; v != nil {
		builder.WriteString("end_line=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Side; v != nil {
		builder.WriteString("side=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	if v := _m.Severity; v != nil {
		builder.WriteString("severity=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Category; v != nil {
		builder.WriteString("category=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReviewComments is a parsable slice of ReviewComment.
type ReviewComments []*ReviewComment
