// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/BeLazy167/argus/ent/predicate"
	"github.com/BeLazy167/argus/ent/review"
	"github.com/BeLazy167/argus/ent/reviewcomment"
)

// ReviewCommentUpdate is the builder for updating ReviewComment entities.
type ReviewCommentUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewCommentMutation
}

// Where appends a list predicates to the ReviewCommentUpdate builder.
func (_u *ReviewCommentUpdate) Where(ps ...predicate.ReviewComment) *ReviewCommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ReviewCommentUpdate) SetFilePath(v string) *ReviewCommentUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ReviewCommentUpdate) SetNillableFilePath(v *string) *ReviewCommentUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *ReviewCommentUpdate) SetStartLine(v int) *ReviewCommentUpdate {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *ReviewCommentUpdate) SetNillableStartLine(v *int) *ReviewCommentUpdate {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *ReviewCommentUpdate) AddStartLine(v int) *ReviewCommentUpdate {
	_u.mutation.AddStartLine(v)
	return _u
}

// ClearStartLine clears the value of the "start_line" field.
func (_u *ReviewCommentUpdate) ClearStartLine() *ReviewCommentUpdate {
	_u.mutation.ClearStartLine()
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *ReviewCommentUpdate) SetEndLine(v int) *ReviewCommentUpdate {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *ReviewCommentUpdate) SetNillableEndLine(v *int) *ReviewCommentUpdate {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *ReviewCommentUpdate) AddEndLine(v int) *ReviewCommentUpdate {
	_u.mutation.AddEndLine(v)
	return _u
}

// ClearEndLine clears the value of the "end_line" field.
func (_u *ReviewCommentUpdate) ClearEndLine() *ReviewCommentUpdate {
	_u.mutation.ClearEndLine()
	return _u
}

// SetSide sets the "side" field.
func (_u *ReviewCommentUpdate) SetSide(v reviewcomment.Side) *ReviewCommentUpdate {
	_u.mutation.SetSide(v)
	return _u
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_u *ReviewCommentUpdate) SetNillableSide(v *reviewcomment.Side) *ReviewCommentUpdate {
	if v != nil {
		_u.SetSide(*v)
	}
	return _u
}

// ClearSide clears the value of the "side" field.
func (_u *ReviewCommentUpdate) ClearSide() *ReviewCommentUpdate {
	_u.mutation.ClearSide()
	return _u
}

// SetBody sets the "body" field.
func (_u *ReviewCommentUpdate) SetBody(v string) *ReviewCommentUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ReviewCommentUpdate) SetNillableBody(v *string) *ReviewCommentUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *ReviewCommentUpdate) SetSeverity(v reviewcomment.Severity) *ReviewCommentUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *ReviewCommentUpdate) SetNillableSeverity(v *reviewcomment.Severity) *ReviewCommentUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// ClearSeverity clears the value of the "severity" field.
func (_u *ReviewCommentUpdate) ClearSeverity() *ReviewCommentUpdate {
	_u.mutation.ClearSeverity()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ReviewCommentUpdate) SetCategory(v string) *ReviewCommentUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ReviewCommentUpdate) SetNillableCategory(v *string) *ReviewCommentUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ReviewCommentUpdate) ClearCategory() *ReviewCommentUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReviewCommentUpdate) SetCreatedAt(v time.Time) *ReviewCommentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReviewCommentUpdate) SetNillableCreatedAt(v *time.Time) *ReviewCommentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReviewID sets the "review" edge to the Review entity by ID.
func (_u *ReviewCommentUpdate) SetReviewID(id uuid.UUID) *ReviewCommentUpdate {
	_u.mutation.SetReviewID(id)
	return _u
}

// SetReview sets the "review" edge to the Review entity.
func (_u *ReviewCommentUpdate) SetReview(v *Review) *ReviewCommentUpdate {
	return _u.SetReviewID(v.ID)
}

// Mutation returns the ReviewCommentMutation object of the builder.
func (_u *ReviewCommentUpdate) Mutation() *ReviewCommentMutation {
	return _u.mutation
}

// ClearReview clears the "review" edge to the Review entity.
func (_u *ReviewCommentUpdate) ClearReview() *ReviewCommentUpdate {
	_u.mutation.ClearReview()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewCommentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewCommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewCommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewCommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewCommentUpdate) check() error {
	if v, ok := _u.mutation.Side(); ok {
		if err := reviewcomment.SideValidator(v); err != nil {
			return &ValidationError{Name: "side", err: fmt.Errorf(`ent: validator failed for field "ReviewComment.side": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := reviewcomment.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "ReviewComment.severity": %w`, err)}
		}
	}
	if _u.mutation.ReviewCleared() && len(_u.mutation.ReviewIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReviewComment.review"`)
	}
	return nil
}

func (_u *ReviewCommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reviewcomment.Table, reviewcomment.Columns, sqlgraph.NewFieldSpec(reviewcomment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(reviewcomment.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(reviewcomment.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(reviewcomment.FieldStartLine, field.TypeInt, value)
	}
	if _u.mutation.StartLineCleared() {
		_spec.ClearField(reviewcomment.FieldStartLine, field.TypeInt)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(reviewcomment.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(reviewcomment.FieldEndLine, field.TypeInt, value)
	}
	if _u.mutation.EndLineCleared() {
		_spec.ClearField(reviewcomment.FieldEndLine, field.TypeInt)
	}
	if value, ok := _u.mutation.Side(); ok {
		_spec.SetField(reviewcomment.FieldSide, field.TypeEnum, value)
	}
	if _u.mutation.SideCleared() {
		_spec.ClearField(reviewcomment.FieldSide, field.TypeEnum)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(reviewcomment.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(reviewcomment.FieldSeverity, field.TypeEnum, value)
	}
	if _u.mutation.SeverityCleared() {
		_spec.ClearField(reviewcomment.FieldSeverity, field.TypeEnum)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(reviewcomment.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(reviewcomment.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(reviewcomment.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewcomment.ReviewTable,
			Columns: []string{reviewcomment.ReviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewcomment.ReviewTable,
			Columns: []string{reviewcomment.ReviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reviewcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewCommentUpdateOne is the builder for updating a single ReviewComment entity.
type ReviewCommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewCommentMutation
}

// SetFilePath sets the "file_path" field.
func (_u *ReviewCommentUpdateOne) SetFilePath(v string) *ReviewCommentUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ReviewCommentUpdateOne) SetNillableFilePath(v *string) *ReviewCommentUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *ReviewCommentUpdateOne) SetStartLine(v int) *ReviewCommentUpdateOne {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *ReviewCommentUpdateOne) SetNillableStartLine(v *int) *ReviewCommentUpdateOne {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *ReviewCommentUpdateOne) AddStartLine(v int) *ReviewCommentUpdateOne {
	_u.mutation.AddStartLine(v)
	return _u
}

// ClearStartLine clears the value of the "start_line" field.
func (_u *ReviewCommentUpdateOne) ClearStartLine() *ReviewCommentUpdateOne {
	_u.mutation.ClearStartLine()
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *ReviewCommentUpdateOne) SetEndLine(v int) *ReviewCommentUpdateOne {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *ReviewCommentUpdateOne) SetNillableEndLine(v *int) *ReviewCommentUpdateOne {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *ReviewCommentUpdateOne) AddEndLine(v int) *ReviewCommentUpdateOne {
	_u.mutation.AddEndLine(v)
	return _u
}

// ClearEndLine clears the value of the "end_line" field.
func (_u *ReviewCommentUpdateOne) ClearEndLine() *ReviewCommentUpdateOne {
	_u.mutation.ClearEndLine()
	return _u
}

// SetSide sets the "side" field.
func (_u *ReviewCommentUpdateOne) SetSide(v reviewcomment.Side) *ReviewCommentUpdateOne {
	_u.mutation.SetSide(v)
	return _u
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_u *ReviewCommentUpdateOne) SetNillableSide(v *reviewcomment.Side) *ReviewCommentUpdateOne {
	if v != nil {
		_u.SetSide(*v)
	}
	return _u
}

// ClearSide clears the value of the "side" field.
func (_u *ReviewCommentUpdateOne) ClearSide() *ReviewCommentUpdateOne {
	_u.mutation.ClearSide()
	return _u
}

// SetBody sets the "body" field.
func (_u *ReviewCommentUpdateOne) SetBody(v string) *ReviewCommentUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ReviewCommentUpdateOne) SetNillableBody(v *string) *ReviewCommentUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *ReviewCommentUpdateOne) SetSeverity(v reviewcomment.Severity) *ReviewCommentUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *ReviewCommentUpdateOne) SetNillableSeverity(v *reviewcomment.Severity) *ReviewCommentUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// ClearSeverity clears the value of the "severity" field.
func (_u *ReviewCommentUpdateOne) ClearSeverity() *ReviewCommentUpdateOne {
	_u.mutation.ClearSeverity()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ReviewCommentUpdateOne) SetCategory(v string) *ReviewCommentUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ReviewCommentUpdateOne) SetNillableCategory(v *string) *ReviewCommentUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ReviewCommentUpdateOne) ClearCategory() *ReviewCommentUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReviewCommentUpdateOne) SetCreatedAt(v time.Time) *ReviewCommentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReviewCommentUpdateOne) SetNillableCreatedAt(v *time.Time) *ReviewCommentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReviewID sets the "review" edge to the Review entity by ID.
func (_u *ReviewCommentUpdateOne) SetReviewID(id uuid.UUID) *ReviewCommentUpdateOne {
	_u.mutation.SetReviewID(id)
	return _u
}

// SetReview sets the "review" edge to the Review entity.
func (_u *ReviewCommentUpdateOne) SetReview(v *Review) *ReviewCommentUpdateOne {
	return _u.SetReviewID(v.ID)
}

// Mutation returns the ReviewCommentMutation object of the builder.
func (_u *ReviewCommentUpdateOne) Mutation() *ReviewCommentMutation {
	return _u.mutation
}

// ClearReview clears the "review" edge to the Review entity.
func (_u *ReviewCommentUpdateOne) ClearReview() *ReviewCommentUpdateOne {
	_u.mutation.ClearReview()
	return _u
}

// Where appends a list predicates to the ReviewCommentUpdate builder.
func (_u *ReviewCommentUpdateOne) Where(ps ...predicate.ReviewComment) *ReviewCommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewCommentUpdateOne) Select(field string, fields ...string) *ReviewCommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReviewComment entity.
func (_u *ReviewCommentUpdateOne) Save(ctx context.Context) (*ReviewComment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewCommentUpdateOne) SaveX(ctx context.Context) *ReviewComment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewCommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewCommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewCommentUpdateOne) check() error {
	if v, ok := _u.mutation.Side(); ok {
		if err := reviewcomment.SideValidator(v); err != nil {
			return &ValidationError{Name: "side", err: fmt.Errorf(`ent: validator failed for field "ReviewComment.side": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := reviewcomment.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "ReviewComment.severity": %w`, err)}
		}
	}
	if _u.mutation.ReviewCleared() && len(_u.mutation.ReviewIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReviewComment.review"`)
	}
	return nil
}

func (_u *ReviewCommentUpdateOne) sqlSave(ctx context.Context) (_node *ReviewComment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reviewcomment.Table, reviewcomment.Columns, sqlgraph.NewFieldSpec(reviewcomment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReviewComment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reviewcomment.FieldID)
		for _, f := range fields {
			if !reviewcomment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reviewcomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(reviewcomment.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(reviewcomment.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(reviewcomment.FieldStartLine, field.TypeInt, value)
	}
	if _u.mutation.StartLineCleared() {
		_spec.ClearField(reviewcomment.FieldStartLine, field.TypeInt)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(reviewcomment.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(reviewcomment.FieldEndLine, field.TypeInt, value)
	}
	if _u.mutation.EndLineCleared() {
		_spec.ClearField(reviewcomment.FieldEndLine, field.TypeInt)
	}
	if value, ok := _u.mutation.Side(); ok {
		_spec.SetField(reviewcomment.FieldSide, field.TypeEnum, value)
	}
	if _u.mutation.SideCleared() {
		_spec.ClearField(reviewcomment.FieldSide, field.TypeEnum)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(reviewcomment.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(reviewcomment.FieldSeverity, field.TypeEnum, value)
	}
	if _u.mutation.SeverityCleared() {
		_spec.ClearField(reviewcomment.FieldSeverity, field.TypeEnum)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(reviewcomment.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(reviewcomment.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(reviewcomment.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewcomment.ReviewTable,
			Columns: []string{reviewcomment.ReviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewcomment.ReviewTable,
			Columns: []string{reviewcomment.ReviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReviewComment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reviewcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
