// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auto_resolve_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAutoResolveStats = `-- name: GetAutoResolveStats :one
SELECT
    COUNT(*)::int                               AS event_count,
    COALESCE(SUM(resolved_count), 0)::int       AS resolved_total,
    COALESCE(SUM(attempted_count), 0)::int      AS attempted_total,
    COALESCE(SUM(github_api_calls), 0)::int     AS api_calls_total
FROM auto_resolve_events
WHERE installation_id = ANY($1::bigint[])
  AND created_at >= NOW() - $2::interval
`

type GetAutoResolveStatsParams struct {
	InstallationIds []int64         `json:"installation_ids"`
	Period          pgtype.Interval `json:"period"`
}

type GetAutoResolveStatsRow struct {
	EventCount     int `json:"event_count"`
	ResolvedTotal  int `json:"resolved_total"`
	AttemptedTotal int `json:"attempted_total"`
	APICallsTotal  int `json:"api_calls_total"`
}

// Aggregate auto-resolve activity for an installation over a period.
// period is a Postgres interval literal like '7 days' or '30 days'.
func (q *Queries) GetAutoResolveStats(ctx context.Context, arg GetAutoResolveStatsParams) (GetAutoResolveStatsRow, error) {
	row := q.db.QueryRow(ctx, getAutoResolveStats, arg.InstallationIds, arg.Period)
	var i GetAutoResolveStatsRow
	err := row.Scan(
		&i.EventCount,
		&i.ResolvedTotal,
		&i.AttemptedTotal,
		&i.APICallsTotal,
	)
	return i, err
}

const getLearnLayerCounts = `-- name: GetLearnLayerCounts :one
SELECT
    COALESCE((
        SELECT COUNT(*) FROM patterns p
        WHERE p.installation_id = ANY($1::bigint[])
          AND p.created_at >= NOW() - $2::interval
    ), 0)::int AS patterns_learned,
    COALESCE((
        SELECT COUNT(*) FROM scenarios s
        WHERE s.installation_id = ANY($1::bigint[])
          AND s.created_at >= NOW() - $2::interval
    ), 0)::int AS scenarios_stored,
    COALESCE((
        SELECT COUNT(*) FROM decision_traces dt
        JOIN repos r ON dt.repo_id = r.id
        WHERE r.installation_id = ANY($1::bigint[])
          AND dt.created_at >= NOW() - $2::interval
    ), 0)::int AS decision_traces,
    COALESCE((
        SELECT COUNT(*) FROM comment_outcomes co
        JOIN review_comments rc ON co.review_comment_id = rc.id
        JOIN reviews rv ON rc.review_id = rv.id
        JOIN repos r ON rv.repo_id = r.id
        WHERE r.installation_id = ANY($1::bigint[])
          AND co.created_at >= NOW() - $2::interval
    ), 0)::int AS feedback_indexed
`

type GetLearnLayerCountsParams struct {
	InstallationIds []int64         `json:"installation_ids"`
	Period          pgtype.Interval `json:"period"`
}

type GetLearnLayerCountsRow struct {
	PatternsLearned int `json:"patterns_learned"`
	ScenariosStored int `json:"scenarios_stored"`
	DecisionTraces  int `json:"decision_traces"`
	FeedbackIndexed int `json:"feedback_indexed"`
}

// Counts new rows across the learn-layer tables for an installation in a
// period. Each subquery scopes to installation via the most direct column:
//
//	patterns, scenarios         — installation_id directly
//	decision_traces             — via reviews.repo_id -> repos.installation_id
//	comment_outcomes            — via review_comments.review_id -> ...
func (q *Queries) GetLearnLayerCounts(ctx context.Context, arg GetLearnLayerCountsParams) (GetLearnLayerCountsRow, error) {
	row := q.db.QueryRow(ctx, getLearnLayerCounts, arg.InstallationIds, arg.Period)
	var i GetLearnLayerCountsRow
	err := row.Scan(
		&i.PatternsLearned,
		&i.ScenariosStored,
		&i.DecisionTraces,
		&i.FeedbackIndexed,
	)
	return i, err
}

const insertAutoResolveEvent = `-- name: InsertAutoResolveEvent :exec

INSERT INTO auto_resolve_events
    (installation_id, repo_id, pr_number, source_sha,
     resolved_count, attempted_count, github_api_calls,
     resolved_thread_keys)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAutoResolveEventParams struct {
	InstallationID     int64    `json:"installation_id"`
	RepoID             int64    `json:"repo_id"`
	PRNumber           int      `json:"pr_number"`
	SourceSHA          string   `json:"source_sha"`
	ResolvedCount      int      `json:"resolved_count"`
	AttemptedCount     int      `json:"attempted_count"`
	GitHubAPICalls     int      `json:"github_api_calls"`
	ResolvedThreadKeys []string `json:"resolved_thread_keys"`
}

// Queries for auto_resolve_events — see migration 037.
func (q *Queries) InsertAutoResolveEvent(ctx context.Context, arg InsertAutoResolveEventParams) error {
	_, err := q.db.Exec(ctx, insertAutoResolveEvent,
		arg.InstallationID,
		arg.RepoID,
		arg.PRNumber,
		arg.SourceSHA,
		arg.ResolvedCount,
		arg.AttemptedCount,
		arg.GitHubAPICalls,
		arg.ResolvedThreadKeys,
	)
	return err
}
