// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph.sql

package db

import (
	"context"
)

const deleteNodesByFile = `-- name: DeleteNodesByFile :exec
DELETE FROM code_nodes WHERE repo_id = $1 AND file_path = $2
`

type DeleteNodesByFileParams struct {
	RepoID   int64  `json:"repo_id"`
	FilePath string `json:"file_path"`
}

func (q *Queries) DeleteNodesByFile(ctx context.Context, arg DeleteNodesByFileParams) error {
	_, err := q.db.Exec(ctx, deleteNodesByFile, arg.RepoID, arg.FilePath)
	return err
}

const deleteUnmergedNodesByPR = `-- name: DeleteUnmergedNodesByPR :exec
DELETE FROM code_nodes WHERE repo_id = $1 AND pr_number = $2 AND is_merged = false
`

type DeleteUnmergedNodesByPRParams struct {
	RepoID   int64 `json:"repo_id"`
	PRNumber *int  `json:"pr_number"`
}

func (q *Queries) DeleteUnmergedNodesByPR(ctx context.Context, arg DeleteUnmergedNodesByPRParams) error {
	_, err := q.db.Exec(ctx, deleteUnmergedNodesByPR, arg.RepoID, arg.PRNumber)
	return err
}

const getBlastRadius = `-- name: GetBlastRadius :many
WITH RECURSIVE affected AS (
    SELECT id, name, file_path, kind, 0 as depth
    FROM code_nodes WHERE code_nodes.repo_id = $1 AND code_nodes.file_path = ANY($2::text[])
    UNION
    SELECT cn.id, cn.name, cn.file_path, cn.kind, a.depth + 1
    FROM code_nodes cn
    JOIN code_edges ce ON ce.source_id = cn.id
    JOIN affected a ON ce.target_id = a.id
    WHERE a.depth < $3::int AND cn.repo_id = $1
)
SELECT DISTINCT id, name, file_path, kind, depth FROM affected ORDER BY depth, file_path LIMIT 50
`

type GetBlastRadiusParams struct {
	RepoID    int64    `json:"repo_id"`
	FilePaths []string `json:"file_paths"`
	MaxDepth  int      `json:"max_depth"`
}

type GetBlastRadiusRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	FilePath string `json:"file_path"`
	Kind     string `json:"kind"`
	Depth    int32  `json:"depth"`
}

func (q *Queries) GetBlastRadius(ctx context.Context, arg GetBlastRadiusParams) ([]GetBlastRadiusRow, error) {
	rows, err := q.db.Query(ctx, getBlastRadius, arg.RepoID, arg.FilePaths, arg.MaxDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlastRadiusRow
	for rows.Next() {
		var i GetBlastRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FilePath,
			&i.Kind,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileBugCount = `-- name: GetFileBugCount :one
SELECT COUNT(*)::int as bugs
FROM review_comments rc
JOIN reviews r ON r.id = rc.review_id
WHERE r.repo_id = $1 AND rc.file_path = $2 AND rc.severity IN ('critical','warning')
`

type GetFileBugCountParams struct {
	RepoID   int64  `json:"repo_id"`
	FilePath string `json:"file_path"`
}

// Single-file bug count for review prompt enrichment.
func (q *Queries) GetFileBugCount(ctx context.Context, arg GetFileBugCountParams) (int, error) {
	row := q.db.QueryRow(ctx, getFileBugCount, arg.RepoID, arg.FilePath)
	var bugs int
	err := row.Scan(&bugs)
	return bugs, err
}

const getFileFanIn = `-- name: GetFileFanIn :one
SELECT COUNT(DISTINCT src.file_path)::int as fan_in
FROM code_edges ce
JOIN code_nodes src ON src.id = ce.source_id
JOIN code_nodes tgt ON tgt.id = ce.target_id
WHERE ce.repo_id = $1 AND tgt.file_path = $2 AND src.file_path != tgt.file_path
`

type GetFileFanInParams struct {
	RepoID   int64  `json:"repo_id"`
	FilePath string `json:"file_path"`
}

// Single-file fan-in lookup for review prompt enrichment.
func (q *Queries) GetFileFanIn(ctx context.Context, arg GetFileFanInParams) (int, error) {
	row := q.db.QueryRow(ctx, getFileFanIn, arg.RepoID, arg.FilePath)
	var fan_in int
	err := row.Scan(&fan_in)
	return fan_in, err
}

const getTopChokePoints = `-- name: GetTopChokePoints :many
SELECT tgt.file_path, COUNT(DISTINCT src.file_path)::int as fan_in
FROM code_edges ce
JOIN code_nodes src ON src.id = ce.source_id
JOIN code_nodes tgt ON tgt.id = ce.target_id
WHERE ce.repo_id = $1 AND src.file_path != tgt.file_path
GROUP BY tgt.file_path
ORDER BY fan_in DESC
LIMIT $2
`

type GetTopChokePointsParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int32 `json:"limit"`
}

type GetTopChokePointsRow struct {
	FilePath string `json:"file_path"`
	FanIn    int    `json:"fan_in"`
}

// Top files by fan_in (used for review prompt context injection + memory indexing).
func (q *Queries) GetTopChokePoints(ctx context.Context, arg GetTopChokePointsParams) ([]GetTopChokePointsRow, error) {
	rows, err := q.db.Query(ctx, getTopChokePoints, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopChokePointsRow
	for rows.Next() {
		var i GetTopChokePointsRow
		if err := rows.Scan(&i.FilePath, &i.FanIn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchBugDensity = `-- name: ListArchBugDensity :many
SELECT rc.file_path,
       COUNT(DISTINCT CONCAT(r.pr_number::text, ':', COALESCE(rc.end_line::text, '0')))
           FILTER (WHERE rc.severity IN ('critical','warning'))::int AS bugs,
       COUNT(DISTINCT r.pr_number)::int AS prs
FROM review_comments rc
JOIN reviews r ON r.id = rc.review_id
WHERE r.repo_id = $1
GROUP BY rc.file_path
`

type ListArchBugDensityRow struct {
	FilePath string `json:"file_path"`
	Bugs     int    `json:"bugs"`
	Prs      int    `json:"prs"`
}

// Returns bug count + PR count per file for bug density and change frequency metrics.
// Bugs are deduped by (pr_number, end_line) so a single defect reported many
// times in one PR counts once — a noisy PR no longer inflates density.
func (q *Queries) ListArchBugDensity(ctx context.Context, repoID int64) ([]ListArchBugDensityRow, error) {
	rows, err := q.db.Query(ctx, listArchBugDensity, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchBugDensityRow
	for rows.Next() {
		var i ListArchBugDensityRow
		if err := rows.Scan(&i.FilePath, &i.Bugs, &i.Prs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchCoupling = `-- name: ListArchCoupling :many
SELECT r.pr_number, array_agg(DISTINCT rc.file_path)::text[] AS files
FROM review_comments rc
JOIN reviews r ON r.id = rc.review_id
WHERE r.repo_id = $1 AND r.status = 'completed'
GROUP BY r.pr_number
ORDER BY r.pr_number DESC
LIMIT 200
`

type ListArchCouplingRow struct {
	PRNumber int      `json:"pr_number"`
	Files    []string `json:"files"`
}

// Returns last 200 PRs with their touched files for Jaccard co-change coupling.
func (q *Queries) ListArchCoupling(ctx context.Context, repoID int64) ([]ListArchCouplingRow, error) {
	rows, err := q.db.Query(ctx, listArchCoupling, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchCouplingRow
	for rows.Next() {
		var i ListArchCouplingRow
		if err := rows.Scan(&i.PRNumber, &i.Files); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchFileEdges = `-- name: ListArchFileEdges :many
SELECT src.file_path as source_path, tgt.file_path as target_path, ce.kind
FROM code_edges ce
JOIN code_nodes src ON src.id = ce.source_id
JOIN code_nodes tgt ON tgt.id = ce.target_id
WHERE ce.repo_id = $1 AND src.file_path != tgt.file_path
`

type ListArchFileEdgesRow struct {
	SourcePath string `json:"source_path"`
	TargetPath string `json:"target_path"`
	Kind       string `json:"kind"`
}

// Returns inter-file edges (excludes self-references) for fan-in/fan-out + edge graph.
func (q *Queries) ListArchFileEdges(ctx context.Context, repoID int64) ([]ListArchFileEdgesRow, error) {
	rows, err := q.db.Query(ctx, listArchFileEdges, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchFileEdgesRow
	for rows.Next() {
		var i ListArchFileEdgesRow
		if err := rows.Scan(&i.SourcePath, &i.TargetPath, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchNodes = `-- name: ListArchNodes :many
SELECT file_path, COALESCE(language, '')::text as language, name,
       (COALESCE(line_end, 0) - COALESCE(line_start, 0) + 1)::int as line_span
FROM code_nodes
WHERE repo_id = $1
ORDER BY file_path, line_start
`

type ListArchNodesRow struct {
	FilePath string `json:"file_path"`
	Language string `json:"language"`
	Name     string `json:"name"`
	LineSpan int    `json:"line_span"`
}

// Returns all code nodes for a repo, used to compute file-level architecture metrics.
func (q *Queries) ListArchNodes(ctx context.Context, repoID int64) ([]ListArchNodesRow, error) {
	rows, err := q.db.Query(ctx, listArchNodes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchNodesRow
	for rows.Next() {
		var i ListArchNodesRow
		if err := rows.Scan(
			&i.FilePath,
			&i.Language,
			&i.Name,
			&i.LineSpan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphEdges = `-- name: ListGraphEdges :many
SELECT ce.id, ce.repo_id, ce.source_id, ce.target_id, ce.kind,
       sn.name as source_name, tn.name as target_name
FROM code_edges ce
JOIN code_nodes sn ON sn.id = ce.source_id
JOIN code_nodes tn ON tn.id = ce.target_id
WHERE ce.repo_id = $1
`

type ListGraphEdgesRow struct {
	ID         int64  `json:"id"`
	RepoID     int64  `json:"repo_id"`
	SourceID   int64  `json:"source_id"`
	TargetID   int64  `json:"target_id"`
	Kind       string `json:"kind"`
	SourceName string `json:"source_name"`
	TargetName string `json:"target_name"`
}

func (q *Queries) ListGraphEdges(ctx context.Context, repoID int64) ([]ListGraphEdgesRow, error) {
	rows, err := q.db.Query(ctx, listGraphEdges, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGraphEdgesRow
	for rows.Next() {
		var i ListGraphEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.SourceID,
			&i.TargetID,
			&i.Kind,
			&i.SourceName,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphNodes = `-- name: ListGraphNodes :many
SELECT id, repo_id, kind, name, file_path, line_start, line_end, language, pr_number, is_merged
FROM code_nodes WHERE repo_id = $1 ORDER BY file_path, name
`

type ListGraphNodesRow struct {
	ID        int64   `json:"id"`
	RepoID    int64   `json:"repo_id"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	FilePath  string  `json:"file_path"`
	LineStart *int    `json:"line_start"`
	LineEnd   *int    `json:"line_end"`
	Language  *string `json:"language"`
	PRNumber  *int    `json:"pr_number"`
	IsMerged  bool    `json:"is_merged"`
}

func (q *Queries) ListGraphNodes(ctx context.Context, repoID int64) ([]ListGraphNodesRow, error) {
	rows, err := q.db.Query(ctx, listGraphNodes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGraphNodesRow
	for rows.Next() {
		var i ListGraphNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Kind,
			&i.Name,
			&i.FilePath,
			&i.LineStart,
			&i.LineEnd,
			&i.Language,
			&i.PRNumber,
			&i.IsMerged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodesMerged = `-- name: MarkNodesMerged :exec
UPDATE code_nodes SET is_merged = true WHERE repo_id = $1 AND pr_number = $2
`

type MarkNodesMergedParams struct {
	RepoID   int64 `json:"repo_id"`
	PRNumber *int  `json:"pr_number"`
}

func (q *Queries) MarkNodesMerged(ctx context.Context, arg MarkNodesMergedParams) error {
	_, err := q.db.Exec(ctx, markNodesMerged, arg.RepoID, arg.PRNumber)
	return err
}

const upsertCodeEdge = `-- name: UpsertCodeEdge :exec
INSERT INTO code_edges (repo_id, source_id, target_id, kind, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (repo_id, source_id, target_id, kind) DO NOTHING
`

type UpsertCodeEdgeParams struct {
	RepoID   int64  `json:"repo_id"`
	SourceID int64  `json:"source_id"`
	TargetID int64  `json:"target_id"`
	Kind     string `json:"kind"`
}

func (q *Queries) UpsertCodeEdge(ctx context.Context, arg UpsertCodeEdgeParams) error {
	_, err := q.db.Exec(ctx, upsertCodeEdge,
		arg.RepoID,
		arg.SourceID,
		arg.TargetID,
		arg.Kind,
	)
	return err
}

const upsertCodeNode = `-- name: UpsertCodeNode :one
INSERT INTO code_nodes (repo_id, kind, name, file_path, line_start, line_end, language, pr_number, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (repo_id, file_path, kind, name)
DO UPDATE SET line_start = $5, line_end = $6, language = $7, pr_number = $8, updated_at = NOW()
RETURNING id
`

type UpsertCodeNodeParams struct {
	RepoID    int64   `json:"repo_id"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	FilePath  string  `json:"file_path"`
	LineStart *int    `json:"line_start"`
	LineEnd   *int    `json:"line_end"`
	Language  *string `json:"language"`
	PRNumber  *int    `json:"pr_number"`
}

func (q *Queries) UpsertCodeNode(ctx context.Context, arg UpsertCodeNodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertCodeNode,
		arg.RepoID,
		arg.Kind,
		arg.Name,
		arg.FilePath,
		arg.LineStart,
		arg.LineEnd,
		arg.Language,
		arg.PRNumber,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
