// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: installations.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const createInstallation = `-- name: CreateInstallation :one
INSERT INTO installations (installation_id, org_login)
VALUES ($1, $2)
ON CONFLICT (installation_id) DO UPDATE SET org_login = $2
RETURNING id, installation_id, org_login, clerk_org_id, created_at, suspended_at
`

type CreateInstallationParams struct {
	InstallationID int64  `json:"installation_id"`
	OrgLogin       string `json:"org_login"`
}

type CreateInstallationRow struct {
	ID             int64      `json:"id"`
	InstallationID int64      `json:"installation_id"`
	OrgLogin       string     `json:"org_login"`
	ClerkOrgID     *string    `json:"clerk_org_id"`
	CreatedAt      time.Time  `json:"created_at"`
	SuspendedAt    *time.Time `json:"suspended_at"`
}

func (q *Queries) CreateInstallation(ctx context.Context, arg CreateInstallationParams) (CreateInstallationRow, error) {
	row := q.db.QueryRow(ctx, createInstallation, arg.InstallationID, arg.OrgLogin)
	var i CreateInstallationRow
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgLogin,
		&i.ClerkOrgID,
		&i.CreatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const getInstallation = `-- name: GetInstallation :one
SELECT id, installation_id, org_login, clerk_org_id, created_at, suspended_at
FROM installations WHERE id = $1
`

type GetInstallationRow struct {
	ID             int64      `json:"id"`
	InstallationID int64      `json:"installation_id"`
	OrgLogin       string     `json:"org_login"`
	ClerkOrgID     *string    `json:"clerk_org_id"`
	CreatedAt      time.Time  `json:"created_at"`
	SuspendedAt    *time.Time `json:"suspended_at"`
}

func (q *Queries) GetInstallation(ctx context.Context, id int64) (GetInstallationRow, error) {
	row := q.db.QueryRow(ctx, getInstallation, id)
	var i GetInstallationRow
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgLogin,
		&i.ClerkOrgID,
		&i.CreatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const getInstallationByClerkOrgID = `-- name: GetInstallationByClerkOrgID :one
SELECT id, installation_id, org_login, clerk_org_id, created_at, suspended_at
FROM installations WHERE clerk_org_id = $1
`

type GetInstallationByClerkOrgIDRow struct {
	ID             int64      `json:"id"`
	InstallationID int64      `json:"installation_id"`
	OrgLogin       string     `json:"org_login"`
	ClerkOrgID     *string    `json:"clerk_org_id"`
	CreatedAt      time.Time  `json:"created_at"`
	SuspendedAt    *time.Time `json:"suspended_at"`
}

func (q *Queries) GetInstallationByClerkOrgID(ctx context.Context, clerkOrgID *string) (GetInstallationByClerkOrgIDRow, error) {
	row := q.db.QueryRow(ctx, getInstallationByClerkOrgID, clerkOrgID)
	var i GetInstallationByClerkOrgIDRow
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgLogin,
		&i.ClerkOrgID,
		&i.CreatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const getInstallationByGitHubID = `-- name: GetInstallationByGitHubID :one
SELECT id, installation_id, org_login, clerk_org_id, created_at, suspended_at
FROM installations WHERE installation_id = $1
`

type GetInstallationByGitHubIDRow struct {
	ID             int64      `json:"id"`
	InstallationID int64      `json:"installation_id"`
	OrgLogin       string     `json:"org_login"`
	ClerkOrgID     *string    `json:"clerk_org_id"`
	CreatedAt      time.Time  `json:"created_at"`
	SuspendedAt    *time.Time `json:"suspended_at"`
}

func (q *Queries) GetInstallationByGitHubID(ctx context.Context, installationID int64) (GetInstallationByGitHubIDRow, error) {
	row := q.db.QueryRow(ctx, getInstallationByGitHubID, installationID)
	var i GetInstallationByGitHubIDRow
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgLogin,
		&i.ClerkOrgID,
		&i.CreatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const getInstallationFeatureFlags = `-- name: GetInstallationFeatureFlags :one
SELECT COALESCE(feature_flags, '{}')::jsonb FROM installations WHERE id = $1
`

func (q *Queries) GetInstallationFeatureFlags(ctx context.Context, id int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getInstallationFeatureFlags, id)
	var column_1 json.RawMessage
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrgDefaults = `-- name: GetOrgDefaults :one
SELECT COALESCE(default_settings, '{}')::jsonb FROM installations WHERE id = $1
`

func (q *Queries) GetOrgDefaults(ctx context.Context, id int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getOrgDefaults, id)
	var column_1 json.RawMessage
	err := row.Scan(&column_1)
	return column_1, err
}

const mergeInstallationFeatureFlags = `-- name: MergeInstallationFeatureFlags :exec
UPDATE installations SET feature_flags = feature_flags || $1::jsonb WHERE id = $2
`

type MergeInstallationFeatureFlagsParams struct {
	Patch json.RawMessage `json:"patch"`
	ID    int64           `json:"id"`
}

// Merge the given keys into feature_flags, leaving every other key intact.
// jsonb || jsonb is a right-biased top-level merge applied inside the UPDATE,
// so there is no read-modify-write window: an operator setting another key
// by hand cannot be silently reverted by a concurrent settings save. The
// column is NOT NULL (migration 030) with a jsonb_typeof = 'object' CHECK
// (032), so both operands are always objects.
func (q *Queries) MergeInstallationFeatureFlags(ctx context.Context, arg MergeInstallationFeatureFlagsParams) error {
	_, err := q.db.Exec(ctx, mergeInstallationFeatureFlags, arg.Patch, arg.ID)
	return err
}

const setInstallationClerkOrgID = `-- name: SetInstallationClerkOrgID :exec
UPDATE installations SET clerk_org_id = $1 WHERE id = $2
`

type SetInstallationClerkOrgIDParams struct {
	ClerkOrgID *string `json:"clerk_org_id"`
	ID         int64   `json:"id"`
}

func (q *Queries) SetInstallationClerkOrgID(ctx context.Context, arg SetInstallationClerkOrgIDParams) error {
	_, err := q.db.Exec(ctx, setInstallationClerkOrgID, arg.ClerkOrgID, arg.ID)
	return err
}

const setOrgDefaults = `-- name: SetOrgDefaults :exec
UPDATE installations SET default_settings = $1 WHERE id = $2
`

type SetOrgDefaultsParams struct {
	DefaultSettings []byte `json:"default_settings"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetOrgDefaults(ctx context.Context, arg SetOrgDefaultsParams) error {
	_, err := q.db.Exec(ctx, setOrgDefaults, arg.DefaultSettings, arg.ID)
	return err
}

const suspendInstallation = `-- name: SuspendInstallation :exec
UPDATE installations SET suspended_at = NOW() WHERE installation_id = $1
`

func (q *Queries) SuspendInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, suspendInstallation, installationID)
	return err
}
