// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: migrate.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listCommentOutcomesForBackfill = `-- name: ListCommentOutcomesForBackfill :many
SELECT co.id, co.outcome,
       rc.file_path, rc.category, rc.body,
       rv.pr_number, r.full_name,
       COALESCE(co.created_at, 'epoch'::timestamptz) AS created_at
FROM comment_outcomes co
JOIN review_comments rc ON rc.id = co.review_comment_id
JOIN reviews rv ON rv.id = rc.review_id
JOIN repos r ON r.id = rv.repo_id
WHERE r.installation_id = $1
  AND co.outcome IN ('confirmed', 'dismissed')
  AND rc.category IS NOT NULL
  AND co.id > $2
ORDER BY co.id ASC
LIMIT $3
`

type ListCommentOutcomesForBackfillParams struct {
	InstallationID int64 `json:"installation_id"`
	ID             int   `json:"id"`
	Limit          int32 `json:"limit"`
}

type ListCommentOutcomesForBackfillRow struct {
	ID        int        `json:"id"`
	Outcome   string     `json:"outcome"`
	FilePath  string     `json:"file_path"`
	Category  *string    `json:"category"`
	Body      string     `json:"body"`
	PRNumber  int        `json:"pr_number"`
	FullName  string     `json:"full_name"`
	CreatedAt *time.Time `json:"created_at"`
}

// (c) comment_outcomes → type=feedback docs. Only confirmed/dismissed (ignored
// has no feedback shape). Category must be present — the pipeline only indexes
// feedback when the comment carries a category. created_at drives the
// --new-shape-since cutoff.
//
// content is body-only. The live pipeline's reply-origin feedback (reply.go)
// appended a "Developer[ explanation]:" reply suffix, but that reply text was
// NEVER persisted to Postgres: CollectReplyTrace (which would have written a
// developer_agreed/developer_dismissed decision_trace) has ZERO callers, so no
// such traces exist to recover it from. Reply text is therefore an SM-only data
// category; body-only is the accepted re-derivation. The feedback customID
// hashes the stored comment body + action (reply text is NOT in the customID),
// so confirmed and dismissed coexist and the customID is exact — the cutoff
// still excludes post-deploy rows so a differing (suffix-carrying) live doc is
// never content-merged.
func (q *Queries) ListCommentOutcomesForBackfill(ctx context.Context, arg ListCommentOutcomesForBackfillParams) ([]ListCommentOutcomesForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listCommentOutcomesForBackfill, arg.InstallationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentOutcomesForBackfillRow
	for rows.Next() {
		var i ListCommentOutcomesForBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.Outcome,
			&i.FilePath,
			&i.Category,
			&i.Body,
			&i.PRNumber,
			&i.FullName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatternsForBackfill = `-- name: ListPatternsForBackfill :many
SELECT p.id, p.repo_id, p.content, COALESCE(p.source, 'manual') AS source,
       p.category, p.pr_number, p.supermemory_id AS old_sm_id, r.full_name
FROM patterns p
LEFT JOIN repos r ON r.id = p.repo_id
WHERE p.installation_id = $1 AND p.id > $2
ORDER BY p.id ASC
LIMIT $3
`

type ListPatternsForBackfillParams struct {
	InstallationID int64 `json:"installation_id"`
	ID             int   `json:"id"`
	Limit          int32 `json:"limit"`
}

type ListPatternsForBackfillRow struct {
	ID       int     `json:"id"`
	RepoID   *int64  `json:"repo_id"`
	Content  string  `json:"content"`
	Source   string  `json:"source"`
	Category *string `json:"category"`
	PRNumber *int    `json:"pr_number"`
	OldSmID  *string `json:"old_sm_id"`
	FullName *string `json:"full_name"`
}

// (b) patterns → type=pattern docs. LEFT JOIN repos: NULL repo_id is an
// org-wide/shared pattern (→ _shared); non-NULL routes to {repo}. old_sm_id is
// the current (legacy) supermemory_id, captured so the caller can remap
// pattern_stats from the legacy id to the new one before overwriting the column.
func (q *Queries) ListPatternsForBackfill(ctx context.Context, arg ListPatternsForBackfillParams) ([]ListPatternsForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listPatternsForBackfill, arg.InstallationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatternsForBackfillRow
	for rows.Next() {
		var i ListPatternsForBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Content,
			&i.Source,
			&i.Category,
			&i.PRNumber,
			&i.OldSmID,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoFullNamesForInstallation = `-- name: ListRepoFullNamesForInstallation :many
SELECT full_name FROM repos WHERE installation_id = $1 ORDER BY id ASC
`

// Owner/repo full_names for one installation, used by --verify-legacy to build
// the legacy container tags whose doc counts feed the count-verify gate.
func (q *Queries) ListRepoFullNamesForInstallation(ctx context.Context, installationID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRepoFullNamesForInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var full_name string
		if err := rows.Scan(&full_name); err != nil {
			return nil, err
		}
		items = append(items, full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewCommentsForBackfill = `-- name: ListReviewCommentsForBackfill :many

SELECT rc.id, rc.file_path, rc.severity, rc.category, rc.body,
       rv.pr_number, rv.pr_author, rv.id AS review_id, r.full_name, rc.created_at
FROM review_comments rc
JOIN reviews rv ON rv.id = rc.review_id
JOIN repos r ON r.id = rv.repo_id
WHERE r.installation_id = $1 AND rc.id > $2
ORDER BY rc.id ASC
LIMIT $3
`

type ListReviewCommentsForBackfillParams struct {
	InstallationID int64     `json:"installation_id"`
	ID             uuid.UUID `json:"id"`
	Limit          int32     `json:"limit"`
}

type ListReviewCommentsForBackfillRow struct {
	ID        uuid.UUID `json:"id"`
	FilePath  string    `json:"file_path"`
	Severity  *string   `json:"severity"`
	Category  *string   `json:"category"`
	Body      string    `json:"body"`
	PRNumber  int       `json:"pr_number"`
	PRAuthor  string    `json:"pr_author"`
	ReviewID  uuid.UUID `json:"review_id"`
	FullName  string    `json:"full_name"`
	CreatedAt time.Time `json:"created_at"`
}

// Backfill queries for cmd/migrate-memory. Each re-derives one memory doc type
// from Postgres (the source of truth) so the backfill can seed the unified
// {repo}/_shared Supermemory containers. All are keyset-paginated by the
// table's primary key ($2 = last-seen id cursor, $3 = page size) so a full
// sweep is a single forward scan with no OFFSET blowup. Ordering is by id ASC;
// for UUID PKs (reviews, review_comments) the order is stable-but-not-temporal,
// which is fine for a complete one-shot sweep.
// (a) review_comments → type=review docs. Joined up to reviews (pr_number,
// pr_author, review id) and repos (full_name → container tag). created_at is
// returned so the caller can apply the --new-shape-since cutoff.
//
// customID CAVEAT: the review doc customID is backfill-internal ONLY. The live
// pipeline hashes the RAW finding body, which Postgres does not persist
// (review_comments.body is the GitHub-formatted body from formatCommentBody), so
// the backfill hashes the stored body — deterministic + idempotent across
// re-runs, but NOT collision-identical to a live pipeline write. The
// --new-shape-since cutoff skips post-deploy rows so this non-identical customID
// can't duplicate (or, via the batch API's '---' content merge, corrupt) a doc
// the pipeline already wrote into the new container.
func (q *Queries) ListReviewCommentsForBackfill(ctx context.Context, arg ListReviewCommentsForBackfillParams) ([]ListReviewCommentsForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listReviewCommentsForBackfill, arg.InstallationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewCommentsForBackfillRow
	for rows.Next() {
		var i ListReviewCommentsForBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Severity,
			&i.Category,
			&i.Body,
			&i.PRNumber,
			&i.PRAuthor,
			&i.ReviewID,
			&i.FullName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewSummariesForBackfill = `-- name: ListReviewSummariesForBackfill :many
SELECT rv.id, rv.pr_number, rv.pr_title, rv.pr_author,
       COALESCE(rv.summary, '') AS summary, rv.score, r.full_name,
       COALESCE((SELECT string_agg(DISTINCT rc.file_path, ', ')
                 FROM review_comments rc WHERE rc.review_id = rv.id), '')::text AS files,
       rv.created_at
FROM reviews rv
JOIN repos r ON r.id = rv.repo_id
WHERE r.installation_id = $1 AND rv.summary IS NOT NULL AND rv.id > $2
ORDER BY rv.id ASC
LIMIT $3
`

type ListReviewSummariesForBackfillParams struct {
	InstallationID int64     `json:"installation_id"`
	ID             uuid.UUID `json:"id"`
	Limit          int32     `json:"limit"`
}

type ListReviewSummariesForBackfillRow struct {
	ID        uuid.UUID `json:"id"`
	PRNumber  int       `json:"pr_number"`
	PRTitle   string    `json:"pr_title"`
	PRAuthor  string    `json:"pr_author"`
	Summary   string    `json:"summary"`
	Score     *int      `json:"score"`
	FullName  string    `json:"full_name"`
	Files     string    `json:"files"`
	CreatedAt time.Time `json:"created_at"`
}

// (g) reviews (summary present) → type=pr_summary docs. created_at drives the
// --new-shape-since cutoff. The customID = PRSummaryCustomID(repo, pr_number) is
// exact, but the content is NOT byte-reproducible: the live pipeline builds it
// from run.Synthesis + the full reviewed-file list, while the backfill rebuilds
// it from the reviews columns and approximates `files` from the commented files.
// Because the batch API merges differing content under the same customId, the
// cutoff skips post-deploy rows so this approximate content can't corrupt a doc
// the pipeline already wrote.
func (q *Queries) ListReviewSummariesForBackfill(ctx context.Context, arg ListReviewSummariesForBackfillParams) ([]ListReviewSummariesForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listReviewSummariesForBackfill, arg.InstallationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewSummariesForBackfillRow
	for rows.Next() {
		var i ListReviewSummariesForBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.PRNumber,
			&i.PRTitle,
			&i.PRAuthor,
			&i.Summary,
			&i.Score,
			&i.FullName,
			&i.Files,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesForBackfill = `-- name: ListRulesForBackfill :many
SELECT id, category, content, priority
FROM rules
WHERE installation_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListRulesForBackfillParams struct {
	InstallationID *int64 `json:"installation_id"`
	ID             int64  `json:"id"`
	Limit          int32  `json:"limit"`
}

type ListRulesForBackfillRow struct {
	ID       int64  `json:"id"`
	Category string `json:"category"`
	Content  string `json:"content"`
	Priority int    `json:"priority"`
}

// (f) rules → type=rule docs in _shared. Prod has 0 rules today; implemented
// for completeness.
func (q *Queries) ListRulesForBackfill(ctx context.Context, arg ListRulesForBackfillParams) ([]ListRulesForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listRulesForBackfill, arg.InstallationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesForBackfillRow
	for rows.Next() {
		var i ListRulesForBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Content,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenariosForBackfill = `-- name: ListScenariosForBackfill :many
SELECT s.id, s.repo_id, s.description, s.severity, s.files, r.full_name
FROM scenarios s
JOIN repos r ON r.id = s.repo_id
WHERE s.installation_id = $1 AND s.repo_id IS NOT NULL AND s.active = TRUE
  AND s.id > $2
ORDER BY s.id ASC
LIMIT $3
`

type ListScenariosForBackfillParams struct {
	InstallationID int64 `json:"installation_id"`
	ID             int64 `json:"id"`
	Limit          int32 `json:"limit"`
}

type ListScenariosForBackfillRow struct {
	ID          int64    `json:"id"`
	RepoID      *int64   `json:"repo_id"`
	Description string   `json:"description"`
	Severity    *string  `json:"severity"`
	Files       []string `json:"files"`
	FullName    string   `json:"full_name"`
}

// (d) scenarios → type=scenario docs. Active + repo-scoped only, matching the
// reconciler: NULL-repo scenarios cannot route to a {repo} container.
func (q *Queries) ListScenariosForBackfill(ctx context.Context, arg ListScenariosForBackfillParams) ([]ListScenariosForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listScenariosForBackfill, arg.InstallationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenariosForBackfillRow
	for rows.Next() {
		var i ListScenariosForBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Description,
			&i.Severity,
			&i.Files,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracesForBackfill = `-- name: ListTracesForBackfill :many
SELECT dt.id, dt.repo_id, dt.file_path, dt.trace_type, dt.content,
       COALESCE(dt.severity, '') AS severity, r.full_name
FROM decision_traces dt
JOIN repos r ON r.id = dt.repo_id
WHERE r.installation_id = $1 AND dt.id > $2
ORDER BY dt.id ASC
LIMIT $3
`

type ListTracesForBackfillParams struct {
	InstallationID int64 `json:"installation_id"`
	ID             int64 `json:"id"`
	Limit          int32 `json:"limit"`
}

type ListTracesForBackfillRow struct {
	ID        int64  `json:"id"`
	RepoID    int64  `json:"repo_id"`
	FilePath  string `json:"file_path"`
	TraceType string `json:"trace_type"`
	Content   string `json:"content"`
	Severity  string `json:"severity"`
	FullName  string `json:"full_name"`
}

// (e) decision_traces → type=trace docs. repo_id is NOT NULL at the schema
// level; joined to repos for installation scoping + full_name.
func (q *Queries) ListTracesForBackfill(ctx context.Context, arg ListTracesForBackfillParams) ([]ListTracesForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listTracesForBackfill, arg.InstallationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracesForBackfillRow
	for rows.Next() {
		var i ListTracesForBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.FilePath,
			&i.TraceType,
			&i.Content,
			&i.Severity,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remapPatternStatsSupermemoryID = `-- name: RemapPatternStatsSupermemoryID :execrows
UPDATE pattern_stats SET supermemory_id = $1, updated_at = NOW()
WHERE supermemory_id = $2
`

type RemapPatternStatsSupermemoryIDParams struct {
	NewID string `json:"new_id"`
	OldID string `json:"old_id"`
}

// Repoint a pattern_stats row from its legacy Supermemory id to the new backfill
// id. pattern_stats.supermemory_id is UNIQUE and previously pointed at the
// legacy doc; the migration overwrites patterns.supermemory_id, so this keeps
// the stats row joined to the live doc. Keyed on the legacy id (exact) rather
// than content_hash — pattern_stats has no writer in the codebase (empty in
// prod) and patterns has no content_hash column, so the legacy id is the only
// exact join key.
func (q *Queries) RemapPatternStatsSupermemoryID(ctx context.Context, arg RemapPatternStatsSupermemoryIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, remapPatternStatsSupermemoryID, arg.NewID, arg.OldID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
