// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID             int64     `json:"id"`
	Action         string    `json:"action"`
	Actor          *string   `json:"actor"`
	Resource       *string   `json:"resource"`
	Metadata       []byte    `json:"metadata"`
	CreatedAt      time.Time `json:"created_at"`
	InstallationID *int64    `json:"installation_id"`
}

type AutoResolveEvent struct {
	ID                 int64     `json:"id"`
	InstallationID     int64     `json:"installation_id"`
	RepoID             int64     `json:"repo_id"`
	PRNumber           int       `json:"pr_number"`
	SourceSHA          string    `json:"source_sha"`
	ResolvedCount      int       `json:"resolved_count"`
	AttemptedCount     int       `json:"attempted_count"`
	GitHubAPICalls     int       `json:"github_api_calls"`
	CreatedAt          time.Time `json:"created_at"`
	ResolvedThreadKeys []string  `json:"resolved_thread_keys"`
}

type CodeEdge struct {
	ID        int64      `json:"id"`
	RepoID    int64      `json:"repo_id"`
	SourceID  int64      `json:"source_id"`
	TargetID  int64      `json:"target_id"`
	Kind      string     `json:"kind"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type CodeNode struct {
	ID           int64      `json:"id"`
	RepoID       int64      `json:"repo_id"`
	Kind         string     `json:"kind"`
	Name         string     `json:"name"`
	FilePath     string     `json:"file_path"`
	LineStart    *int       `json:"line_start"`
	LineEnd      *int       `json:"line_end"`
	Language     *string    `json:"language"`
	UpdatedAt    *time.Time `json:"updated_at"`
	PRNumber     *int       `json:"pr_number"`
	IsMerged     bool       `json:"is_merged"`
	ReturnType   *string    `json:"return_type"`
	Params       *string    `json:"params"`
	Visibility   *string    `json:"visibility"`
	IsAsync      *bool      `json:"is_async"`
	ReceiverType *string    `json:"receiver_type"`
	Scope        *string    `json:"scope"`
	ContentHash  *string    `json:"content_hash"`
}

type CommentOutcome struct {
	ID              int        `json:"id"`
	ReviewCommentID uuid.UUID  `json:"review_comment_id"`
	Outcome         string     `json:"outcome"`
	CreatedAt       *time.Time `json:"created_at"`
}

type DecisionTrace struct {
	ID            int64      `json:"id"`
	RepoID        int64      `json:"repo_id"`
	FilePath      string     `json:"file_path"`
	SymbolName    *string    `json:"symbol_name"`
	TraceType     string     `json:"trace_type"`
	Content       string     `json:"content"`
	Severity      *string    `json:"severity"`
	ReviewID      *uuid.UUID `json:"review_id"`
	PRNumber      *int       `json:"pr_number"`
	Metadata      []byte     `json:"metadata"`
	CreatedAt     *time.Time `json:"created_at"`
	SupermemoryID *string    `json:"supermemory_id"`
}

type Installation struct {
	ID                int64           `json:"id"`
	InstallationID    int64           `json:"installation_id"`
	OrgLogin          string          `json:"org_login"`
	CreatedAt         time.Time       `json:"created_at"`
	SuspendedAt       *time.Time      `json:"suspended_at"`
	ClerkOrgID        *string         `json:"clerk_org_id"`
	PlanTier          string          `json:"plan_tier"`
	DefaultSettings   []byte          `json:"default_settings"`
	FeatureFlags      json.RawMessage `json:"feature_flags"`
	SupermemoryKeyEnc *string         `json:"supermemory_key_enc"`
}

type ModelConfig struct {
	ID             int64     `json:"id"`
	RepoID         *int64    `json:"repo_id"`
	Stage          string    `json:"stage"`
	Provider       string    `json:"provider"`
	Model          string    `json:"model"`
	BaseURL        *string   `json:"base_url"`
	MaxTokens      int       `json:"max_tokens"`
	Temperature    float32   `json:"temperature"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	InstallationID *int64    `json:"installation_id"`
}

type ModelPricing struct {
	ID               int64          `json:"id"`
	ModelPattern     string         `json:"model_pattern"`
	InputPerMillion  pgtype.Numeric `json:"input_per_million"`
	OutputPerMillion pgtype.Numeric `json:"output_per_million"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type Pattern struct {
	ID             int        `json:"id"`
	InstallationID int64      `json:"installation_id"`
	RepoID         *int64     `json:"repo_id"`
	Content        string     `json:"content"`
	SupermemoryID  *string    `json:"supermemory_id"`
	CreatedBy      *string    `json:"created_by"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
	Source         *string    `json:"source"`
	Category       *string    `json:"category"`
	PRNumber       *int       `json:"pr_number"`
}

type PatternStat struct {
	ID             int64      `json:"id"`
	InstallationID int64      `json:"installation_id"`
	RepoID         *int64     `json:"repo_id"`
	SupermemoryID  string     `json:"supermemory_id"`
	ContentHash    string     `json:"content_hash"`
	Category       string     `json:"category"`
	TimesMatched   int        `json:"times_matched"`
	TimesConfirmed int        `json:"times_confirmed"`
	TimesDismissed int        `json:"times_dismissed"`
	QualityScore   float64    `json:"quality_score"`
	LastMatchedAt  *time.Time `json:"last_matched_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type PipelineState struct {
	ID        uuid.UUID `json:"id"`
	ReviewID  uuid.UUID `json:"review_id"`
	State     string    `json:"state"`
	Payload   []byte    `json:"payload"`
	Error     *string   `json:"error"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PromptTemplate struct {
	ID         int        `json:"id"`
	RepoID     int64      `json:"repo_id"`
	Stage      string     `json:"stage"`
	PromptText string     `json:"prompt_text"`
	CreatedAt  *time.Time `json:"created_at"`
	UpdatedAt  *time.Time `json:"updated_at"`
}

type ProviderKey struct {
	ID             int64     `json:"id"`
	InstallationID int64     `json:"installation_id"`
	RepoID         *int64    `json:"repo_id"`
	Provider       string    `json:"provider"`
	APIKeyEnc      string    `json:"api_key_enc"`
	BaseURL        *string   `json:"base_url"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	KeyHint        *string   `json:"key_hint"`
}

type Repo struct {
	ID             int64           `json:"id"`
	InstallationID int64           `json:"installation_id"`
	GithubID       int64           `json:"github_id"`
	FullName       string          `json:"full_name"`
	DefaultBranch  string          `json:"default_branch"`
	Enabled        bool            `json:"enabled"`
	SettingsJSON   json.RawMessage `json:"settings_json"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Review struct {
	ID                 uuid.UUID       `json:"id"`
	RepoID             int64           `json:"repo_id"`
	PRNumber           int             `json:"pr_number"`
	PRTitle            string          `json:"pr_title"`
	PRAuthor           string          `json:"pr_author"`
	HeadSHA            string          `json:"head_sha"`
	BaseSHA            string          `json:"base_sha"`
	GithubReviewID     *int64          `json:"github_review_id"`
	Status             string          `json:"status"`
	Summary            *string         `json:"summary"`
	Score              *int            `json:"score"`
	TokenUsage         []byte          `json:"token_usage"`
	Trigger            string          `json:"trigger"`
	TriggeredBy        *string         `json:"triggered_by"`
	DurationMs         *int            `json:"duration_ms"`
	Error              *string         `json:"error"`
	CreatedAt          time.Time       `json:"created_at"`
	CompletedAt        *time.Time      `json:"completed_at"`
	FileCount          *int            `json:"file_count"`
	DeepReview         bool            `json:"deep_review"`
	Persona            *string         `json:"persona"`
	IsIncremental      bool            `json:"is_incremental"`
	ResolvedStaleCount *int            `json:"resolved_stale_count"`
	HeadRef            *string         `json:"head_ref"`
	SimulationResults  []byte          `json:"simulation_results"`
	Diagram            *string         `json:"diagram"`
	DiagramTitle       *string         `json:"diagram_title"`
	Diagrams           []byte          `json:"diagrams"`
	TruncatedFiles     []byte          `json:"truncated_files"`
	Brief              *string         `json:"brief"`
	MemoryEnabled      bool            `json:"memory_enabled"`
	CrossPRHash        *string         `json:"cross_pr_hash"`
	LinkedPRRefs       json.RawMessage `json:"linked_pr_refs"`
	LinkedIssueRefs    json.RawMessage `json:"linked_issue_refs"`
	TraceID            *string         `json:"trace_id"`
}

type ReviewComment struct {
	ID                  uuid.UUID `json:"id"`
	ReviewID            uuid.UUID `json:"review_id"`
	FilePath            string    `json:"file_path"`
	StartLine           *int      `json:"start_line"`
	EndLine             *int      `json:"end_line"`
	Side                *string   `json:"side"`
	Body                string    `json:"body"`
	Severity            *string   `json:"severity"`
	Category            *string   `json:"category"`
	CreatedAt           time.Time `json:"created_at"`
	CodeSnippet         *string   `json:"code_snippet"`
	GithubCommentID     *int64    `json:"github_comment_id"`
	Specialist          *string   `json:"specialist"`
	ConfidenceScore     *int      `json:"confidence_score"`
	MatchedPatternID    *int64    `json:"matched_pattern_id"`
	MatchedPatternScore *float32  `json:"matched_pattern_score"`
	EnforcedRuleContent *string   `json:"enforced_rule_content"`
	IsNewFinding        *bool     `json:"is_new_finding"`
	SuppressedReason    *string   `json:"suppressed_reason"`
}

type Rule struct {
	ID             int64     `json:"id"`
	Category       string    `json:"category"`
	Content        string    `json:"content"`
	Priority       int       `json:"priority"`
	Enabled        bool      `json:"enabled"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	InstallationID *int64    `json:"installation_id"`
}

type Scenario struct {
	ID              int64          `json:"id"`
	InstallationID  int64          `json:"installation_id"`
	RepoID          *int64         `json:"repo_id"`
	Description     string         `json:"description"`
	Source          string         `json:"source"`
	SourceRef       *string        `json:"source_ref"`
	Files           []string       `json:"files"`
	Modules         []string       `json:"modules"`
	Severity        *string        `json:"severity"`
	Active          *bool          `json:"active"`
	CreatedAt       *time.Time     `json:"created_at"`
	Steps           []byte         `json:"steps"`
	InitialState    *string        `json:"initial_state"`
	ExpectedOutcome *string        `json:"expected_outcome"`
	IsOutdated      *bool          `json:"is_outdated"`
	LastRunAt       *time.Time     `json:"last_run_at"`
	TriggerCount    int            `json:"trigger_count"`
	LastVerdict     *string        `json:"last_verdict"`
	LastConfidence  pgtype.Numeric `json:"last_confidence"`
	LastWhy         *string        `json:"last_why"`
	LastFix         *string        `json:"last_fix"`
	LastPrNumber    *int           `json:"last_pr_number"`
	LastReviewID    *uuid.UUID     `json:"last_review_id"`
	SupermemoryID   *string        `json:"supermemory_id"`
}

type ScenarioRun struct {
	ID         int64          `json:"id"`
	ScenarioID int64          `json:"scenario_id"`
	ReviewID   uuid.UUID      `json:"review_id"`
	PRNumber   int            `json:"pr_number"`
	Verdict    string         `json:"verdict"`
	Confidence pgtype.Numeric `json:"confidence"`
	Why        *string        `json:"why"`
	Fix        *string        `json:"fix"`
	RootCause  *string        `json:"root_cause"`
	Impact     *string        `json:"impact"`
	CreatedAt  time.Time      `json:"created_at"`
}

type UserInstallation struct {
	ID             int64     `json:"id"`
	ClerkUserID    string    `json:"clerk_user_id"`
	InstallationID int64     `json:"installation_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
}
