// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patterns.sql

package db

import (
	"context"
	"time"
)

const createPattern = `-- name: CreatePattern :one
INSERT INTO patterns (installation_id, repo_id, content, memory_doc_id, created_by, source, category, pr_number, memory_custom_id)
VALUES ($1, $2, $3, $4, $5, COALESCE($8::text, 'manual'), $6, $7, $9::text)
ON CONFLICT (installation_id, memory_custom_id) WHERE memory_custom_id IS NOT NULL AND source = 'convention' DO UPDATE
SET repo_id = EXCLUDED.repo_id,
    content = EXCLUDED.content,
    memory_doc_id = COALESCE(EXCLUDED.memory_doc_id, patterns.memory_doc_id),
    created_by = COALESCE(EXCLUDED.created_by, patterns.created_by),
    source = EXCLUDED.source,
    category = EXCLUDED.category,
    pr_number = EXCLUDED.pr_number,
    updated_at = now()
RETURNING id, installation_id, repo_id, content, memory_doc_id, created_by, COALESCE(source, 'manual') as source, category, pr_number, created_at, updated_at
`

type CreatePatternParams struct {
	InstallationID int64   `json:"installation_id"`
	RepoID         *int64  `json:"repo_id"`
	Content        string  `json:"content"`
	MemoryDocID    *string `json:"memory_doc_id"`
	CreatedBy      *string `json:"created_by"`
	Category       *string `json:"category"`
	PRNumber       *int    `json:"pr_number"`
	Source         *string `json:"source"`
	MemoryCustomID *string `json:"memory_custom_id"`
}

type CreatePatternRow struct {
	ID             int        `json:"id"`
	InstallationID int64      `json:"installation_id"`
	RepoID         *int64     `json:"repo_id"`
	Content        string     `json:"content"`
	MemoryDocID    *string    `json:"memory_doc_id"`
	CreatedBy      *string    `json:"created_by"`
	Source         string     `json:"source"`
	Category       *string    `json:"category"`
	PRNumber       *int       `json:"pr_number"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
}

func (q *Queries) CreatePattern(ctx context.Context, arg CreatePatternParams) (CreatePatternRow, error) {
	row := q.db.QueryRow(ctx, createPattern,
		arg.InstallationID,
		arg.RepoID,
		arg.Content,
		arg.MemoryDocID,
		arg.CreatedBy,
		arg.Category,
		arg.PRNumber,
		arg.Source,
		arg.MemoryCustomID,
	)
	var i CreatePatternRow
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.RepoID,
		&i.Content,
		&i.MemoryDocID,
		&i.CreatedBy,
		&i.Source,
		&i.Category,
		&i.PRNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePattern = `-- name: DeletePattern :one
DELETE FROM patterns
WHERE id = $1::bigint AND installation_id = ANY($2::bigint[])
RETURNING installation_id, memory_custom_id, memory_doc_id,
          repo_id, content, COALESCE(source, 'manual')::text AS source, category, pr_number
`

type DeletePatternParams struct {
	ID              int64   `json:"id"`
	InstallationIds []int64 `json:"installation_ids"`
}

type DeletePatternRow struct {
	InstallationID int64   `json:"installation_id"`
	MemoryCustomID *string `json:"memory_custom_id"`
	MemoryDocID    *string `json:"memory_doc_id"`
	RepoID         *int64  `json:"repo_id"`
	Content        string  `json:"content"`
	Source         string  `json:"source"`
	Category       *string `json:"category"`
	PRNumber       *int    `json:"pr_number"`
}

func (q *Queries) DeletePattern(ctx context.Context, arg DeletePatternParams) (DeletePatternRow, error) {
	row := q.db.QueryRow(ctx, deletePattern, arg.ID, arg.InstallationIds)
	var i DeletePatternRow
	err := row.Scan(
		&i.InstallationID,
		&i.MemoryCustomID,
		&i.MemoryDocID,
		&i.RepoID,
		&i.Content,
		&i.Source,
		&i.Category,
		&i.PRNumber,
	)
	return i, err
}

const getLowQualityPatterns = `-- name: GetLowQualityPatterns :many
SELECT id, installation_id, repo_id, memory_doc_id, content_hash, category,
       times_matched, times_confirmed, times_dismissed, quality_score,
       last_matched_at, created_at, updated_at
FROM pattern_stats
WHERE installation_id = $1 AND quality_score <= $2
ORDER BY quality_score ASC
LIMIT $3::bigint
`

type GetLowQualityPatternsParams struct {
	InstallationID int64   `json:"installation_id"`
	QualityScore   float64 `json:"quality_score"`
	RowLimit       int64   `json:"row_limit"`
}

func (q *Queries) GetLowQualityPatterns(ctx context.Context, arg GetLowQualityPatternsParams) ([]PatternStat, error) {
	rows, err := q.db.Query(ctx, getLowQualityPatterns, arg.InstallationID, arg.QualityScore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatternStat
	for rows.Next() {
		var i PatternStat
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.RepoID,
			&i.MemoryDocID,
			&i.ContentHash,
			&i.Category,
			&i.TimesMatched,
			&i.TimesConfirmed,
			&i.TimesDismissed,
			&i.QualityScore,
			&i.LastMatchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPattern = `-- name: GetPattern :one
SELECT id, installation_id, repo_id, content, memory_doc_id, created_by, COALESCE(source, 'manual') as source, category, pr_number, created_at, updated_at
FROM patterns WHERE id = $1::bigint
`

type GetPatternRow struct {
	ID             int        `json:"id"`
	InstallationID int64      `json:"installation_id"`
	RepoID         *int64     `json:"repo_id"`
	Content        string     `json:"content"`
	MemoryDocID    *string    `json:"memory_doc_id"`
	CreatedBy      *string    `json:"created_by"`
	Source         string     `json:"source"`
	Category       *string    `json:"category"`
	PRNumber       *int       `json:"pr_number"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
}

func (q *Queries) GetPattern(ctx context.Context, id int64) (GetPatternRow, error) {
	row := q.db.QueryRow(ctx, getPattern, id)
	var i GetPatternRow
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.RepoID,
		&i.Content,
		&i.MemoryDocID,
		&i.CreatedBy,
		&i.Source,
		&i.Category,
		&i.PRNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatternStats = `-- name: GetPatternStats :many
SELECT DATE_TRUNC('week', created_at)::timestamptz AS week, COALESCE(source, 'manual') as source, COUNT(*)::int as count
FROM patterns WHERE installation_id = ANY($1::bigint[])
GROUP BY week, source ORDER BY week
`

type GetPatternStatsRow struct {
	Week   time.Time `json:"week"`
	Source string    `json:"source"`
	Count  int       `json:"count"`
}

func (q *Queries) GetPatternStats(ctx context.Context, dollar_1 []int64) ([]GetPatternStatsRow, error) {
	rows, err := q.db.Query(ctx, getPatternStats, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPatternStatsRow
	for rows.Next() {
		var i GetPatternStatsRow
		if err := rows.Scan(&i.Week, &i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatterns = `-- name: ListPatterns :many
SELECT p.id, p.installation_id, p.repo_id, p.content, p.memory_doc_id, p.created_by, COALESCE(p.source, 'manual') as source, p.category, p.pr_number, p.created_at, p.updated_at,
CASE WHEN m.id IS NULL THEN 'unmirrored' WHEN m.deleted_at IS NOT NULL THEN 'deleted' WHEN m.invalidated_at IS NOT NULL OR m.superseded_by IS NOT NULL THEN 'superseded' WHEN EXISTS (SELECT 1 FROM convention_conflicts c WHERE c.state='open' AND (c.memory_low_id=m.id OR c.memory_high_id=m.id)) THEN 'disputed' ELSE 'active' END::text AS status,
COALESCE((SELECT count(*) FROM convention_evidence e WHERE e.convention_memory_id=m.id), 1)::int AS evidence_count
FROM patterns p LEFT JOIN memories m ON m.installation_id=p.installation_id AND m.custom_id=p.memory_custom_id WHERE p.installation_id = ANY($1::bigint[]) ORDER BY p.created_at DESC
`

type ListPatternsRow struct {
	ID             int        `json:"id"`
	InstallationID int64      `json:"installation_id"`
	RepoID         *int64     `json:"repo_id"`
	Content        string     `json:"content"`
	MemoryDocID    *string    `json:"memory_doc_id"`
	CreatedBy      *string    `json:"created_by"`
	Source         string     `json:"source"`
	Category       *string    `json:"category"`
	PRNumber       *int       `json:"pr_number"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
	Status         string     `json:"status"`
	EvidenceCount  int        `json:"evidence_count"`
}

func (q *Queries) ListPatterns(ctx context.Context, dollar_1 []int64) ([]ListPatternsRow, error) {
	rows, err := q.db.Query(ctx, listPatterns, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatternsRow
	for rows.Next() {
		var i ListPatternsRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.RepoID,
			&i.Content,
			&i.MemoryDocID,
			&i.CreatedBy,
			&i.Source,
			&i.Category,
			&i.PRNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.EvidenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatternsForRepo = `-- name: ListPatternsForRepo :many
SELECT p.id, p.installation_id, p.repo_id, p.content, p.memory_doc_id, p.created_by, COALESCE(p.source, 'manual') as source, p.category, p.pr_number, p.created_at, p.updated_at,
CASE WHEN m.id IS NULL THEN 'unmirrored' WHEN m.deleted_at IS NOT NULL THEN 'deleted' WHEN m.invalidated_at IS NOT NULL OR m.superseded_by IS NOT NULL THEN 'superseded' WHEN EXISTS (SELECT 1 FROM convention_conflicts c WHERE c.state='open' AND (c.memory_low_id=m.id OR c.memory_high_id=m.id)) THEN 'disputed' ELSE 'active' END::text AS status,
COALESCE((SELECT count(*) FROM convention_evidence e WHERE e.convention_memory_id=m.id), 1)::int AS evidence_count
FROM patterns p LEFT JOIN memories m ON m.installation_id=p.installation_id AND m.custom_id=p.memory_custom_id WHERE p.installation_id = ANY($1::bigint[]) AND (p.repo_id IS NULL OR p.repo_id = $2) ORDER BY p.created_at DESC
`

type ListPatternsForRepoParams struct {
	Column1 []int64 `json:"column_1"`
	RepoID  *int64  `json:"repo_id"`
}

type ListPatternsForRepoRow struct {
	ID             int        `json:"id"`
	InstallationID int64      `json:"installation_id"`
	RepoID         *int64     `json:"repo_id"`
	Content        string     `json:"content"`
	MemoryDocID    *string    `json:"memory_doc_id"`
	CreatedBy      *string    `json:"created_by"`
	Source         string     `json:"source"`
	Category       *string    `json:"category"`
	PRNumber       *int       `json:"pr_number"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
	Status         string     `json:"status"`
	EvidenceCount  int        `json:"evidence_count"`
}

func (q *Queries) ListPatternsForRepo(ctx context.Context, arg ListPatternsForRepoParams) ([]ListPatternsForRepoRow, error) {
	rows, err := q.db.Query(ctx, listPatternsForRepo, arg.Column1, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatternsForRepoRow
	for rows.Next() {
		var i ListPatternsForRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.RepoID,
			&i.Content,
			&i.MemoryDocID,
			&i.CreatedBy,
			&i.Source,
			&i.Category,
			&i.PRNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.EvidenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
