// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getAllFileReviewsForReview = `-- name: GetAllFileReviewsForReview :one
SELECT (payload->'AllFileReviews')::jsonb AS all_file_reviews
FROM pipeline_states
WHERE review_id = $1
ORDER BY updated_at DESC
LIMIT 1
`

// Returns the unfiltered comments (before dedup/scoring) from the latest pipeline run for a review.
// Used by the export endpoint to surface dropped findings.
// Explicit ::jsonb cast is needed so sqlc infers a concrete type and applies
// the RawMessage override from sqlc.yaml (otherwise it defaults to interface{}
// which pgx decodes via json.Unmarshal, breaking the []byte assertion in export).
func (q *Queries) GetAllFileReviewsForReview(ctx context.Context, reviewID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getAllFileReviewsForReview, reviewID)
	var all_file_reviews json.RawMessage
	err := row.Scan(&all_file_reviews)
	return all_file_reviews, err
}

const getLatestRunForReview = `-- name: GetLatestRunForReview :one
SELECT id FROM pipeline_states WHERE review_id = $1 ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) GetLatestRunForReview(ctx context.Context, reviewID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestRunForReview, reviewID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listIncompleteRuns = `-- name: ListIncompleteRuns :many
SELECT id FROM pipeline_states WHERE state NOT IN ($1, $2) ORDER BY updated_at
`

type ListIncompleteRunsParams struct {
	State   string `json:"state"`
	State_2 string `json:"state_2"`
}

func (q *Queries) ListIncompleteRuns(ctx context.Context, arg ListIncompleteRunsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listIncompleteRuns, arg.State, arg.State_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadPipelineState = `-- name: LoadPipelineState :one
SELECT payload FROM pipeline_states WHERE id = $1
`

func (q *Queries) LoadPipelineState(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadPipelineState, id)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const upsertPipelineState = `-- name: UpsertPipelineState :exec
INSERT INTO pipeline_states (id, review_id, state, payload, error, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (id) DO UPDATE SET
    state = EXCLUDED.state,
    payload = EXCLUDED.payload,
    error = EXCLUDED.error,
    updated_at = NOW()
`

type UpsertPipelineStateParams struct {
	ID       uuid.UUID `json:"id"`
	ReviewID uuid.UUID `json:"review_id"`
	State    string    `json:"state"`
	Payload  []byte    `json:"payload"`
	Error    *string   `json:"error"`
}

func (q *Queries) UpsertPipelineState(ctx context.Context, arg UpsertPipelineStateParams) error {
	_, err := q.db.Exec(ctx, upsertPipelineState,
		arg.ID,
		arg.ReviewID,
		arg.State,
		arg.Payload,
		arg.Error,
	)
	return err
}
