// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countReviewsThisMonth = `-- name: CountReviewsThisMonth :one
SELECT COUNT(*)::int FROM reviews r
JOIN repos rp ON r.repo_id = rp.id
WHERE rp.installation_id = $1
AND r.created_at >= date_trunc('month', NOW())
`

func (q *Queries) CountReviewsThisMonth(ctx context.Context, installationID int64) (int, error) {
	row := q.db.QueryRow(ctx, countReviewsThisMonth, installationID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const findReviewsLinkingToPR = `-- name: FindReviewsLinkingToPR :many
SELECT rv.id, rv.repo_id, rv.pr_number, rv.head_sha
FROM reviews rv
WHERE rv.status = 'completed'
  AND rv.id <> $1::uuid
  AND rv.linked_pr_refs @> jsonb_build_array(jsonb_build_object(
      'owner',  $2::text,
      'repo',   $3::text,
      'number', $4::int
  ))
`

type FindReviewsLinkingToPRParams struct {
	ExcludeID uuid.UUID `json:"exclude_id"`
	Owner     string    `json:"owner"`
	Repo      string    `json:"repo"`
	Number    int       `json:"number"`
}

type FindReviewsLinkingToPRRow struct {
	ID       uuid.UUID `json:"id"`
	RepoID   int64     `json:"repo_id"`
	PRNumber int       `json:"pr_number"`
	HeadSHA  string    `json:"head_sha"`
}

// Returns completed reviews whose linked_pr_refs JSONB contains the given
// (owner, repo, number). Used by OnReviewCompleted to enqueue sibling
// refreshes when a PR whose review was linked-to finishes a new review.
// Excludes the caller's own review_id.
//
// Index: reviews_linked_pr_refs_gin (jsonb_path_ops) — containment (@>) is
// the GIN-supported operator; any relaxation (e.g. ? or ?&) loses the index.
func (q *Queries) FindReviewsLinkingToPR(ctx context.Context, arg FindReviewsLinkingToPRParams) ([]FindReviewsLinkingToPRRow, error) {
	rows, err := q.db.Query(ctx, findReviewsLinkingToPR,
		arg.ExcludeID,
		arg.Owner,
		arg.Repo,
		arg.Number,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindReviewsLinkingToPRRow
	for rows.Next() {
		var i FindReviewsLinkingToPRRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.PRNumber,
			&i.HeadSHA,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSharedLinkedIssues = `-- name: FindSharedLinkedIssues :many
SELECT
    (t.issue->>'owner')::text  AS owner,
    (t.issue->>'repo')::text   AS repo,
    (t.issue->>'number')::int  AS number,
    array_agg(DISTINCT r.id)::uuid[] AS review_ids
FROM reviews target
CROSS JOIN LATERAL jsonb_array_elements(target.linked_issue_refs) AS t(issue)
JOIN reviews r
    ON r.status = 'completed'
   AND r.linked_issue_refs @> jsonb_build_array(t.issue)
WHERE target.id = $1::uuid
GROUP BY 1, 2, 3
HAVING count(DISTINCT r.id) >= 2
`

type FindSharedLinkedIssuesRow struct {
	Owner     string      `json:"owner"`
	Repo      string      `json:"repo"`
	Number    int         `json:"number"`
	ReviewIds []uuid.UUID `json:"review_ids"`
}

// Given a review id, returns the set of (owner, repo, number) issues that
// appear in THIS review's linked_issue_refs AND are also referenced by at
// least one other completed review (so count(DISTINCT review_ids) >= 2).
// Each row carries the aggregated list of review ids pointing at that
// issue so the joint-acceptance stage can hydrate their findings.
//
// Correctness notes:
//   - Joining on `r.linked_issue_refs @> jsonb_build_array(t.issue)` uses
//     the GIN(jsonb_path_ops) index from migration 040. Relaxing the
//     operator (e.g. ? / ?&) would lose the index scan.
//   - The target review is allowed to self-match — it counts toward the
//     >=2 threshold precisely because joint acceptance IS about "this PR
//     plus its siblings" (a lone review can't share an issue with itself
//     distinct-id-wise, so the filter still excludes singletons naturally).
//   - status = 'completed' filter is applied to siblings only; the target
//     row's status is not re-verified because the caller is always the
//     just-completed review and race-wise it's safe: a later status flip
//     won't surface stale joint output (the stage re-runs on next event).
func (q *Queries) FindSharedLinkedIssues(ctx context.Context, reviewID uuid.UUID) ([]FindSharedLinkedIssuesRow, error) {
	rows, err := q.db.Query(ctx, findSharedLinkedIssues, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSharedLinkedIssuesRow
	for rows.Next() {
		var i FindSharedLinkedIssuesRow
		if err := rows.Scan(
			&i.Owner,
			&i.Repo,
			&i.Number,
			&i.ReviewIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastCompletedReview = `-- name: GetLastCompletedReview :one
SELECT id, repo_id, pr_number, pr_title, pr_author, head_sha, base_sha, COALESCE(head_ref,'') as head_ref, github_review_id,
       status, summary, score, token_usage, trigger, triggered_by, duration_ms, error,
       deep_review, persona, is_incremental, created_at, completed_at, trace_id
FROM reviews WHERE repo_id = $1 AND pr_number = $2 AND status = 'completed'
ORDER BY completed_at DESC LIMIT 1
`

type GetLastCompletedReviewParams struct {
	RepoID   int64 `json:"repo_id"`
	PRNumber int   `json:"pr_number"`
}

type GetLastCompletedReviewRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
	TraceID        *string    `json:"trace_id"`
}

func (q *Queries) GetLastCompletedReview(ctx context.Context, arg GetLastCompletedReviewParams) (GetLastCompletedReviewRow, error) {
	row := q.db.QueryRow(ctx, getLastCompletedReview, arg.RepoID, arg.PRNumber)
	var i GetLastCompletedReviewRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.PRTitle,
		&i.PRAuthor,
		&i.HeadSHA,
		&i.BaseSHA,
		&i.HeadRef,
		&i.GithubReviewID,
		&i.Status,
		&i.Summary,
		&i.Score,
		&i.TokenUsage,
		&i.Trigger,
		&i.TriggeredBy,
		&i.DurationMs,
		&i.Error,
		&i.DeepReview,
		&i.Persona,
		&i.IsIncremental,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.TraceID,
	)
	return i, err
}

const getLatestCompletedReviewByPR = `-- name: GetLatestCompletedReviewByPR :one
SELECT
    rv.id,
    rv.repo_id,
    rv.pr_number,
    rv.head_sha,
    rv.completed_at,
    COALESCE(ps.payload->'AllFileReviews', '[]'::jsonb)::jsonb AS all_file_reviews,
    COALESCE(
        (
            SELECT array_agg(DISTINCT key)
            FROM auto_resolve_events are2,
                 UNNEST(are2.resolved_thread_keys) AS key
            WHERE are2.repo_id = rv.repo_id
              AND are2.pr_number = rv.pr_number
              AND are2.created_at > rv.completed_at
              AND key <> ''
        ),
        '{}'
    )::text[] AS auto_resolved_thread_keys
FROM reviews rv
LEFT JOIN LATERAL (
    SELECT payload
    FROM pipeline_states
    WHERE review_id = rv.id
    ORDER BY updated_at DESC
    LIMIT 1
) ps ON TRUE
WHERE rv.repo_id = $1
  AND rv.pr_number = $2
  AND rv.status = 'completed'
ORDER BY rv.completed_at DESC
LIMIT 1
`

type GetLatestCompletedReviewByPRParams struct {
	RepoID   int64 `json:"repo_id"`
	PRNumber int   `json:"pr_number"`
}

type GetLatestCompletedReviewByPRRow struct {
	ID                     uuid.UUID       `json:"id"`
	RepoID                 int64           `json:"repo_id"`
	PRNumber               int             `json:"pr_number"`
	HeadSHA                string          `json:"head_sha"`
	CompletedAt            *time.Time      `json:"completed_at"`
	AllFileReviews         json.RawMessage `json:"all_file_reviews"`
	AutoResolvedThreadKeys []string        `json:"auto_resolved_thread_keys"`
}

// Returns the most recent completed review for a given (repo_id, pr_number)
// along with its findings payload (AllFileReviews from the latest pipeline
// state) and the flat set of per-thread auto-resolve keys fired AFTER the
// review completed. Used by the async cross-PR stage to hydrate linked-PR
// state in one round trip.
//
// Findings storage note: findings currently live inside
// pipeline_states.payload->'AllFileReviews' (see GetAllFileReviewsForReview
// for the existing pattern). If reviews ever gains a findings_json column,
// this LEFT JOIN on pipeline_states can collapse.
//
// Auto-resolve filtering: migration 041 added resolved_thread_keys TEXT[]
// to auto_resolve_events — each element is a "<path>:<line>" key matching
// the shape that Finding.Path + Finding.Line produces on the Go side.
// We flatten the post-review events' arrays via UNNEST + array_agg so the
// consumer receives a single deduped set ready for O(1) membership tests
// in filterAutoResolvedFindings. Pre-migration rows contribute an empty
// array (zero join keys, no filtering happens for them — documented no-op).
//
// Returns pgx.ErrNoRows when the PR was never reviewed — callers must
// treat the absence as graceful (Reviewed=false), not as an error.
func (q *Queries) GetLatestCompletedReviewByPR(ctx context.Context, arg GetLatestCompletedReviewByPRParams) (GetLatestCompletedReviewByPRRow, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedReviewByPR, arg.RepoID, arg.PRNumber)
	var i GetLatestCompletedReviewByPRRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.HeadSHA,
		&i.CompletedAt,
		&i.AllFileReviews,
		&i.AutoResolvedThreadKeys,
	)
	return i, err
}

const getLatestReviewByPR = `-- name: GetLatestReviewByPR :one
SELECT rv.id, rv.repo_id, rv.pr_number, rv.pr_title, rv.pr_author, rv.head_sha, rv.base_sha, COALESCE(rv.head_ref,'') as head_ref, rv.github_review_id,
       rv.status, rv.summary, rv.score, rv.token_usage, rv.trigger, rv.triggered_by, rv.duration_ms, rv.error,
       rv.deep_review, rv.persona, rv.is_incremental, rv.created_at, rv.completed_at, rv.trace_id
FROM reviews rv JOIN repos r ON rv.repo_id = r.id
WHERE r.full_name = $1 AND rv.pr_number = $2
  AND rv.status = 'completed'
ORDER BY rv.created_at DESC LIMIT 1
`

type GetLatestReviewByPRParams struct {
	FullName string `json:"full_name"`
	PRNumber int    `json:"pr_number"`
}

type GetLatestReviewByPRRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
	TraceID        *string    `json:"trace_id"`
}

func (q *Queries) GetLatestReviewByPR(ctx context.Context, arg GetLatestReviewByPRParams) (GetLatestReviewByPRRow, error) {
	row := q.db.QueryRow(ctx, getLatestReviewByPR, arg.FullName, arg.PRNumber)
	var i GetLatestReviewByPRRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.PRTitle,
		&i.PRAuthor,
		&i.HeadSHA,
		&i.BaseSHA,
		&i.HeadRef,
		&i.GithubReviewID,
		&i.Status,
		&i.Summary,
		&i.Score,
		&i.TokenUsage,
		&i.Trigger,
		&i.TriggeredBy,
		&i.DurationMs,
		&i.Error,
		&i.DeepReview,
		&i.Persona,
		&i.IsIncremental,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.TraceID,
	)
	return i, err
}

const getLatestReviewBySHA = `-- name: GetLatestReviewBySHA :one
SELECT rv.id, rv.repo_id, rv.pr_number, rv.pr_title, rv.pr_author, rv.head_sha, rv.base_sha, COALESCE(rv.head_ref,'') as head_ref, rv.github_review_id,
       rv.status, rv.summary, rv.score, rv.token_usage, rv.trigger, rv.triggered_by, rv.duration_ms, rv.error,
       rv.deep_review, rv.persona, rv.is_incremental, rv.created_at, rv.completed_at, rv.trace_id
FROM reviews rv JOIN repos r ON rv.repo_id = r.id
WHERE r.full_name = $1 AND rv.pr_number = $2 AND rv.head_sha = $3
  AND rv.status = 'completed'
ORDER BY rv.created_at DESC LIMIT 1
`

type GetLatestReviewBySHAParams struct {
	FullName string `json:"full_name"`
	PRNumber int    `json:"pr_number"`
	HeadSHA  string `json:"head_sha"`
}

type GetLatestReviewBySHARow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
	TraceID        *string    `json:"trace_id"`
}

func (q *Queries) GetLatestReviewBySHA(ctx context.Context, arg GetLatestReviewBySHAParams) (GetLatestReviewBySHARow, error) {
	row := q.db.QueryRow(ctx, getLatestReviewBySHA, arg.FullName, arg.PRNumber, arg.HeadSHA)
	var i GetLatestReviewBySHARow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.PRTitle,
		&i.PRAuthor,
		&i.HeadSHA,
		&i.BaseSHA,
		&i.HeadRef,
		&i.GithubReviewID,
		&i.Status,
		&i.Summary,
		&i.Score,
		&i.TokenUsage,
		&i.Trigger,
		&i.TriggeredBy,
		&i.DurationMs,
		&i.Error,
		&i.DeepReview,
		&i.Persona,
		&i.IsIncremental,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.TraceID,
	)
	return i, err
}

const getRepoReviewStats = `-- name: GetRepoReviewStats :one
WITH recent AS (
  SELECT token_usage FROM reviews
  WHERE repo_id = $1 AND status = 'completed' AND token_usage IS NOT NULL
  ORDER BY created_at DESC
  LIMIT $2
)
SELECT
  COUNT(*)::int AS sample_size,
  COALESCE(AVG((token_usage->'total'->>'total_tokens')::bigint), 0)::bigint AS avg_tokens,
  COALESCE(AVG(NULLIF((token_usage->'total'->>'cost')::float8, 0)), 0)::float8 AS avg_cost,
  COALESCE(BOOL_OR((token_usage->'total'->>'cost') IS NOT NULL AND (token_usage->'total'->>'cost')::float8 > 0), false) AS cost_available
FROM recent
`

type GetRepoReviewStatsParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int32 `json:"limit"`
}

type GetRepoReviewStatsRow struct {
	SampleSize    int         `json:"sample_size"`
	AvgTokens     int64       `json:"avg_tokens"`
	AvgCost       float64     `json:"avg_cost"`
	CostAvailable interface{} `json:"cost_available"`
}

// Returns averaged token + cost stats over the last N completed reviews for a repo,
// used to estimate cost for the "Trigger review" checkbox comment. `cost_available`
// is true only when at least one review in the sample has token_usage.total.cost.
func (q *Queries) GetRepoReviewStats(ctx context.Context, arg GetRepoReviewStatsParams) (GetRepoReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getRepoReviewStats, arg.RepoID, arg.Limit)
	var i GetRepoReviewStatsRow
	err := row.Scan(
		&i.SampleSize,
		&i.AvgTokens,
		&i.AvgCost,
		&i.CostAvailable,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT id, repo_id, pr_number, pr_title, pr_author, head_sha, base_sha, COALESCE(head_ref,'') as head_ref, github_review_id,
       status, summary, score, token_usage, trigger, triggered_by, duration_ms, error,
       deep_review, persona, is_incremental, created_at, completed_at, simulation_results, diagram, diagram_title, trace_id
FROM reviews WHERE id = $1
`

type GetReviewRow struct {
	ID                uuid.UUID  `json:"id"`
	RepoID            int64      `json:"repo_id"`
	PRNumber          int        `json:"pr_number"`
	PRTitle           string     `json:"pr_title"`
	PRAuthor          string     `json:"pr_author"`
	HeadSHA           string     `json:"head_sha"`
	BaseSHA           string     `json:"base_sha"`
	HeadRef           string     `json:"head_ref"`
	GithubReviewID    *int64     `json:"github_review_id"`
	Status            string     `json:"status"`
	Summary           *string    `json:"summary"`
	Score             *int       `json:"score"`
	TokenUsage        []byte     `json:"token_usage"`
	Trigger           string     `json:"trigger"`
	TriggeredBy       *string    `json:"triggered_by"`
	DurationMs        *int       `json:"duration_ms"`
	Error             *string    `json:"error"`
	DeepReview        bool       `json:"deep_review"`
	Persona           *string    `json:"persona"`
	IsIncremental     bool       `json:"is_incremental"`
	CreatedAt         time.Time  `json:"created_at"`
	CompletedAt       *time.Time `json:"completed_at"`
	SimulationResults []byte     `json:"simulation_results"`
	Diagram           *string    `json:"diagram"`
	DiagramTitle      *string    `json:"diagram_title"`
	TraceID           *string    `json:"trace_id"`
}

func (q *Queries) GetReview(ctx context.Context, id uuid.UUID) (GetReviewRow, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i GetReviewRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.PRTitle,
		&i.PRAuthor,
		&i.HeadSHA,
		&i.BaseSHA,
		&i.HeadRef,
		&i.GithubReviewID,
		&i.Status,
		&i.Summary,
		&i.Score,
		&i.TokenUsage,
		&i.Trigger,
		&i.TriggeredBy,
		&i.DurationMs,
		&i.Error,
		&i.DeepReview,
		&i.Persona,
		&i.IsIncremental,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.SimulationResults,
		&i.Diagram,
		&i.DiagramTitle,
		&i.TraceID,
	)
	return i, err
}

const listAllReviewsScoped = `-- name: ListAllReviewsScoped :many
SELECT rv.id, rv.repo_id, rv.pr_number, rv.pr_title, rv.pr_author, rv.head_sha, rv.base_sha, COALESCE(rv.head_ref,'') as head_ref, rv.github_review_id,
       rv.status, rv.summary, rv.score, rv.token_usage, rv.trigger, rv.triggered_by, rv.duration_ms, rv.error,
       rv.deep_review, rv.persona, rv.is_incremental, rv.created_at, rv.completed_at, rv.trace_id
FROM reviews rv
JOIN repos r ON rv.repo_id = r.id
WHERE r.installation_id = ANY($1::bigint[])
ORDER BY rv.created_at DESC LIMIT $2 OFFSET $3
`

type ListAllReviewsScopedParams struct {
	Column1 []int64 `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type ListAllReviewsScopedRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
	TraceID        *string    `json:"trace_id"`
}

func (q *Queries) ListAllReviewsScoped(ctx context.Context, arg ListAllReviewsScopedParams) ([]ListAllReviewsScopedRow, error) {
	rows, err := q.db.Query(ctx, listAllReviewsScoped, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReviewsScopedRow
	for rows.Next() {
		var i ListAllReviewsScopedRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.PRNumber,
			&i.PRTitle,
			&i.PRAuthor,
			&i.HeadSHA,
			&i.BaseSHA,
			&i.HeadRef,
			&i.GithubReviewID,
			&i.Status,
			&i.Summary,
			&i.Score,
			&i.TokenUsage,
			&i.Trigger,
			&i.TriggeredBy,
			&i.DurationMs,
			&i.Error,
			&i.DeepReview,
			&i.Persona,
			&i.IsIncremental,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT id, repo_id, pr_number, pr_title, pr_author, head_sha, base_sha, COALESCE(head_ref,'') as head_ref, github_review_id,
       status, summary, score, token_usage, trigger, triggered_by, duration_ms, error,
       deep_review, persona, is_incremental, created_at, completed_at, trace_id
FROM reviews WHERE repo_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReviewsParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListReviewsRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
	TraceID        *string    `json:"trace_id"`
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.PRNumber,
			&i.PRTitle,
			&i.PRAuthor,
			&i.HeadSHA,
			&i.BaseSHA,
			&i.HeadRef,
			&i.GithubReviewID,
			&i.Status,
			&i.Summary,
			&i.Score,
			&i.TokenUsage,
			&i.Trigger,
			&i.TriggeredBy,
			&i.DurationMs,
			&i.Error,
			&i.DeepReview,
			&i.Persona,
			&i.IsIncremental,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsScoped = `-- name: ListReviewsScoped :many
SELECT rv.id, rv.repo_id, rv.pr_number, rv.pr_title, rv.pr_author, rv.head_sha, rv.base_sha, COALESCE(rv.head_ref,'') as head_ref, rv.github_review_id,
       rv.status, rv.summary, rv.score, rv.token_usage, rv.trigger, rv.triggered_by, rv.duration_ms, rv.error,
       rv.deep_review, rv.persona, rv.is_incremental, rv.created_at, rv.completed_at, rv.trace_id
FROM reviews rv
JOIN repos r ON rv.repo_id = r.id
WHERE rv.repo_id = $1 AND r.installation_id = ANY($2::bigint[])
ORDER BY rv.created_at DESC LIMIT $3 OFFSET $4
`

type ListReviewsScopedParams struct {
	RepoID  int64   `json:"repo_id"`
	Column2 []int64 `json:"column_2"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type ListReviewsScopedRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
	TraceID        *string    `json:"trace_id"`
}

func (q *Queries) ListReviewsScoped(ctx context.Context, arg ListReviewsScopedParams) ([]ListReviewsScopedRow, error) {
	rows, err := q.db.Query(ctx, listReviewsScoped,
		arg.RepoID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsScopedRow
	for rows.Next() {
		var i ListReviewsScopedRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.PRNumber,
			&i.PRTitle,
			&i.PRAuthor,
			&i.HeadSHA,
			&i.BaseSHA,
			&i.HeadRef,
			&i.GithubReviewID,
			&i.Status,
			&i.Summary,
			&i.Score,
			&i.TokenUsage,
			&i.Trigger,
			&i.TriggeredBy,
			&i.DurationMs,
			&i.Error,
			&i.DeepReview,
			&i.Persona,
			&i.IsIncremental,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeStageTokenEntry = `-- name: MergeStageTokenEntry :execrows
UPDATE reviews
SET token_usage = jsonb_set(
    jsonb_set(
        COALESCE(token_usage, '{}'::jsonb),
        ARRAY[$1::text],
        jsonb_build_object(
            'prompt_tokens',
                COALESCE((token_usage -> $1::text ->> 'prompt_tokens')::bigint, 0)
                + COALESCE(($2::jsonb ->> 'prompt_tokens')::bigint, 0),
            'completion_tokens',
                COALESCE((token_usage -> $1::text ->> 'completion_tokens')::bigint, 0)
                + COALESCE(($2::jsonb ->> 'completion_tokens')::bigint, 0),
            'total_tokens',
                COALESCE((token_usage -> $1::text ->> 'total_tokens')::bigint, 0)
                + COALESCE(($2::jsonb ->> 'total_tokens')::bigint, 0),
            'cost',
                COALESCE((token_usage -> $1::text ->> 'cost')::float8, 0)
                + COALESCE(($2::jsonb ->> 'cost')::float8, 0),
            'model',
                COALESCE(
                    NULLIF(token_usage -> $1::text ->> 'model', ''),
                    NULLIF($2::jsonb ->> 'model', ''),
                    ''
                ),
            'provider',
                COALESCE(
                    NULLIF(token_usage -> $1::text ->> 'provider', ''),
                    NULLIF($2::jsonb ->> 'provider', ''),
                    ''
                )
        ),
        true
    ),
    '{total}',
    jsonb_build_object(
        'prompt_tokens',
            COALESCE((token_usage -> 'total' ->> 'prompt_tokens')::bigint, 0)
            + COALESCE(($2::jsonb ->> 'prompt_tokens')::bigint, 0),
        'completion_tokens',
            COALESCE((token_usage -> 'total' ->> 'completion_tokens')::bigint, 0)
            + COALESCE(($2::jsonb ->> 'completion_tokens')::bigint, 0),
        'total_tokens',
            COALESCE((token_usage -> 'total' ->> 'total_tokens')::bigint, 0)
            + COALESCE(($2::jsonb ->> 'total_tokens')::bigint, 0),
        'cost',
            COALESCE((token_usage -> 'total' ->> 'cost')::float8, 0)
            + COALESCE(($2::jsonb ->> 'cost')::float8, 0)
    ),
    true
)
WHERE id = $3::uuid
`

type MergeStageTokenEntryParams struct {
	StageKey string          `json:"stage_key"`
	Entry    json.RawMessage `json:"entry"`
	ReviewID uuid.UUID       `json:"review_id"`
}

// Merges a StageTokens JSON object into reviews.token_usage under the
// named scalar bucket (e.g. 'cross_pr', 'acceptance') AND increments
// the 'total' aggregate in a single atomic UPDATE. Used by async
// stages whose LLM calls fire AFTER the synthesis-time token_usage
// commit — the inline orchestrator path doesn't apply to them.
//
// Parameters:
//
//	$1 review_id
//	$2 stage_key  — 'cross_pr' | 'acceptance' (or any scalar bucket)
//	$3 entry_json — a single StageTokens JSON object
//
// Merge semantics (matches RunTokenUsage.addCrossPR / addAcceptance):
//
//	prompt_tokens/completion_tokens/total_tokens/cost  → summed
//	model/provider                                     → stamped only
//	                                                     if currently
//	                                                     missing
//
// Invariants:
//   - If token_usage is NULL it's initialized to '{}'.
//   - If the bucket is missing it's initialized from zero.
//   - If the bucket currently holds a non-object (legacy array / drift)
//     the '->' projection returns NULL and COALESCE treats it as zero —
//     i.e. we rebuild a fresh scalar object rather than error out.
func (q *Queries) MergeStageTokenEntry(ctx context.Context, arg MergeStageTokenEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeStageTokenEntry, arg.StageKey, arg.Entry, arg.ReviewID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReviewLinkedIssueRefs = `-- name: SetReviewLinkedIssueRefs :exec
UPDATE reviews SET linked_issue_refs = $2 WHERE id = $1
`

type SetReviewLinkedIssueRefsParams struct {
	ID              uuid.UUID       `json:"id"`
	LinkedIssueRefs json.RawMessage `json:"linked_issue_refs"`
}

// Writes the JSONB array of linked-issue refs for a review. Same call-site
// contract as SetReviewLinkedPRRefs: synthesis path, BEFORE
// EventReviewCompleted publish, so the joint-acceptance stage sees this
// review's refs the instant a sibling fires.
func (q *Queries) SetReviewLinkedIssueRefs(ctx context.Context, arg SetReviewLinkedIssueRefsParams) error {
	_, err := q.db.Exec(ctx, setReviewLinkedIssueRefs, arg.ID, arg.LinkedIssueRefs)
	return err
}

const setReviewLinkedPRRefs = `-- name: SetReviewLinkedPRRefs :exec
UPDATE reviews SET linked_pr_refs = $2 WHERE id = $1
`

type SetReviewLinkedPRRefsParams struct {
	ID           uuid.UUID       `json:"id"`
	LinkedPRRefs json.RawMessage `json:"linked_pr_refs"`
}

// Writes the JSONB array of linked-PR refs for a review, typically called
// from the synthesis path BEFORE EventReviewCompleted publish so sibling
// lookups (FindReviewsLinkingToPR) see up-to-date data.
func (q *Queries) SetReviewLinkedPRRefs(ctx context.Context, arg SetReviewLinkedPRRefsParams) error {
	_, err := q.db.Exec(ctx, setReviewLinkedPRRefs, arg.ID, arg.LinkedPRRefs)
	return err
}

const updateReviewCrossPRHash = `-- name: UpdateReviewCrossPRHash :exec
UPDATE reviews SET cross_pr_hash = $2 WHERE id = $1
`

type UpdateReviewCrossPRHashParams struct {
	ID          uuid.UUID `json:"id"`
	CrossPRHash *string   `json:"cross_pr_hash"`
}

// Stores the SHA256 hash of the cross-PR findings+diffs bundle that the async
// cross-PR stage used to produce its output. Subsequent runs compare against
// this value and skip the LLM call when unchanged. Persisted so the
// idempotency check survives machine restarts.
func (q *Queries) UpdateReviewCrossPRHash(ctx context.Context, arg UpdateReviewCrossPRHashParams) error {
	_, err := q.db.Exec(ctx, updateReviewCrossPRHash, arg.ID, arg.CrossPRHash)
	return err
}

const updateReviewStatus = `-- name: UpdateReviewStatus :exec
UPDATE reviews SET status = $2, error = $3, completed_at = CASE WHEN $2 IN ('completed','failed','cancelled') THEN NOW() ELSE NULL END
WHERE id = $1
`

type UpdateReviewStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) error {
	_, err := q.db.Exec(ctx, updateReviewStatus, arg.ID, arg.Status, arg.Error)
	return err
}
