// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countReviewsThisMonth = `-- name: CountReviewsThisMonth :one
SELECT COUNT(*)::int FROM reviews r
JOIN repos rp ON r.repo_id = rp.id
WHERE rp.installation_id = $1
AND r.created_at >= date_trunc('month', NOW())
`

func (q *Queries) CountReviewsThisMonth(ctx context.Context, installationID int64) (int, error) {
	row := q.db.QueryRow(ctx, countReviewsThisMonth, installationID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getLastCompletedReview = `-- name: GetLastCompletedReview :one
SELECT id, repo_id, pr_number, pr_title, pr_author, head_sha, base_sha, COALESCE(head_ref,'') as head_ref, github_review_id,
       status, summary, score, token_usage, trigger, triggered_by, duration_ms, error,
       deep_review, persona, is_incremental, created_at, completed_at
FROM reviews WHERE repo_id = $1 AND pr_number = $2 AND status = 'completed'
ORDER BY completed_at DESC LIMIT 1
`

type GetLastCompletedReviewParams struct {
	RepoID   int64 `json:"repo_id"`
	PRNumber int   `json:"pr_number"`
}

type GetLastCompletedReviewRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
}

func (q *Queries) GetLastCompletedReview(ctx context.Context, arg GetLastCompletedReviewParams) (GetLastCompletedReviewRow, error) {
	row := q.db.QueryRow(ctx, getLastCompletedReview, arg.RepoID, arg.PRNumber)
	var i GetLastCompletedReviewRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.PRTitle,
		&i.PRAuthor,
		&i.HeadSHA,
		&i.BaseSHA,
		&i.HeadRef,
		&i.GithubReviewID,
		&i.Status,
		&i.Summary,
		&i.Score,
		&i.TokenUsage,
		&i.Trigger,
		&i.TriggeredBy,
		&i.DurationMs,
		&i.Error,
		&i.DeepReview,
		&i.Persona,
		&i.IsIncremental,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestReviewByPR = `-- name: GetLatestReviewByPR :one
SELECT rv.id, rv.repo_id, rv.pr_number, rv.pr_title, rv.pr_author, rv.head_sha, rv.base_sha, COALESCE(rv.head_ref,'') as head_ref, rv.github_review_id,
       rv.status, rv.summary, rv.score, rv.token_usage, rv.trigger, rv.triggered_by, rv.duration_ms, rv.error,
       rv.deep_review, rv.persona, rv.is_incremental, rv.created_at, rv.completed_at
FROM reviews rv JOIN repos r ON rv.repo_id = r.id
WHERE r.full_name = $1 AND rv.pr_number = $2
  AND rv.status = 'completed'
ORDER BY rv.created_at DESC LIMIT 1
`

type GetLatestReviewByPRParams struct {
	FullName string `json:"full_name"`
	PRNumber int    `json:"pr_number"`
}

type GetLatestReviewByPRRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
}

func (q *Queries) GetLatestReviewByPR(ctx context.Context, arg GetLatestReviewByPRParams) (GetLatestReviewByPRRow, error) {
	row := q.db.QueryRow(ctx, getLatestReviewByPR, arg.FullName, arg.PRNumber)
	var i GetLatestReviewByPRRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.PRTitle,
		&i.PRAuthor,
		&i.HeadSHA,
		&i.BaseSHA,
		&i.HeadRef,
		&i.GithubReviewID,
		&i.Status,
		&i.Summary,
		&i.Score,
		&i.TokenUsage,
		&i.Trigger,
		&i.TriggeredBy,
		&i.DurationMs,
		&i.Error,
		&i.DeepReview,
		&i.Persona,
		&i.IsIncremental,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestReviewBySHA = `-- name: GetLatestReviewBySHA :one
SELECT rv.id, rv.repo_id, rv.pr_number, rv.pr_title, rv.pr_author, rv.head_sha, rv.base_sha, COALESCE(rv.head_ref,'') as head_ref, rv.github_review_id,
       rv.status, rv.summary, rv.score, rv.token_usage, rv.trigger, rv.triggered_by, rv.duration_ms, rv.error,
       rv.deep_review, rv.persona, rv.is_incremental, rv.created_at, rv.completed_at
FROM reviews rv JOIN repos r ON rv.repo_id = r.id
WHERE r.full_name = $1 AND rv.pr_number = $2 AND rv.head_sha = $3
  AND rv.status = 'completed'
ORDER BY rv.created_at DESC LIMIT 1
`

type GetLatestReviewBySHAParams struct {
	FullName string `json:"full_name"`
	PRNumber int    `json:"pr_number"`
	HeadSHA  string `json:"head_sha"`
}

type GetLatestReviewBySHARow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
}

func (q *Queries) GetLatestReviewBySHA(ctx context.Context, arg GetLatestReviewBySHAParams) (GetLatestReviewBySHARow, error) {
	row := q.db.QueryRow(ctx, getLatestReviewBySHA, arg.FullName, arg.PRNumber, arg.HeadSHA)
	var i GetLatestReviewBySHARow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.PRTitle,
		&i.PRAuthor,
		&i.HeadSHA,
		&i.BaseSHA,
		&i.HeadRef,
		&i.GithubReviewID,
		&i.Status,
		&i.Summary,
		&i.Score,
		&i.TokenUsage,
		&i.Trigger,
		&i.TriggeredBy,
		&i.DurationMs,
		&i.Error,
		&i.DeepReview,
		&i.Persona,
		&i.IsIncremental,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRepoReviewStats = `-- name: GetRepoReviewStats :one
WITH recent AS (
  SELECT token_usage FROM reviews
  WHERE repo_id = $1 AND status = 'completed' AND token_usage IS NOT NULL
  ORDER BY created_at DESC
  LIMIT $2
)
SELECT
  COUNT(*)::int AS sample_size,
  COALESCE(AVG((token_usage->'total'->>'total_tokens')::bigint), 0)::bigint AS avg_tokens,
  COALESCE(AVG(NULLIF((token_usage->'total'->>'cost')::float8, 0)), 0)::float8 AS avg_cost,
  COALESCE(BOOL_OR((token_usage->'total'->>'cost') IS NOT NULL AND (token_usage->'total'->>'cost')::float8 > 0), false) AS cost_available
FROM recent
`

type GetRepoReviewStatsParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int32 `json:"limit"`
}

type GetRepoReviewStatsRow struct {
	SampleSize    int         `json:"sample_size"`
	AvgTokens     int64       `json:"avg_tokens"`
	AvgCost       float64     `json:"avg_cost"`
	CostAvailable interface{} `json:"cost_available"`
}

// Returns averaged token + cost stats over the last N completed reviews for a repo,
// used to estimate cost for the "Trigger review" checkbox comment. `cost_available`
// is true only when at least one review in the sample has token_usage.total.cost.
func (q *Queries) GetRepoReviewStats(ctx context.Context, arg GetRepoReviewStatsParams) (GetRepoReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getRepoReviewStats, arg.RepoID, arg.Limit)
	var i GetRepoReviewStatsRow
	err := row.Scan(
		&i.SampleSize,
		&i.AvgTokens,
		&i.AvgCost,
		&i.CostAvailable,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT id, repo_id, pr_number, pr_title, pr_author, head_sha, base_sha, COALESCE(head_ref,'') as head_ref, github_review_id,
       status, summary, score, token_usage, trigger, triggered_by, duration_ms, error,
       deep_review, persona, is_incremental, created_at, completed_at, simulation_results, diagram, diagram_title
FROM reviews WHERE id = $1
`

type GetReviewRow struct {
	ID                uuid.UUID  `json:"id"`
	RepoID            int64      `json:"repo_id"`
	PRNumber          int        `json:"pr_number"`
	PRTitle           string     `json:"pr_title"`
	PRAuthor          string     `json:"pr_author"`
	HeadSHA           string     `json:"head_sha"`
	BaseSHA           string     `json:"base_sha"`
	HeadRef           string     `json:"head_ref"`
	GithubReviewID    *int64     `json:"github_review_id"`
	Status            string     `json:"status"`
	Summary           *string    `json:"summary"`
	Score             *int       `json:"score"`
	TokenUsage        []byte     `json:"token_usage"`
	Trigger           string     `json:"trigger"`
	TriggeredBy       *string    `json:"triggered_by"`
	DurationMs        *int       `json:"duration_ms"`
	Error             *string    `json:"error"`
	DeepReview        bool       `json:"deep_review"`
	Persona           *string    `json:"persona"`
	IsIncremental     bool       `json:"is_incremental"`
	CreatedAt         time.Time  `json:"created_at"`
	CompletedAt       *time.Time `json:"completed_at"`
	SimulationResults []byte     `json:"simulation_results"`
	Diagram           *string    `json:"diagram"`
	DiagramTitle      *string    `json:"diagram_title"`
}

func (q *Queries) GetReview(ctx context.Context, id uuid.UUID) (GetReviewRow, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i GetReviewRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PRNumber,
		&i.PRTitle,
		&i.PRAuthor,
		&i.HeadSHA,
		&i.BaseSHA,
		&i.HeadRef,
		&i.GithubReviewID,
		&i.Status,
		&i.Summary,
		&i.Score,
		&i.TokenUsage,
		&i.Trigger,
		&i.TriggeredBy,
		&i.DurationMs,
		&i.Error,
		&i.DeepReview,
		&i.Persona,
		&i.IsIncremental,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.SimulationResults,
		&i.Diagram,
		&i.DiagramTitle,
	)
	return i, err
}

const listAllReviewsScoped = `-- name: ListAllReviewsScoped :many
SELECT rv.id, rv.repo_id, rv.pr_number, rv.pr_title, rv.pr_author, rv.head_sha, rv.base_sha, COALESCE(rv.head_ref,'') as head_ref, rv.github_review_id,
       rv.status, rv.summary, rv.score, rv.token_usage, rv.trigger, rv.triggered_by, rv.duration_ms, rv.error,
       rv.deep_review, rv.persona, rv.is_incremental, rv.created_at, rv.completed_at
FROM reviews rv
JOIN repos r ON rv.repo_id = r.id
WHERE r.installation_id = ANY($1::bigint[])
ORDER BY rv.created_at DESC LIMIT $2 OFFSET $3
`

type ListAllReviewsScopedParams struct {
	Column1 []int64 `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type ListAllReviewsScopedRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
}

func (q *Queries) ListAllReviewsScoped(ctx context.Context, arg ListAllReviewsScopedParams) ([]ListAllReviewsScopedRow, error) {
	rows, err := q.db.Query(ctx, listAllReviewsScoped, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReviewsScopedRow
	for rows.Next() {
		var i ListAllReviewsScopedRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.PRNumber,
			&i.PRTitle,
			&i.PRAuthor,
			&i.HeadSHA,
			&i.BaseSHA,
			&i.HeadRef,
			&i.GithubReviewID,
			&i.Status,
			&i.Summary,
			&i.Score,
			&i.TokenUsage,
			&i.Trigger,
			&i.TriggeredBy,
			&i.DurationMs,
			&i.Error,
			&i.DeepReview,
			&i.Persona,
			&i.IsIncremental,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT id, repo_id, pr_number, pr_title, pr_author, head_sha, base_sha, COALESCE(head_ref,'') as head_ref, github_review_id,
       status, summary, score, token_usage, trigger, triggered_by, duration_ms, error,
       deep_review, persona, is_incremental, created_at, completed_at
FROM reviews WHERE repo_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReviewsParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListReviewsRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.PRNumber,
			&i.PRTitle,
			&i.PRAuthor,
			&i.HeadSHA,
			&i.BaseSHA,
			&i.HeadRef,
			&i.GithubReviewID,
			&i.Status,
			&i.Summary,
			&i.Score,
			&i.TokenUsage,
			&i.Trigger,
			&i.TriggeredBy,
			&i.DurationMs,
			&i.Error,
			&i.DeepReview,
			&i.Persona,
			&i.IsIncremental,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsScoped = `-- name: ListReviewsScoped :many
SELECT rv.id, rv.repo_id, rv.pr_number, rv.pr_title, rv.pr_author, rv.head_sha, rv.base_sha, COALESCE(rv.head_ref,'') as head_ref, rv.github_review_id,
       rv.status, rv.summary, rv.score, rv.token_usage, rv.trigger, rv.triggered_by, rv.duration_ms, rv.error,
       rv.deep_review, rv.persona, rv.is_incremental, rv.created_at, rv.completed_at
FROM reviews rv
JOIN repos r ON rv.repo_id = r.id
WHERE rv.repo_id = $1 AND r.installation_id = ANY($2::bigint[])
ORDER BY rv.created_at DESC LIMIT $3 OFFSET $4
`

type ListReviewsScopedParams struct {
	RepoID  int64   `json:"repo_id"`
	Column2 []int64 `json:"column_2"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type ListReviewsScopedRow struct {
	ID             uuid.UUID  `json:"id"`
	RepoID         int64      `json:"repo_id"`
	PRNumber       int        `json:"pr_number"`
	PRTitle        string     `json:"pr_title"`
	PRAuthor       string     `json:"pr_author"`
	HeadSHA        string     `json:"head_sha"`
	BaseSHA        string     `json:"base_sha"`
	HeadRef        string     `json:"head_ref"`
	GithubReviewID *int64     `json:"github_review_id"`
	Status         string     `json:"status"`
	Summary        *string    `json:"summary"`
	Score          *int       `json:"score"`
	TokenUsage     []byte     `json:"token_usage"`
	Trigger        string     `json:"trigger"`
	TriggeredBy    *string    `json:"triggered_by"`
	DurationMs     *int       `json:"duration_ms"`
	Error          *string    `json:"error"`
	DeepReview     bool       `json:"deep_review"`
	Persona        *string    `json:"persona"`
	IsIncremental  bool       `json:"is_incremental"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
}

func (q *Queries) ListReviewsScoped(ctx context.Context, arg ListReviewsScopedParams) ([]ListReviewsScopedRow, error) {
	rows, err := q.db.Query(ctx, listReviewsScoped,
		arg.RepoID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsScopedRow
	for rows.Next() {
		var i ListReviewsScopedRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.PRNumber,
			&i.PRTitle,
			&i.PRAuthor,
			&i.HeadSHA,
			&i.BaseSHA,
			&i.HeadRef,
			&i.GithubReviewID,
			&i.Status,
			&i.Summary,
			&i.Score,
			&i.TokenUsage,
			&i.Trigger,
			&i.TriggeredBy,
			&i.DurationMs,
			&i.Error,
			&i.DeepReview,
			&i.Persona,
			&i.IsIncremental,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewStatus = `-- name: UpdateReviewStatus :exec
UPDATE reviews SET status = $2, error = $3, completed_at = CASE WHEN $2 IN ('completed','failed','cancelled') THEN NOW() ELSE NULL END
WHERE id = $1
`

type UpdateReviewStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) error {
	_, err := q.db.Exec(ctx, updateReviewStatus, arg.ID, arg.Status, arg.Error)
	return err
}
