// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_comments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReviewComment = `-- name: CreateReviewComment :exec
INSERT INTO review_comments (review_id, file_path, start_line, end_line, side, body, severity, category, specialist, confidence_score, code_snippet, github_comment_id, matched_pattern_id, matched_pattern_score, enforced_rule_content, is_new_finding)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type CreateReviewCommentParams struct {
	ReviewID            uuid.UUID `json:"review_id"`
	FilePath            string    `json:"file_path"`
	StartLine           *int      `json:"start_line"`
	EndLine             *int      `json:"end_line"`
	Side                *string   `json:"side"`
	Body                string    `json:"body"`
	Severity            *string   `json:"severity"`
	Category            *string   `json:"category"`
	Specialist          *string   `json:"specialist"`
	ConfidenceScore     *int      `json:"confidence_score"`
	CodeSnippet         *string   `json:"code_snippet"`
	GithubCommentID     *int64    `json:"github_comment_id"`
	MatchedPatternID    *int64    `json:"matched_pattern_id"`
	MatchedPatternScore *float32  `json:"matched_pattern_score"`
	EnforcedRuleContent *string   `json:"enforced_rule_content"`
	IsNewFinding        *bool     `json:"is_new_finding"`
}

func (q *Queries) CreateReviewComment(ctx context.Context, arg CreateReviewCommentParams) error {
	_, err := q.db.Exec(ctx, createReviewComment,
		arg.ReviewID,
		arg.FilePath,
		arg.StartLine,
		arg.EndLine,
		arg.Side,
		arg.Body,
		arg.Severity,
		arg.Category,
		arg.Specialist,
		arg.ConfidenceScore,
		arg.CodeSnippet,
		arg.GithubCommentID,
		arg.MatchedPatternID,
		arg.MatchedPatternScore,
		arg.EnforcedRuleContent,
		arg.IsNewFinding,
	)
	return err
}

const getCommentByGithubID = `-- name: GetCommentByGithubID :one
SELECT id, review_id, file_path, start_line, end_line, side, body, severity, category,
       specialist, confidence_score, code_snippet, github_comment_id,
       matched_pattern_id, matched_pattern_score, enforced_rule_content, is_new_finding,
       created_at
FROM review_comments WHERE github_comment_id = $1
`

type GetCommentByGithubIDRow struct {
	ID                  uuid.UUID `json:"id"`
	ReviewID            uuid.UUID `json:"review_id"`
	FilePath            string    `json:"file_path"`
	StartLine           *int      `json:"start_line"`
	EndLine             *int      `json:"end_line"`
	Side                *string   `json:"side"`
	Body                string    `json:"body"`
	Severity            *string   `json:"severity"`
	Category            *string   `json:"category"`
	Specialist          *string   `json:"specialist"`
	ConfidenceScore     *int      `json:"confidence_score"`
	CodeSnippet         *string   `json:"code_snippet"`
	GithubCommentID     *int64    `json:"github_comment_id"`
	MatchedPatternID    *int64    `json:"matched_pattern_id"`
	MatchedPatternScore *float32  `json:"matched_pattern_score"`
	EnforcedRuleContent *string   `json:"enforced_rule_content"`
	IsNewFinding        *bool     `json:"is_new_finding"`
	CreatedAt           time.Time `json:"created_at"`
}

func (q *Queries) GetCommentByGithubID(ctx context.Context, githubCommentID *int64) (GetCommentByGithubIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByGithubID, githubCommentID)
	var i GetCommentByGithubIDRow
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.FilePath,
		&i.StartLine,
		&i.EndLine,
		&i.Side,
		&i.Body,
		&i.Severity,
		&i.Category,
		&i.Specialist,
		&i.ConfidenceScore,
		&i.CodeSnippet,
		&i.GithubCommentID,
		&i.MatchedPatternID,
		&i.MatchedPatternScore,
		&i.EnforcedRuleContent,
		&i.IsNewFinding,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentOutcomes = `-- name: GetCommentOutcomes :many
SELECT id, review_comment_id, outcome, created_at
FROM comment_outcomes WHERE review_comment_id = $1 ORDER BY created_at DESC
`

type GetCommentOutcomesRow struct {
	ID              int        `json:"id"`
	ReviewCommentID uuid.UUID  `json:"review_comment_id"`
	Outcome         string     `json:"outcome"`
	CreatedAt       *time.Time `json:"created_at"`
}

func (q *Queries) GetCommentOutcomes(ctx context.Context, reviewCommentID uuid.UUID) ([]GetCommentOutcomesRow, error) {
	rows, err := q.db.Query(ctx, getCommentOutcomes, reviewCommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentOutcomesRow
	for rows.Next() {
		var i GetCommentOutcomesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewCommentID,
			&i.Outcome,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewComments = `-- name: GetReviewComments :many
SELECT id, review_id, file_path, start_line, end_line, side, body, severity, category,
       specialist, confidence_score, code_snippet, github_comment_id,
       matched_pattern_id, matched_pattern_score, enforced_rule_content, is_new_finding,
       created_at
FROM review_comments WHERE review_id = $1 ORDER BY file_path, start_line
`

type GetReviewCommentsRow struct {
	ID                  uuid.UUID `json:"id"`
	ReviewID            uuid.UUID `json:"review_id"`
	FilePath            string    `json:"file_path"`
	StartLine           *int      `json:"start_line"`
	EndLine             *int      `json:"end_line"`
	Side                *string   `json:"side"`
	Body                string    `json:"body"`
	Severity            *string   `json:"severity"`
	Category            *string   `json:"category"`
	Specialist          *string   `json:"specialist"`
	ConfidenceScore     *int      `json:"confidence_score"`
	CodeSnippet         *string   `json:"code_snippet"`
	GithubCommentID     *int64    `json:"github_comment_id"`
	MatchedPatternID    *int64    `json:"matched_pattern_id"`
	MatchedPatternScore *float32  `json:"matched_pattern_score"`
	EnforcedRuleContent *string   `json:"enforced_rule_content"`
	IsNewFinding        *bool     `json:"is_new_finding"`
	CreatedAt           time.Time `json:"created_at"`
}

func (q *Queries) GetReviewComments(ctx context.Context, reviewID uuid.UUID) ([]GetReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, getReviewComments, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewCommentsRow
	for rows.Next() {
		var i GetReviewCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.Side,
			&i.Body,
			&i.Severity,
			&i.Category,
			&i.Specialist,
			&i.ConfidenceScore,
			&i.CodeSnippet,
			&i.GithubCommentID,
			&i.MatchedPatternID,
			&i.MatchedPatternScore,
			&i.EnforcedRuleContent,
			&i.IsNewFinding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCommentOutcome = `-- name: RecordCommentOutcome :exec
INSERT INTO comment_outcomes (review_comment_id, outcome)
VALUES ($1, $2)
ON CONFLICT (review_comment_id, outcome) DO NOTHING
`

type RecordCommentOutcomeParams struct {
	ReviewCommentID uuid.UUID `json:"review_comment_id"`
	Outcome         string    `json:"outcome"`
}

// Idempotent: webhook retries delivering the same reaction event produce no-op
// second inserts instead of duplicate rows. Paired with the UNIQUE constraint
// added in migration 037.
func (q *Queries) RecordCommentOutcome(ctx context.Context, arg RecordCommentOutcomeParams) error {
	_, err := q.db.Exec(ctx, recordCommentOutcome, arg.ReviewCommentID, arg.Outcome)
	return err
}
