// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_minor_notes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getReviewMinorNotes = `-- name: GetReviewMinorNotes :many
SELECT n.id, n.review_id, n.attempt_generation, n.file_path, n.line, n.severity, n.title, n.created_at
FROM review_minor_notes n
JOIN reviews r ON r.id = n.review_id
WHERE n.review_id = $1 AND n.attempt_generation = r.attempt_generation
ORDER BY n.file_path, n.line, n.id
`

func (q *Queries) GetReviewMinorNotes(ctx context.Context, reviewID uuid.UUID) ([]ReviewMinorNote, error) {
	rows, err := q.db.Query(ctx, getReviewMinorNotes, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewMinorNote
	for rows.Next() {
		var i ReviewMinorNote
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.AttemptGeneration,
			&i.FilePath,
			&i.Line,
			&i.Severity,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
