// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenarios.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateScenario = `-- name: ActivateScenario :exec
UPDATE scenarios SET active = TRUE WHERE id = $1
`

func (q *Queries) ActivateScenario(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, activateScenario, id)
	return err
}

const createPendingScenario = `-- name: CreatePendingScenario :one
INSERT INTO scenarios (installation_id, repo_id, description, source, source_ref, files, modules, severity, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, FALSE)
RETURNING id
`

type CreatePendingScenarioParams struct {
	InstallationID int64    `json:"installation_id"`
	RepoID         *int64   `json:"repo_id"`
	Description    string   `json:"description"`
	Source         string   `json:"source"`
	SourceRef      *string  `json:"source_ref"`
	Files          []string `json:"files"`
	Modules        []string `json:"modules"`
	Severity       *string  `json:"severity"`
}

func (q *Queries) CreatePendingScenario(ctx context.Context, arg CreatePendingScenarioParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPendingScenario,
		arg.InstallationID,
		arg.RepoID,
		arg.Description,
		arg.Source,
		arg.SourceRef,
		arg.Files,
		arg.Modules,
		arg.Severity,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenarios (installation_id, repo_id, description, source, source_ref, files, modules, severity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateScenarioParams struct {
	InstallationID int64    `json:"installation_id"`
	RepoID         *int64   `json:"repo_id"`
	Description    string   `json:"description"`
	Source         string   `json:"source"`
	SourceRef      *string  `json:"source_ref"`
	Files          []string `json:"files"`
	Modules        []string `json:"modules"`
	Severity       *string  `json:"severity"`
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (int64, error) {
	row := q.db.QueryRow(ctx, createScenario,
		arg.InstallationID,
		arg.RepoID,
		arg.Description,
		arg.Source,
		arg.SourceRef,
		arg.Files,
		arg.Modules,
		arg.Severity,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createScenarioRun = `-- name: CreateScenarioRun :one
INSERT INTO scenario_runs (
    scenario_id, review_id, pr_number, verdict, confidence, why, fix, root_cause, impact
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (scenario_id, review_id) DO UPDATE SET
    verdict    = EXCLUDED.verdict,
    confidence = EXCLUDED.confidence,
    why        = EXCLUDED.why,
    fix        = EXCLUDED.fix,
    root_cause = EXCLUDED.root_cause,
    impact     = EXCLUDED.impact,
    created_at = NOW()
RETURNING id, scenario_id, review_id, pr_number, verdict, confidence, why, fix, root_cause, impact, created_at
`

type CreateScenarioRunParams struct {
	ScenarioID int64          `json:"scenario_id"`
	ReviewID   uuid.UUID      `json:"review_id"`
	PRNumber   int            `json:"pr_number"`
	Verdict    string         `json:"verdict"`
	Confidence pgtype.Numeric `json:"confidence"`
	Why        *string        `json:"why"`
	Fix        *string        `json:"fix"`
	RootCause  *string        `json:"root_cause"`
	Impact     *string        `json:"impact"`
}

func (q *Queries) CreateScenarioRun(ctx context.Context, arg CreateScenarioRunParams) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, createScenarioRun,
		arg.ScenarioID,
		arg.ReviewID,
		arg.PRNumber,
		arg.Verdict,
		arg.Confidence,
		arg.Why,
		arg.Fix,
		arg.RootCause,
		arg.Impact,
	)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.ReviewID,
		&i.PRNumber,
		&i.Verdict,
		&i.Confidence,
		&i.Why,
		&i.Fix,
		&i.RootCause,
		&i.Impact,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateScenario = `-- name: DeactivateScenario :exec
UPDATE scenarios SET active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateScenario(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateScenario, id)
	return err
}

const deactivateScenarioScoped = `-- name: DeactivateScenarioScoped :execrows
UPDATE scenarios SET active = FALSE WHERE id = $1 AND installation_id = ANY($2::bigint[])
`

type DeactivateScenarioScopedParams struct {
	ID      int64   `json:"id"`
	Column2 []int64 `json:"column_2"`
}

func (q *Queries) DeactivateScenarioScoped(ctx context.Context, arg DeactivateScenarioScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateScenarioScoped, arg.ID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScenarioKPIs = `-- name: GetScenarioKPIs :one
SELECT
    COUNT(*) FILTER (WHERE active)                                                                           AS active,
    COUNT(*) FILTER (WHERE active AND last_verdict = 'broken' AND last_run_at > NOW() - INTERVAL '7 days') AS broken_this_week,
    COUNT(*) FILTER (WHERE active AND last_verdict = 'fixed'  AND last_run_at > NOW() - INTERVAL '7 days') AS fixed_this_week,
    COUNT(*) FILTER (WHERE active AND is_outdated)                                                         AS outdated
FROM scenarios
WHERE repo_id = $1
`

type GetScenarioKPIsRow struct {
	Active         int64 `json:"active"`
	BrokenThisWeek int64 `json:"broken_this_week"`
	FixedThisWeek  int64 `json:"fixed_this_week"`
	Outdated       int64 `json:"outdated"`
}

// All four counts are scoped to active scenarios — an inactive-but-broken row would inflate
// "Broken this week" without being visible in the list, so we exclude them everywhere.
func (q *Queries) GetScenarioKPIs(ctx context.Context, repoID *int64) (GetScenarioKPIsRow, error) {
	row := q.db.QueryRow(ctx, getScenarioKPIs, repoID)
	var i GetScenarioKPIsRow
	err := row.Scan(
		&i.Active,
		&i.BrokenThisWeek,
		&i.FixedThisWeek,
		&i.Outdated,
	)
	return i, err
}

const getScenarioRuns = `-- name: GetScenarioRuns :many
SELECT id, scenario_id, review_id, pr_number, verdict, confidence, why, fix, root_cause, impact, created_at
FROM scenario_runs
WHERE scenario_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetScenarioRunsParams struct {
	ScenarioID int64 `json:"scenario_id"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) GetScenarioRuns(ctx context.Context, arg GetScenarioRunsParams) ([]ScenarioRun, error) {
	rows, err := q.db.Query(ctx, getScenarioRuns, arg.ScenarioID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScenarioRun
	for rows.Next() {
		var i ScenarioRun
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioID,
			&i.ReviewID,
			&i.PRNumber,
			&i.Verdict,
			&i.Confidence,
			&i.Why,
			&i.Fix,
			&i.RootCause,
			&i.Impact,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementScenarioTriggerCount = `-- name: IncrementScenarioTriggerCount :exec
UPDATE scenarios SET trigger_count = trigger_count + 1 WHERE id = $1
`

func (q *Queries) IncrementScenarioTriggerCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementScenarioTriggerCount, id)
	return err
}

const listScenariosForFiles = `-- name: ListScenariosForFiles :many
WITH recent_runs AS (
    SELECT
        sr.scenario_id,
        COUNT(*)::double precision                                                    AS n,
        COUNT(*) FILTER (WHERE sr.verdict IN ('broken','partial'))::double precision  AS wins
    FROM scenario_runs sr
    JOIN scenarios     s  ON s.id = sr.scenario_id
    WHERE s.repo_id = $1
      AND sr.created_at > NOW() - INTERVAL '90 days'
    GROUP BY sr.scenario_id
),
repo_total AS (
    -- GREATEST(..., 1) avoids ln(0) on a fresh repo with no prior runs.
    SELECT GREATEST(COALESCE(SUM(n), 0), 1)::double precision AS t
    FROM recent_runs
)
SELECT
    s.id, s.installation_id, s.repo_id, s.description, s.source,
    COALESCE(s.source_ref,'') AS source_ref, s.files, s.modules,
    COALESCE(s.severity,'medium') AS severity, s.active, s.created_at,
    COALESCE(s.steps,'[]') AS steps,
    COALESCE(s.initial_state,'') AS initial_state,
    COALESCE(s.expected_outcome,'') AS expected_outcome,
    COALESCE(s.is_outdated,FALSE) AS is_outdated,
    s.last_run_at,
    s.last_verdict, s.last_confidence, s.last_why, s.last_fix, s.last_pr_number, s.last_review_id,
    s.trigger_count
FROM scenarios s
LEFT JOIN recent_runs r ON r.scenario_id = s.id
WHERE s.repo_id = $1 AND s.active = TRUE AND s.files && $2::text[]
ORDER BY
    CASE
        WHEN COALESCE(r.n, 0) = 0 THEN 1e9
        ELSE (r.wins / r.n) + sqrt(2.0 * ln((SELECT t FROM repo_total)) / r.n)
    END DESC,
    s.created_at DESC
LIMIT 20
`

type ListScenariosForFilesParams struct {
	RepoID  *int64   `json:"repo_id"`
	Column2 []string `json:"column_2"`
}

type ListScenariosForFilesRow struct {
	ID              int64           `json:"id"`
	InstallationID  int64           `json:"installation_id"`
	RepoID          *int64          `json:"repo_id"`
	Description     string          `json:"description"`
	Source          string          `json:"source"`
	SourceRef       string          `json:"source_ref"`
	Files           []string        `json:"files"`
	Modules         []string        `json:"modules"`
	Severity        string          `json:"severity"`
	Active          *bool           `json:"active"`
	CreatedAt       *time.Time      `json:"created_at"`
	Steps           json.RawMessage `json:"steps"`
	InitialState    string          `json:"initial_state"`
	ExpectedOutcome string          `json:"expected_outcome"`
	IsOutdated      bool            `json:"is_outdated"`
	LastRunAt       *time.Time      `json:"last_run_at"`
	LastVerdict     *string         `json:"last_verdict"`
	LastConfidence  pgtype.Numeric  `json:"last_confidence"`
	LastWhy         *string         `json:"last_why"`
	LastFix         *string         `json:"last_fix"`
	LastPrNumber    *int            `json:"last_pr_number"`
	LastReviewID    *uuid.UUID      `json:"last_review_id"`
	TriggerCount    int             `json:"trigger_count"`
}

// Ranks matching scenarios by UCB1. Full write-up:
// docs/plans/2026-04-17-ucb-scenario-selection.md
//
// score = mean_reward + sqrt(2 * ln(T) / n)
//
//	reward = 1 when scenario_runs.verdict IN ('broken','partial'), else 0
//	n      = recent runs for this scenario (last 90 days)
//	T      = total recent runs across scenarios in this repo
//
// Scenarios with n = 0 get priority 1e9 so newcomers are guaranteed their first run
// (fixes cold-start starvation from the old `ORDER BY trigger_count DESC`).
func (q *Queries) ListScenariosForFiles(ctx context.Context, arg ListScenariosForFilesParams) ([]ListScenariosForFilesRow, error) {
	rows, err := q.db.Query(ctx, listScenariosForFiles, arg.RepoID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenariosForFilesRow
	for rows.Next() {
		var i ListScenariosForFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.RepoID,
			&i.Description,
			&i.Source,
			&i.SourceRef,
			&i.Files,
			&i.Modules,
			&i.Severity,
			&i.Active,
			&i.CreatedAt,
			&i.Steps,
			&i.InitialState,
			&i.ExpectedOutcome,
			&i.IsOutdated,
			&i.LastRunAt,
			&i.LastVerdict,
			&i.LastConfidence,
			&i.LastWhy,
			&i.LastFix,
			&i.LastPrNumber,
			&i.LastReviewID,
			&i.TriggerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenariosForRepo = `-- name: ListScenariosForRepo :many
SELECT
    id, installation_id, repo_id, description, source,
    COALESCE(source_ref,'') AS source_ref, files, modules,
    COALESCE(severity,'medium') AS severity, active, created_at,
    COALESCE(steps,'[]') AS steps,
    COALESCE(initial_state,'') AS initial_state,
    COALESCE(expected_outcome,'') AS expected_outcome,
    COALESCE(is_outdated,FALSE) AS is_outdated,
    last_run_at,
    last_verdict, last_confidence, last_why, last_fix, last_pr_number, last_review_id,
    trigger_count
FROM scenarios
WHERE repo_id = $1
ORDER BY active DESC, created_at DESC
LIMIT $2
`

type ListScenariosForRepoParams struct {
	RepoID *int64 `json:"repo_id"`
	Limit  int32  `json:"limit"`
}

type ListScenariosForRepoRow struct {
	ID              int64           `json:"id"`
	InstallationID  int64           `json:"installation_id"`
	RepoID          *int64          `json:"repo_id"`
	Description     string          `json:"description"`
	Source          string          `json:"source"`
	SourceRef       string          `json:"source_ref"`
	Files           []string        `json:"files"`
	Modules         []string        `json:"modules"`
	Severity        string          `json:"severity"`
	Active          *bool           `json:"active"`
	CreatedAt       *time.Time      `json:"created_at"`
	Steps           json.RawMessage `json:"steps"`
	InitialState    string          `json:"initial_state"`
	ExpectedOutcome string          `json:"expected_outcome"`
	IsOutdated      bool            `json:"is_outdated"`
	LastRunAt       *time.Time      `json:"last_run_at"`
	LastVerdict     *string         `json:"last_verdict"`
	LastConfidence  pgtype.Numeric  `json:"last_confidence"`
	LastWhy         *string         `json:"last_why"`
	LastFix         *string         `json:"last_fix"`
	LastPrNumber    *int            `json:"last_pr_number"`
	LastReviewID    *uuid.UUID      `json:"last_review_id"`
	TriggerCount    int             `json:"trigger_count"`
}

func (q *Queries) ListScenariosForRepo(ctx context.Context, arg ListScenariosForRepoParams) ([]ListScenariosForRepoRow, error) {
	rows, err := q.db.Query(ctx, listScenariosForRepo, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenariosForRepoRow
	for rows.Next() {
		var i ListScenariosForRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.RepoID,
			&i.Description,
			&i.Source,
			&i.SourceRef,
			&i.Files,
			&i.Modules,
			&i.Severity,
			&i.Active,
			&i.CreatedAt,
			&i.Steps,
			&i.InitialState,
			&i.ExpectedOutcome,
			&i.IsOutdated,
			&i.LastRunAt,
			&i.LastVerdict,
			&i.LastConfidence,
			&i.LastWhy,
			&i.LastFix,
			&i.LastPrNumber,
			&i.LastReviewID,
			&i.TriggerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScenarioOutdated = `-- name: MarkScenarioOutdated :exec
UPDATE scenarios SET is_outdated = TRUE
WHERE repo_id = $1 AND active = TRUE AND files && $2::text[]
`

type MarkScenarioOutdatedParams struct {
	RepoID  *int64   `json:"repo_id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) MarkScenarioOutdated(ctx context.Context, arg MarkScenarioOutdatedParams) error {
	_, err := q.db.Exec(ctx, markScenarioOutdated, arg.RepoID, arg.Column2)
	return err
}

const updateScenarioLastRun = `-- name: UpdateScenarioLastRun :exec
UPDATE scenarios
SET last_run_at     = NOW(),
    is_outdated     = FALSE,
    last_verdict    = $2,
    last_confidence = $3,
    last_why        = $4,
    last_fix        = $5,
    last_pr_number  = $6,
    last_review_id  = $7
WHERE id = $1
`

type UpdateScenarioLastRunParams struct {
	ID             int64          `json:"id"`
	LastVerdict    *string        `json:"last_verdict"`
	LastConfidence pgtype.Numeric `json:"last_confidence"`
	LastWhy        *string        `json:"last_why"`
	LastFix        *string        `json:"last_fix"`
	LastPrNumber   *int           `json:"last_pr_number"`
	LastReviewID   *uuid.UUID     `json:"last_review_id"`
}

func (q *Queries) UpdateScenarioLastRun(ctx context.Context, arg UpdateScenarioLastRunParams) error {
	_, err := q.db.Exec(ctx, updateScenarioLastRun,
		arg.ID,
		arg.LastVerdict,
		arg.LastConfidence,
		arg.LastWhy,
		arg.LastFix,
		arg.LastPrNumber,
		arg.LastReviewID,
	)
	return err
}
