// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"time"
)

const getStats = `-- name: GetStats :one
SELECT
    (SELECT COUNT(*) FROM reviews
     WHERE NOT (github_review_id IS NULL AND status = 'failed' AND error IN ('auto_run_disabled', 'no_api_key')))::int as total_reviews,
    (SELECT COUNT(*) FROM reviews WHERE created_at >= CURRENT_DATE AND status = 'completed')::int as completed_today,
    COALESCE((SELECT AVG(score)::int FROM reviews WHERE score IS NOT NULL), 0)::int as avg_score,
    (SELECT COUNT(*) FROM repos WHERE enabled = true)::int as active_repos,
    (SELECT COUNT(*) FROM review_comments rc JOIN reviews rv ON rv.id = rc.review_id WHERE rc.attempt_generation = rv.attempt_generation AND rc.severity = 'critical' AND rc.state <> 'suppressed')::int as critical_finds,
    (SELECT COUNT(*) FROM reviews WHERE status IN ('pending','in_progress'))::int as pending_reviews,
    COALESCE((SELECT (COUNT(*) FILTER (WHERE score < 10) * 100 / NULLIF(COUNT(*) FILTER (WHERE status = 'completed'), 0))::int FROM reviews), 0)::int as catch_rate,
    (SELECT COUNT(*) FROM reviews WHERE created_at >= NOW() - INTERVAL '7 days')::int as prs_this_week,
    (SELECT COUNT(*) FROM reviews WHERE score IS NOT NULL AND score <= 4)::int as high_risk_count,
    COALESCE((SELECT (AVG(EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000))::int FROM reviews WHERE completed_at IS NOT NULL), 0)::int as avg_review_time_ms,
    (SELECT COUNT(*) FROM reviews WHERE deep_review = true)::int as deep_review_count
`

type GetStatsRow struct {
	TotalReviews    int `json:"total_reviews"`
	CompletedToday  int `json:"completed_today"`
	AvgScore        int `json:"avg_score"`
	ActiveRepos     int `json:"active_repos"`
	CriticalFinds   int `json:"critical_finds"`
	PendingReviews  int `json:"pending_reviews"`
	CatchRate       int `json:"catch_rate"`
	PrsThisWeek     int `json:"prs_this_week"`
	HighRiskCount   int `json:"high_risk_count"`
	AvgReviewTimeMs int `json:"avg_review_time_ms"`
	DeepReviewCount int `json:"deep_review_count"`
}

// critical_finds excludes state='suppressed': those findings were generated and
// then withheld, so no PR author ever received them. Counting them advertises
// review coverage that was never delivered.
func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.TotalReviews,
		&i.CompletedToday,
		&i.AvgScore,
		&i.ActiveRepos,
		&i.CriticalFinds,
		&i.PendingReviews,
		&i.CatchRate,
		&i.PrsThisWeek,
		&i.HighRiskCount,
		&i.AvgReviewTimeMs,
		&i.DeepReviewCount,
	)
	return i, err
}

const getStatsScoped = `-- name: GetStatsScoped :one
WITH scoped_reviews AS (
    SELECT id, repo_id, pr_number, pr_title, pr_author, head_sha, base_sha, github_review_id, status, summary, score, token_usage, trigger, triggered_by, duration_ms, error, created_at, completed_at, file_count, deep_review, persona, is_incremental, resolved_stale_count, head_ref, simulation_results, diagram, diagram_title, diagrams, truncated_files, brief, memory_enabled, cross_pr_hash, linked_pr_refs, linked_issue_refs, trace_id, review_contract, started_comment_id, budget_note, attempt_generation, review_post_claimed_at, expected_github_inline_count FROM reviews WHERE repo_id IN (SELECT id FROM repos WHERE installation_id = ANY($1::bigint[]))
)
SELECT
    (SELECT COUNT(*) FROM scoped_reviews
     WHERE NOT (github_review_id IS NULL AND status = 'failed' AND error IN ('auto_run_disabled', 'no_api_key')))::int as total_reviews,
    (SELECT COUNT(*) FROM scoped_reviews WHERE created_at >= CURRENT_DATE AND status = 'completed')::int as completed_today,
    COALESCE((SELECT AVG(score)::int FROM scoped_reviews WHERE score IS NOT NULL), 0)::int as avg_score,
    (SELECT COUNT(*) FROM repos WHERE installation_id = ANY($1::bigint[]) AND enabled = true)::int as active_repos,
    (SELECT COUNT(*) FROM review_comments rc JOIN scoped_reviews rv ON rv.id = rc.review_id WHERE rc.attempt_generation = rv.attempt_generation AND rc.severity = 'critical' AND rc.state <> 'suppressed')::int as critical_finds,
    (SELECT COUNT(*) FROM scoped_reviews WHERE status IN ('pending','in_progress'))::int as pending_reviews,
    COALESCE((SELECT (COUNT(*) FILTER (WHERE score < 10) * 100 / NULLIF(COUNT(*) FILTER (WHERE status = 'completed'), 0))::int FROM scoped_reviews), 0)::int as catch_rate,
    (SELECT COUNT(*) FROM scoped_reviews WHERE created_at >= NOW() - INTERVAL '7 days')::int as prs_this_week,
    (SELECT COUNT(*) FROM scoped_reviews WHERE score IS NOT NULL AND score <= 4)::int as high_risk_count,
    COALESCE((SELECT (AVG(EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000))::int FROM scoped_reviews WHERE completed_at IS NOT NULL), 0)::int as avg_review_time_ms,
    (SELECT COUNT(*) FROM scoped_reviews WHERE deep_review = true)::int as deep_review_count
`

type GetStatsScopedRow struct {
	TotalReviews    int `json:"total_reviews"`
	CompletedToday  int `json:"completed_today"`
	AvgScore        int `json:"avg_score"`
	ActiveRepos     int `json:"active_repos"`
	CriticalFinds   int `json:"critical_finds"`
	PendingReviews  int `json:"pending_reviews"`
	CatchRate       int `json:"catch_rate"`
	PrsThisWeek     int `json:"prs_this_week"`
	HighRiskCount   int `json:"high_risk_count"`
	AvgReviewTimeMs int `json:"avg_review_time_ms"`
	DeepReviewCount int `json:"deep_review_count"`
}

func (q *Queries) GetStatsScoped(ctx context.Context, dollar_1 []int64) (GetStatsScopedRow, error) {
	row := q.db.QueryRow(ctx, getStatsScoped, dollar_1)
	var i GetStatsScopedRow
	err := row.Scan(
		&i.TotalReviews,
		&i.CompletedToday,
		&i.AvgScore,
		&i.ActiveRepos,
		&i.CriticalFinds,
		&i.PendingReviews,
		&i.CatchRate,
		&i.PrsThisWeek,
		&i.HighRiskCount,
		&i.AvgReviewTimeMs,
		&i.DeepReviewCount,
	)
	return i, err
}

const listActivity = `-- name: ListActivity :many
SELECT id, installation_id, action, actor, resource, metadata, created_at
FROM activity_log WHERE installation_id = ANY($1::bigint[]) ORDER BY created_at DESC LIMIT $2::bigint
`

type ListActivityParams struct {
	Column1  []int64 `json:"column_1"`
	RowLimit int64   `json:"row_limit"`
}

type ListActivityRow struct {
	ID             int64     `json:"id"`
	InstallationID *int64    `json:"installation_id"`
	Action         string    `json:"action"`
	Actor          *string   `json:"actor"`
	Resource       *string   `json:"resource"`
	Metadata       []byte    `json:"metadata"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity, arg.Column1, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityRow
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.Action,
			&i.Actor,
			&i.Resource,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewGauge = `-- name: ListReviewGauge :many
SELECT installation_id, category, change_class, posted_findings,
       addressed_human, addressed_agent, dismissed, ignored, deferred,
       address_rate, dismiss_rate, median_seconds_to_merge
FROM vw_review_gauge
WHERE installation_id = ANY($1::bigint[])
ORDER BY category, change_class
`

func (q *Queries) ListReviewGauge(ctx context.Context, dollar_1 []int64) ([]VwReviewGauge, error) {
	rows, err := q.db.Query(ctx, listReviewGauge, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwReviewGauge
	for rows.Next() {
		var i VwReviewGauge
		if err := rows.Scan(
			&i.InstallationID,
			&i.Category,
			&i.ChangeClass,
			&i.PostedFindings,
			&i.AddressedHuman,
			&i.AddressedAgent,
			&i.Dismissed,
			&i.Ignored,
			&i.Deferred,
			&i.AddressRate,
			&i.DismissRate,
			&i.MedianSecondsToMerge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logActivity = `-- name: LogActivity :exec
INSERT INTO activity_log (installation_id, action, actor, resource, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type LogActivityParams struct {
	InstallationID *int64  `json:"installation_id"`
	Action         string  `json:"action"`
	Actor          *string `json:"actor"`
	Resource       *string `json:"resource"`
	Metadata       []byte  `json:"metadata"`
}

func (q *Queries) LogActivity(ctx context.Context, arg LogActivityParams) error {
	_, err := q.db.Exec(ctx, logActivity,
		arg.InstallationID,
		arg.Action,
		arg.Actor,
		arg.Resource,
		arg.Metadata,
	)
	return err
}
