// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: traces.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createTrace = `-- name: CreateTrace :exec
INSERT INTO decision_traces (repo_id, file_path, symbol_name, trace_type, content, severity, review_id, pr_number, metadata)
VALUES ($1, $2, NULLIF($3, ''), $4, $5, NULLIF($6, ''), $7, $8, $9)
`

type CreateTraceParams struct {
	RepoID    int64       `json:"repo_id"`
	FilePath  string      `json:"file_path"`
	Column3   interface{} `json:"column_3"`
	TraceType string      `json:"trace_type"`
	Content   string      `json:"content"`
	Column6   interface{} `json:"column_6"`
	ReviewID  *uuid.UUID  `json:"review_id"`
	PRNumber  *int        `json:"pr_number"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) error {
	_, err := q.db.Exec(ctx, createTrace,
		arg.RepoID,
		arg.FilePath,
		arg.Column3,
		arg.TraceType,
		arg.Content,
		arg.Column6,
		arg.ReviewID,
		arg.PRNumber,
		arg.Metadata,
	)
	return err
}

const getFileRiskScore = `-- name: GetFileRiskScore :one
SELECT COALESCE(SUM(
    CASE severity
        WHEN 'critical' THEN 5
        WHEN 'warning' THEN 3
        WHEN 'suggestion' THEN 1
        ELSE 1
    END
), 0)::int as risk_score
FROM decision_traces
WHERE repo_id = $1 AND file_path = $2 AND created_at > NOW() - INTERVAL '90 days'
`

type GetFileRiskScoreParams struct {
	RepoID   int64  `json:"repo_id"`
	FilePath string `json:"file_path"`
}

func (q *Queries) GetFileRiskScore(ctx context.Context, arg GetFileRiskScoreParams) (int, error) {
	row := q.db.QueryRow(ctx, getFileRiskScore, arg.RepoID, arg.FilePath)
	var risk_score int
	err := row.Scan(&risk_score)
	return risk_score, err
}

const getHotFiles = `-- name: GetHotFiles :many
SELECT file_path, COUNT(*)::int AS trace_count, MAX(created_at) AS last_trace
FROM decision_traces
WHERE repo_id = $1 AND created_at > NOW() - INTERVAL '90 days'
GROUP BY file_path
ORDER BY trace_count DESC
LIMIT $2
`

type GetHotFilesParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int32 `json:"limit"`
}

type GetHotFilesRow struct {
	FilePath   string      `json:"file_path"`
	TraceCount int         `json:"trace_count"`
	LastTrace  interface{} `json:"last_trace"`
}

func (q *Queries) GetHotFiles(ctx context.Context, arg GetHotFilesParams) ([]GetHotFilesRow, error) {
	rows, err := q.db.Query(ctx, getHotFiles, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHotFilesRow
	for rows.Next() {
		var i GetHotFilesRow
		if err := rows.Scan(&i.FilePath, &i.TraceCount, &i.LastTrace); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracesForFiles = `-- name: ListTracesForFiles :many
SELECT id, repo_id, file_path, COALESCE(symbol_name, '') as symbol_name, trace_type, content, COALESCE(severity, '') as severity, review_id, COALESCE(pr_number, 0) as pr_number, COALESCE(metadata, '{}') as metadata, created_at
FROM decision_traces
WHERE repo_id = $1 AND file_path = ANY($2::text[])
ORDER BY created_at DESC
LIMIT $3
`

type ListTracesForFilesParams struct {
	RepoID  int64    `json:"repo_id"`
	Column2 []string `json:"column_2"`
	Limit   int32    `json:"limit"`
}

type ListTracesForFilesRow struct {
	ID         int64           `json:"id"`
	RepoID     int64           `json:"repo_id"`
	FilePath   string          `json:"file_path"`
	SymbolName string          `json:"symbol_name"`
	TraceType  string          `json:"trace_type"`
	Content    string          `json:"content"`
	Severity   string          `json:"severity"`
	ReviewID   *uuid.UUID      `json:"review_id"`
	PRNumber   int             `json:"pr_number"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  *time.Time      `json:"created_at"`
}

func (q *Queries) ListTracesForFiles(ctx context.Context, arg ListTracesForFilesParams) ([]ListTracesForFilesRow, error) {
	rows, err := q.db.Query(ctx, listTracesForFiles, arg.RepoID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracesForFilesRow
	for rows.Next() {
		var i ListTracesForFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.FilePath,
			&i.SymbolName,
			&i.TraceType,
			&i.Content,
			&i.Severity,
			&i.ReviewID,
			&i.PRNumber,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracesForRepo = `-- name: ListTracesForRepo :many
SELECT id, repo_id, file_path, COALESCE(symbol_name, '') as symbol_name, trace_type, content, COALESCE(severity, '') as severity, review_id, COALESCE(pr_number, 0) as pr_number, COALESCE(metadata, '{}') as metadata, created_at
FROM decision_traces
WHERE repo_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTracesForRepoParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int32 `json:"limit"`
}

type ListTracesForRepoRow struct {
	ID         int64           `json:"id"`
	RepoID     int64           `json:"repo_id"`
	FilePath   string          `json:"file_path"`
	SymbolName string          `json:"symbol_name"`
	TraceType  string          `json:"trace_type"`
	Content    string          `json:"content"`
	Severity   string          `json:"severity"`
	ReviewID   *uuid.UUID      `json:"review_id"`
	PRNumber   int             `json:"pr_number"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  *time.Time      `json:"created_at"`
}

func (q *Queries) ListTracesForRepo(ctx context.Context, arg ListTracesForRepoParams) ([]ListTracesForRepoRow, error) {
	rows, err := q.db.Query(ctx, listTracesForRepo, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracesForRepoRow
	for rows.Next() {
		var i ListTracesForRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.FilePath,
			&i.SymbolName,
			&i.TraceType,
			&i.Content,
			&i.Severity,
			&i.ReviewID,
			&i.PRNumber,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
