// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_configs.sql

package db

import (
	"context"
)

const deleteModelConfig = `-- name: DeleteModelConfig :execrows
DELETE FROM model_configs WHERE repo_id = $1 AND stage = $2
`

type DeleteModelConfigParams struct {
	RepoID *int64 `json:"repo_id"`
	Stage  string `json:"stage"`
}

func (q *Queries) DeleteModelConfig(ctx context.Context, arg DeleteModelConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModelConfig, arg.RepoID, arg.Stage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listModelConfigs = `-- name: ListModelConfigs :many
SELECT id, repo_id, stage, provider, model, base_url, max_tokens, temperature, created_at, updated_at
FROM model_configs WHERE repo_id = $1 ORDER BY stage
`

func (q *Queries) ListModelConfigs(ctx context.Context, repoID *int64) ([]ModelConfig, error) {
	rows, err := q.db.Query(ctx, listModelConfigs, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelConfig
	for rows.Next() {
		var i ModelConfig
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Stage,
			&i.Provider,
			&i.Model,
			&i.BaseUrl,
			&i.MaxTokens,
			&i.Temperature,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelConfig = `-- name: UpsertModelConfig :one
INSERT INTO model_configs (repo_id, stage, provider, model, base_url, max_tokens, temperature)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (repo_id, stage) DO UPDATE SET
    provider = EXCLUDED.provider,
    model = EXCLUDED.model,
    base_url = EXCLUDED.base_url,
    max_tokens = EXCLUDED.max_tokens,
    temperature = EXCLUDED.temperature,
    updated_at = NOW()
RETURNING id, repo_id, stage, provider, model, base_url, max_tokens, temperature, created_at, updated_at
`

type UpsertModelConfigParams struct {
	RepoID      *int64  `json:"repo_id"`
	Stage       string  `json:"stage"`
	Provider    string  `json:"provider"`
	Model       string  `json:"model"`
	BaseUrl     *string `json:"base_url"`
	MaxTokens   int32   `json:"max_tokens"`
	Temperature float32 `json:"temperature"`
}

func (q *Queries) UpsertModelConfig(ctx context.Context, arg UpsertModelConfigParams) (ModelConfig, error) {
	row := q.db.QueryRow(ctx, upsertModelConfig,
		arg.RepoID,
		arg.Stage,
		arg.Provider,
		arg.Model,
		arg.BaseUrl,
		arg.MaxTokens,
		arg.Temperature,
	)
	var i ModelConfig
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Stage,
		&i.Provider,
		&i.Model,
		&i.BaseUrl,
		&i.MaxTokens,
		&i.Temperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
