// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID        int64              `json:"id"`
	Action    string             `json:"action"`
	Actor     *string            `json:"actor"`
	Resource  *string            `json:"resource"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CodeEdge struct {
	ID        int64              `json:"id"`
	RepoID    int64              `json:"repo_id"`
	SourceID  int64              `json:"source_id"`
	TargetID  int64              `json:"target_id"`
	Kind      string             `json:"kind"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CodeNode struct {
	ID        int64              `json:"id"`
	RepoID    int64              `json:"repo_id"`
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	FilePath  string             `json:"file_path"`
	LineStart *int32             `json:"line_start"`
	LineEnd   *int32             `json:"line_end"`
	Language  *string            `json:"language"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	PrNumber  *int32             `json:"pr_number"`
	IsMerged  bool               `json:"is_merged"`
}

type CommentOutcome struct {
	ID              int32              `json:"id"`
	ReviewCommentID pgtype.UUID        `json:"review_comment_id"`
	Outcome         string             `json:"outcome"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DecisionTrace struct {
	ID         int64              `json:"id"`
	RepoID     int64              `json:"repo_id"`
	FilePath   string             `json:"file_path"`
	SymbolName *string            `json:"symbol_name"`
	TraceType  string             `json:"trace_type"`
	Content    string             `json:"content"`
	Severity   *string            `json:"severity"`
	ReviewID   pgtype.UUID        `json:"review_id"`
	PrNumber   *int32             `json:"pr_number"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Installation struct {
	ID              int64              `json:"id"`
	InstallationID  int64              `json:"installation_id"`
	OrgLogin        string             `json:"org_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	SuspendedAt     pgtype.Timestamptz `json:"suspended_at"`
	ClerkOrgID      *string            `json:"clerk_org_id"`
	PlanTier        string             `json:"plan_tier"`
	DefaultSettings []byte             `json:"default_settings"`
}

type ModelConfig struct {
	ID             int64              `json:"id"`
	RepoID         *int64             `json:"repo_id"`
	Stage          string             `json:"stage"`
	Provider       string             `json:"provider"`
	Model          string             `json:"model"`
	BaseUrl        *string            `json:"base_url"`
	MaxTokens      int32              `json:"max_tokens"`
	Temperature    float32            `json:"temperature"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	InstallationID *int64             `json:"installation_id"`
}

type Pattern struct {
	ID             int32              `json:"id"`
	InstallationID int64              `json:"installation_id"`
	RepoID         *int64             `json:"repo_id"`
	Content        string             `json:"content"`
	SupermemoryID  *string            `json:"supermemory_id"`
	CreatedBy      *string            `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Source         *string            `json:"source"`
	Category       *string            `json:"category"`
	PrNumber       *int32             `json:"pr_number"`
}

type PipelineState struct {
	ID        pgtype.UUID        `json:"id"`
	ReviewID  pgtype.UUID        `json:"review_id"`
	State     string             `json:"state"`
	Payload   []byte             `json:"payload"`
	Error     *string            `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PromptTemplate struct {
	ID         int32              `json:"id"`
	RepoID     int64              `json:"repo_id"`
	Stage      string             `json:"stage"`
	PromptText string             `json:"prompt_text"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProviderKey struct {
	ID             int64              `json:"id"`
	InstallationID int64              `json:"installation_id"`
	RepoID         *int64             `json:"repo_id"`
	Provider       string             `json:"provider"`
	ApiKeyEnc      string             `json:"api_key_enc"`
	BaseUrl        *string            `json:"base_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Repo struct {
	ID             int64              `json:"id"`
	InstallationID int64              `json:"installation_id"`
	GithubID       int64              `json:"github_id"`
	FullName       string             `json:"full_name"`
	DefaultBranch  string             `json:"default_branch"`
	Enabled        bool               `json:"enabled"`
	SettingsJson   json.RawMessage    `json:"settings_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID                 pgtype.UUID        `json:"id"`
	RepoID             int64              `json:"repo_id"`
	PrNumber           int32              `json:"pr_number"`
	PrTitle            string             `json:"pr_title"`
	PrAuthor           string             `json:"pr_author"`
	HeadSha            string             `json:"head_sha"`
	BaseSha            string             `json:"base_sha"`
	GithubReviewID     *int64             `json:"github_review_id"`
	Status             string             `json:"status"`
	Summary            *string            `json:"summary"`
	Score              *int32             `json:"score"`
	TokenUsage         []byte             `json:"token_usage"`
	Trigger            string             `json:"trigger"`
	TriggeredBy        *string            `json:"triggered_by"`
	DurationMs         *int32             `json:"duration_ms"`
	Error              *string            `json:"error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	FileCount          *int32             `json:"file_count"`
	DeepReview         bool               `json:"deep_review"`
	Persona            *string            `json:"persona"`
	IsIncremental      bool               `json:"is_incremental"`
	ResolvedStaleCount *int32             `json:"resolved_stale_count"`
	HeadRef            *string            `json:"head_ref"`
	SimulationResults  []byte             `json:"simulation_results"`
}

type ReviewComment struct {
	ID                  pgtype.UUID        `json:"id"`
	ReviewID            pgtype.UUID        `json:"review_id"`
	FilePath            string             `json:"file_path"`
	StartLine           *int32             `json:"start_line"`
	EndLine             *int32             `json:"end_line"`
	Side                *string            `json:"side"`
	Body                string             `json:"body"`
	Severity            *string            `json:"severity"`
	Category            *string            `json:"category"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CodeSnippet         *string            `json:"code_snippet"`
	GithubCommentID     *int64             `json:"github_comment_id"`
	Specialist          *string            `json:"specialist"`
	ConfidenceScore     *int32             `json:"confidence_score"`
	MatchedPatternID    *int64             `json:"matched_pattern_id"`
	MatchedPatternScore *float32           `json:"matched_pattern_score"`
	EnforcedRuleContent *string            `json:"enforced_rule_content"`
	IsNewFinding        *bool              `json:"is_new_finding"`
}

type Rule struct {
	ID        int64              `json:"id"`
	Category  string             `json:"category"`
	Content   string             `json:"content"`
	Priority  int32              `json:"priority"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Scenario struct {
	ID              int64              `json:"id"`
	InstallationID  int64              `json:"installation_id"`
	RepoID          *int64             `json:"repo_id"`
	Description     string             `json:"description"`
	Source          string             `json:"source"`
	SourceRef       *string            `json:"source_ref"`
	Files           []string           `json:"files"`
	Modules         []string           `json:"modules"`
	Severity        *string            `json:"severity"`
	Active          *bool              `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Steps           []byte             `json:"steps"`
	InitialState    *string            `json:"initial_state"`
	ExpectedOutcome *string            `json:"expected_outcome"`
	IsOutdated      *bool              `json:"is_outdated"`
	LastRunAt       pgtype.Timestamptz `json:"last_run_at"`
	TriggerCount    int32              `json:"trigger_count"`
}

type UserInstallation struct {
	ID             int64              `json:"id"`
	ClerkUserID    string             `json:"clerk_user_id"`
	InstallationID int64              `json:"installation_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
