// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package db

import (
	"context"
	"encoding/json"
)

const countEnabledRepos = `-- name: CountEnabledRepos :one
SELECT COUNT(*)::int FROM repos WHERE installation_id = $1 AND enabled = TRUE
`

func (q *Queries) CountEnabledRepos(ctx context.Context, installationID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countEnabledRepos, installationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getRepo = `-- name: GetRepo :one
SELECT id, installation_id, github_id, full_name, default_branch, enabled, settings_json, created_at, updated_at
FROM repos WHERE id = $1
`

func (q *Queries) GetRepo(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.GithubID,
		&i.FullName,
		&i.DefaultBranch,
		&i.Enabled,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByFullName = `-- name: GetRepoByFullName :one
SELECT id, installation_id, github_id, full_name, default_branch, enabled, settings_json, created_at, updated_at
FROM repos WHERE full_name = $1
`

func (q *Queries) GetRepoByFullName(ctx context.Context, fullName string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByFullName, fullName)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.GithubID,
		&i.FullName,
		&i.DefaultBranch,
		&i.Enabled,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoScoped = `-- name: GetRepoScoped :one
SELECT id, installation_id, github_id, full_name, default_branch, enabled, settings_json, created_at, updated_at
FROM repos WHERE id = $1 AND installation_id = ANY($2::bigint[])
`

type GetRepoScopedParams struct {
	ID      int64   `json:"id"`
	Column2 []int64 `json:"column_2"`
}

func (q *Queries) GetRepoScoped(ctx context.Context, arg GetRepoScopedParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoScoped, arg.ID, arg.Column2)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.GithubID,
		&i.FullName,
		&i.DefaultBranch,
		&i.Enabled,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReposScoped = `-- name: ListReposScoped :many
SELECT id, installation_id, github_id, full_name, default_branch, enabled, settings_json, created_at, updated_at
FROM repos WHERE installation_id = ANY($1::bigint[]) ORDER BY full_name
`

func (q *Queries) ListReposScoped(ctx context.Context, dollar_1 []int64) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listReposScoped, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.GithubID,
			&i.FullName,
			&i.DefaultBranch,
			&i.Enabled,
			&i.SettingsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepo = `-- name: UpdateRepo :one
UPDATE repos SET
    enabled = COALESCE($2, enabled),
    default_branch = COALESCE($3, default_branch),
    settings_json = COALESCE($4, settings_json),
    updated_at = NOW()
WHERE id = $1
RETURNING id, installation_id, github_id, full_name, default_branch, enabled, settings_json, created_at, updated_at
`

type UpdateRepoParams struct {
	ID            int64           `json:"id"`
	Enabled       bool            `json:"enabled"`
	DefaultBranch string          `json:"default_branch"`
	SettingsJson  json.RawMessage `json:"settings_json"`
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepo,
		arg.ID,
		arg.Enabled,
		arg.DefaultBranch,
		arg.SettingsJson,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.GithubID,
		&i.FullName,
		&i.DefaultBranch,
		&i.Enabled,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repos (installation_id, github_id, full_name, default_branch)
VALUES ($1, $2, $3, $4)
ON CONFLICT (github_id) DO UPDATE SET full_name = $3, default_branch = $4, updated_at = NOW()
RETURNING id, installation_id, github_id, full_name, default_branch, enabled, settings_json, created_at, updated_at
`

type UpsertRepoParams struct {
	InstallationID int64  `json:"installation_id"`
	GithubID       int64  `json:"github_id"`
	FullName       string `json:"full_name"`
	DefaultBranch  string `json:"default_branch"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, upsertRepo,
		arg.InstallationID,
		arg.GithubID,
		arg.FullName,
		arg.DefaultBranch,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.GithubID,
		&i.FullName,
		&i.DefaultBranch,
		&i.Enabled,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
