// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReviewComment = `-- name: CreateReviewComment :exec
INSERT INTO review_comments (review_id, file_path, start_line, end_line, side, body, severity, category, specialist, confidence_score, code_snippet, github_comment_id, matched_pattern_id, matched_pattern_score, enforced_rule_content, is_new_finding)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type CreateReviewCommentParams struct {
	ReviewID            pgtype.UUID `json:"review_id"`
	FilePath            string      `json:"file_path"`
	StartLine           *int32      `json:"start_line"`
	EndLine             *int32      `json:"end_line"`
	Side                *string     `json:"side"`
	Body                string      `json:"body"`
	Severity            *string     `json:"severity"`
	Category            *string     `json:"category"`
	Specialist          *string     `json:"specialist"`
	ConfidenceScore     *int32      `json:"confidence_score"`
	CodeSnippet         *string     `json:"code_snippet"`
	GithubCommentID     *int64      `json:"github_comment_id"`
	MatchedPatternID    *int64      `json:"matched_pattern_id"`
	MatchedPatternScore *float32    `json:"matched_pattern_score"`
	EnforcedRuleContent *string     `json:"enforced_rule_content"`
	IsNewFinding        *bool       `json:"is_new_finding"`
}

func (q *Queries) CreateReviewComment(ctx context.Context, arg CreateReviewCommentParams) error {
	_, err := q.db.Exec(ctx, createReviewComment,
		arg.ReviewID,
		arg.FilePath,
		arg.StartLine,
		arg.EndLine,
		arg.Side,
		arg.Body,
		arg.Severity,
		arg.Category,
		arg.Specialist,
		arg.ConfidenceScore,
		arg.CodeSnippet,
		arg.GithubCommentID,
		arg.MatchedPatternID,
		arg.MatchedPatternScore,
		arg.EnforcedRuleContent,
		arg.IsNewFinding,
	)
	return err
}

const getCommentByGithubID = `-- name: GetCommentByGithubID :one
SELECT id, review_id, file_path, start_line, end_line, side, body, severity, category,
       specialist, confidence_score, code_snippet, github_comment_id,
       matched_pattern_id, matched_pattern_score, enforced_rule_content, is_new_finding,
       created_at
FROM review_comments WHERE github_comment_id = $1
`

type GetCommentByGithubIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ReviewID            pgtype.UUID        `json:"review_id"`
	FilePath            string             `json:"file_path"`
	StartLine           *int32             `json:"start_line"`
	EndLine             *int32             `json:"end_line"`
	Side                *string            `json:"side"`
	Body                string             `json:"body"`
	Severity            *string            `json:"severity"`
	Category            *string            `json:"category"`
	Specialist          *string            `json:"specialist"`
	ConfidenceScore     *int32             `json:"confidence_score"`
	CodeSnippet         *string            `json:"code_snippet"`
	GithubCommentID     *int64             `json:"github_comment_id"`
	MatchedPatternID    *int64             `json:"matched_pattern_id"`
	MatchedPatternScore *float32           `json:"matched_pattern_score"`
	EnforcedRuleContent *string            `json:"enforced_rule_content"`
	IsNewFinding        *bool              `json:"is_new_finding"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCommentByGithubID(ctx context.Context, githubCommentID *int64) (GetCommentByGithubIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByGithubID, githubCommentID)
	var i GetCommentByGithubIDRow
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.FilePath,
		&i.StartLine,
		&i.EndLine,
		&i.Side,
		&i.Body,
		&i.Severity,
		&i.Category,
		&i.Specialist,
		&i.ConfidenceScore,
		&i.CodeSnippet,
		&i.GithubCommentID,
		&i.MatchedPatternID,
		&i.MatchedPatternScore,
		&i.EnforcedRuleContent,
		&i.IsNewFinding,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentOutcomes = `-- name: GetCommentOutcomes :many
SELECT id, review_comment_id, outcome, created_at
FROM comment_outcomes WHERE review_comment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetCommentOutcomes(ctx context.Context, reviewCommentID pgtype.UUID) ([]CommentOutcome, error) {
	rows, err := q.db.Query(ctx, getCommentOutcomes, reviewCommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentOutcome
	for rows.Next() {
		var i CommentOutcome
		if err := rows.Scan(
			&i.ID,
			&i.ReviewCommentID,
			&i.Outcome,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewComments = `-- name: GetReviewComments :many
SELECT id, review_id, file_path, start_line, end_line, side, body, severity, category,
       specialist, confidence_score, code_snippet, github_comment_id,
       matched_pattern_id, matched_pattern_score, enforced_rule_content, is_new_finding,
       created_at
FROM review_comments WHERE review_id = $1 ORDER BY file_path, start_line
`

type GetReviewCommentsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ReviewID            pgtype.UUID        `json:"review_id"`
	FilePath            string             `json:"file_path"`
	StartLine           *int32             `json:"start_line"`
	EndLine             *int32             `json:"end_line"`
	Side                *string            `json:"side"`
	Body                string             `json:"body"`
	Severity            *string            `json:"severity"`
	Category            *string            `json:"category"`
	Specialist          *string            `json:"specialist"`
	ConfidenceScore     *int32             `json:"confidence_score"`
	CodeSnippet         *string            `json:"code_snippet"`
	GithubCommentID     *int64             `json:"github_comment_id"`
	MatchedPatternID    *int64             `json:"matched_pattern_id"`
	MatchedPatternScore *float32           `json:"matched_pattern_score"`
	EnforcedRuleContent *string            `json:"enforced_rule_content"`
	IsNewFinding        *bool              `json:"is_new_finding"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetReviewComments(ctx context.Context, reviewID pgtype.UUID) ([]GetReviewCommentsRow, error) {
	rows, err := q.db.Query(ctx, getReviewComments, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewCommentsRow
	for rows.Next() {
		var i GetReviewCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.Side,
			&i.Body,
			&i.Severity,
			&i.Category,
			&i.Specialist,
			&i.ConfidenceScore,
			&i.CodeSnippet,
			&i.GithubCommentID,
			&i.MatchedPatternID,
			&i.MatchedPatternScore,
			&i.EnforcedRuleContent,
			&i.IsNewFinding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCommentOutcome = `-- name: RecordCommentOutcome :exec
INSERT INTO comment_outcomes (review_comment_id, outcome)
VALUES ($1, $2)
`

type RecordCommentOutcomeParams struct {
	ReviewCommentID pgtype.UUID `json:"review_comment_id"`
	Outcome         string      `json:"outcome"`
}

func (q *Queries) RecordCommentOutcome(ctx context.Context, arg RecordCommentOutcomeParams) error {
	_, err := q.db.Exec(ctx, recordCommentOutcome, arg.ReviewCommentID, arg.Outcome)
	return err
}
