// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
)

const getStats = `-- name: GetStats :one
SELECT
    (SELECT COUNT(*) FROM reviews)::int as total_reviews,
    (SELECT COUNT(*) FROM reviews WHERE created_at >= CURRENT_DATE AND status = 'completed')::int as completed_today,
    COALESCE((SELECT AVG(score)::int FROM reviews WHERE score IS NOT NULL), 0) as avg_score,
    (SELECT COUNT(*) FROM repos WHERE enabled = true)::int as active_repos,
    (SELECT COUNT(*) FROM review_comments WHERE severity = 'critical')::int as critical_finds,
    (SELECT COUNT(*) FROM reviews WHERE status IN ('pending','in_progress'))::int as pending_reviews,
    COALESCE((SELECT (COUNT(*) FILTER (WHERE score < 10) * 100 / NULLIF(COUNT(*) FILTER (WHERE status = 'completed'), 0))::int FROM reviews), 0) as catch_rate,
    (SELECT COUNT(*) FROM reviews WHERE created_at >= NOW() - INTERVAL '7 days')::int as prs_this_week,
    (SELECT COUNT(*) FROM reviews WHERE score IS NOT NULL AND score <= 4)::int as high_risk_count,
    COALESCE((SELECT (AVG(EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000))::int FROM reviews WHERE completed_at IS NOT NULL), 0) as avg_review_time_ms,
    (SELECT COUNT(*) FROM reviews WHERE deep_review = true)::int as deep_review_count
`

type GetStatsRow struct {
	TotalReviews    int32       `json:"total_reviews"`
	CompletedToday  int32       `json:"completed_today"`
	AvgScore        interface{} `json:"avg_score"`
	ActiveRepos     int32       `json:"active_repos"`
	CriticalFinds   int32       `json:"critical_finds"`
	PendingReviews  int32       `json:"pending_reviews"`
	CatchRate       interface{} `json:"catch_rate"`
	PrsThisWeek     int32       `json:"prs_this_week"`
	HighRiskCount   int32       `json:"high_risk_count"`
	AvgReviewTimeMs interface{} `json:"avg_review_time_ms"`
	DeepReviewCount int32       `json:"deep_review_count"`
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.TotalReviews,
		&i.CompletedToday,
		&i.AvgScore,
		&i.ActiveRepos,
		&i.CriticalFinds,
		&i.PendingReviews,
		&i.CatchRate,
		&i.PrsThisWeek,
		&i.HighRiskCount,
		&i.AvgReviewTimeMs,
		&i.DeepReviewCount,
	)
	return i, err
}

const getStatsScoped = `-- name: GetStatsScoped :one
WITH scoped_reviews AS (
    SELECT id, repo_id, pr_number, pr_title, pr_author, head_sha, base_sha, github_review_id, status, summary, score, token_usage, trigger, triggered_by, duration_ms, error, created_at, completed_at, file_count, deep_review, persona, is_incremental, resolved_stale_count, head_ref, simulation_results FROM reviews WHERE repo_id IN (SELECT id FROM repos WHERE installation_id = ANY($1::bigint[]))
)
SELECT
    (SELECT COUNT(*) FROM scoped_reviews)::int as total_reviews,
    (SELECT COUNT(*) FROM scoped_reviews WHERE created_at >= CURRENT_DATE AND status = 'completed')::int as completed_today,
    COALESCE((SELECT AVG(score)::int FROM scoped_reviews WHERE score IS NOT NULL), 0) as avg_score,
    (SELECT COUNT(*) FROM repos WHERE installation_id = ANY($1::bigint[]) AND enabled = true)::int as active_repos,
    (SELECT COUNT(*) FROM review_comments WHERE review_id IN (SELECT id FROM scoped_reviews) AND severity = 'critical')::int as critical_finds,
    (SELECT COUNT(*) FROM scoped_reviews WHERE status IN ('pending','in_progress'))::int as pending_reviews,
    COALESCE((SELECT (COUNT(*) FILTER (WHERE score < 10) * 100 / NULLIF(COUNT(*) FILTER (WHERE status = 'completed'), 0))::int FROM scoped_reviews), 0) as catch_rate,
    (SELECT COUNT(*) FROM scoped_reviews WHERE created_at >= NOW() - INTERVAL '7 days')::int as prs_this_week,
    (SELECT COUNT(*) FROM scoped_reviews WHERE score IS NOT NULL AND score <= 4)::int as high_risk_count,
    COALESCE((SELECT (AVG(EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000))::int FROM scoped_reviews WHERE completed_at IS NOT NULL), 0) as avg_review_time_ms,
    (SELECT COUNT(*) FROM scoped_reviews WHERE deep_review = true)::int as deep_review_count
`

type GetStatsScopedRow struct {
	TotalReviews    int32       `json:"total_reviews"`
	CompletedToday  int32       `json:"completed_today"`
	AvgScore        interface{} `json:"avg_score"`
	ActiveRepos     int32       `json:"active_repos"`
	CriticalFinds   int32       `json:"critical_finds"`
	PendingReviews  int32       `json:"pending_reviews"`
	CatchRate       interface{} `json:"catch_rate"`
	PrsThisWeek     int32       `json:"prs_this_week"`
	HighRiskCount   int32       `json:"high_risk_count"`
	AvgReviewTimeMs interface{} `json:"avg_review_time_ms"`
	DeepReviewCount int32       `json:"deep_review_count"`
}

func (q *Queries) GetStatsScoped(ctx context.Context, dollar_1 []int64) (GetStatsScopedRow, error) {
	row := q.db.QueryRow(ctx, getStatsScoped, dollar_1)
	var i GetStatsScopedRow
	err := row.Scan(
		&i.TotalReviews,
		&i.CompletedToday,
		&i.AvgScore,
		&i.ActiveRepos,
		&i.CriticalFinds,
		&i.PendingReviews,
		&i.CatchRate,
		&i.PrsThisWeek,
		&i.HighRiskCount,
		&i.AvgReviewTimeMs,
		&i.DeepReviewCount,
	)
	return i, err
}

const listActivity = `-- name: ListActivity :many
SELECT id, action, actor, resource, metadata, created_at
FROM activity_log ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListActivity(ctx context.Context, limit int32) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Actor,
			&i.Resource,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logActivity = `-- name: LogActivity :exec
INSERT INTO activity_log (action, actor, resource, metadata)
VALUES ($1, $2, $3, $4)
`

type LogActivityParams struct {
	Action   string  `json:"action"`
	Actor    *string `json:"actor"`
	Resource *string `json:"resource"`
	Metadata []byte  `json:"metadata"`
}

func (q *Queries) LogActivity(ctx context.Context, arg LogActivityParams) error {
	_, err := q.db.Exec(ctx, logActivity,
		arg.Action,
		arg.Actor,
		arg.Resource,
		arg.Metadata,
	)
	return err
}
