// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const getUserInstallationByUserAndInstallation = `-- name: GetUserInstallationByUserAndInstallation :one
SELECT id, clerk_user_id, installation_id, role, created_at
FROM user_installations WHERE clerk_user_id = $1 AND installation_id = $2
`

type GetUserInstallationByUserAndInstallationParams struct {
	ClerkUserID    string `json:"clerk_user_id"`
	InstallationID int64  `json:"installation_id"`
}

func (q *Queries) GetUserInstallationByUserAndInstallation(ctx context.Context, arg GetUserInstallationByUserAndInstallationParams) (UserInstallation, error) {
	row := q.db.QueryRow(ctx, getUserInstallationByUserAndInstallation, arg.ClerkUserID, arg.InstallationID)
	var i UserInstallation
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.InstallationID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserInstallationIDs = `-- name: GetUserInstallationIDs :many
SELECT installation_id FROM user_installations WHERE clerk_user_id = $1
`

func (q *Queries) GetUserInstallationIDs(ctx context.Context, clerkUserID string) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserInstallationIDs, clerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var installation_id int64
		if err := rows.Scan(&installation_id); err != nil {
			return nil, err
		}
		items = append(items, installation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkUserInstallation = `-- name: LinkUserInstallation :one
INSERT INTO user_installations (clerk_user_id, installation_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_user_id, installation_id) DO NOTHING
RETURNING id, clerk_user_id, installation_id, role, created_at
`

type LinkUserInstallationParams struct {
	ClerkUserID    string `json:"clerk_user_id"`
	InstallationID int64  `json:"installation_id"`
	Role           string `json:"role"`
}

func (q *Queries) LinkUserInstallation(ctx context.Context, arg LinkUserInstallationParams) (UserInstallation, error) {
	row := q.db.QueryRow(ctx, linkUserInstallation, arg.ClerkUserID, arg.InstallationID, arg.Role)
	var i UserInstallation
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.InstallationID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUserInstallations = `-- name: ListUserInstallations :many
SELECT i.id, i.installation_id, i.org_login, i.clerk_org_id, i.plan_tier, i.created_at, i.suspended_at
FROM installations i
JOIN user_installations ui ON ui.installation_id = i.id
WHERE ui.clerk_user_id = $1
ORDER BY i.created_at DESC
`

type ListUserInstallationsRow struct {
	ID             int64      `json:"id"`
	InstallationID int64      `json:"installation_id"`
	OrgLogin       string     `json:"org_login"`
	ClerkOrgID     *string    `json:"clerk_org_id"`
	PlanTier       string     `json:"plan_tier"`
	CreatedAt      time.Time  `json:"created_at"`
	SuspendedAt    *time.Time `json:"suspended_at"`
}

func (q *Queries) ListUserInstallations(ctx context.Context, clerkUserID string) ([]ListUserInstallationsRow, error) {
	rows, err := q.db.Query(ctx, listUserInstallations, clerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserInstallationsRow
	for rows.Next() {
		var i ListUserInstallationsRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.OrgLogin,
			&i.ClerkOrgID,
			&i.PlanTier,
			&i.CreatedAt,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
