// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ActivityLog is the predicate function for activitylog builders.
type ActivityLog func(*sql.Selector)

// Installation is the predicate function for installation builders.
type Installation func(*sql.Selector)

// ModelConfig is the predicate function for modelconfig builders.
type ModelConfig func(*sql.Selector)

// PipelineState is the predicate function for pipelinestate builders.
type PipelineState func(*sql.Selector)

// Repo is the predicate function for repo builders.
type Repo func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// ReviewComment is the predicate function for reviewcomment builders.
type ReviewComment func(*sql.Selector)

// Rule is the predicate function for rule builders.
type Rule func(*sql.Selector)
